Examples/MAX32655/Dual_core_sync/Dual_core_sync_arm/main.c, Examples/MAX32655/Dual_core_sync/Dual_core_sync_riscv/main.c, Examples/MAX78002/USB_CompositeDevice_MSC_CDC/descriptors.h, Examples/MAX78002/USB_CompositeDevice_MSC_CDC/mscmem.h, Examples/MAX78002/USB_MassStorage/descriptors.h, Examples/MAX78002/USB_MassStorage/mscmem.h, Examples/MAX78002/USB_MassStorage_ThroughPut/descriptors.h, Examples/MAX78002/USB_MassStorage_ThroughPut/mscmem.h
Fixed the linter errors in the newest examples that weren't checked in the first major pass-through.
=> Examples: Fixed linter errors.

Libraries/CMSIS/Device/Maxim/MAX32570/Source/header_MAX32570.c
Update MAX32570 SLA Header magic word
Signed-off-by: Sadik.Ozer <sadik.ozer@analog.com>
=> Fix MAX32570 SLA Header Typo

.github/workflows/ci-tests/Examples_tests/local_testLauncher.sh, .github/workflows/ci-tests/Examples_tests/resources/Serial.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_FreeRTOS.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_FreeRTOS_cs.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_dat_cs.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_datc.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_dats.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_fit.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_mcs.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_ota_cs.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_otac.robot, Examples/MAX32655/BLE_otas/test.txt
Fixes issue with failed test discarding the logging information, which is not very helpful in debugging why a test failed.
=> preserves logging of failed tests

Libraries/PeriphDrivers/Source/TRNG/trng_revb.c
TRNG RevB was waiting for the AESKG_USR bit to clear to determine when the generated AES key had finished transferring into the AESKEY registers, however the AESKG_USR bit clears after the key has finished generating not when it has finished transferring. Since the new key wasn't done transferring into the AESKEY registers by the end of the function, an encryption operation performed immediately after would only be using a partial key. This would cause data mismatches for subsequent decryption operations since by the time they were performed the key had been fully transferred into the AESKEY registers. The fix is to instead poll the AESKGD bit in the status register since it is cleared by hardware once the transfer has finished.
=> Bug fix: TRNG RevB AES key generation polling wrong status bit

Libraries/PeriphDrivers/Source/SPI/spi_me18.c
As reported in https://github.com/Analog-Devices-MSDK/msdk/issues/211 ME18 `MXC_SPI_GetPeripheralClock` was missing breaks in its switch statement and returning the incorrect clock frequency.
=> [MSDK-951] SPI ME18: Add missing break statements

Libraries/CMSIS/Device/Maxim/MAX32650/Source/system_max32650.c
ME10 has SRAM trim issue and requires setting gcr.scon[17:16]=2'b10 - for 1.1V +/- 10% on every power up which overwrites the wrong trims to the correct SRAM trims.
The ME14 also has the same issue and already has this implementation.
=> Added workaround for SRAM trim issue

Examples/MAX78000/TFT_Demo/example_config.h, Examples/MAX78000/TFT_Demo/include/state.h
TFT Demo TS issue fixed, 
Tested on MAX78000 EvKit RevC.
If there is some other TFT example which TS does not work it most probably can be fix by this type change.
Signed-off-by: Sadik.Ozer <sadik.ozer@analog.com>
=> MSDK-952: Fix TFT TS issue

Examples/MAX78002/TFT_Demo/main.c, Libraries/Boards/MAX32655/EvKit_V1/Include/board.h, Libraries/Boards/MAX32655/EvKit_V1/Source/board.c, Libraries/Boards/MAX78000/EvKit_V1/Include/board.h, Libraries/Boards/MAX78000/EvKit_V1/Source/board.c, Libraries/Boards/MAX78002/EvKit_V1/Include/board.h, Libraries/Boards/MAX78002/EvKit_V1/Source/board.c, Libraries/Boards/MAX78002/EvKit_V1/board.mk, Libraries/MiscDrivers/Touchscreen/tsc2046.c, Libraries/MiscDrivers/Touchscreen/tsc2046.h
This PR adds touchscreen support for the AI87 EVKIT (tsc2046.c)
The SPI transport layer had to be moved out of the tsc2046.c file and into the board files.  The AI87 EVKIT requires software control of the Chip Select pin, and additionally does not have the TS_BUSY signal routed, so its SPI transport function differs completely from the old one.
Currently, the drivers and hardware works but there is a mismatch between the TFT display's coordinate system and the touchscreen's.  This can most likely be fixed in software by post-processing the X,Y coordinates returned from the touchscreen to match the TFT.  I've already tried swapping x,y values alongside various `FLIP_SCREEN` and `ROTATE_SCREEN` combinations, but haven't successfully matched the correct coordinates yet.
=> Add Touch Screen Support for AI87 EVKIT + NewHaven TFT

Libraries/CMSIS/Device/Maxim/MAX32662/Include/max32662.svd, Libraries/CMSIS/Device/Maxim/MAX32662/Include/pwrseq_regs.h, Libraries/PeriphDrivers/Source/LP/lp_me12.c, Libraries/PeriphDrivers/Source/LP/pwrseq_me12.svd
ME12 doesn't have a port 1, so PWRSEQ LPWKFL1 and LPWKEN1 registers should be removed.
=> ME12: Removed LP registers relating to non-existent port 1.

Libraries/CMSIS/Device/Maxim/MAX32675/Include/max32675.svd, Libraries/CMSIS/Device/Maxim/MAX32675/Include/pwrseq_regs.h, Libraries/PeriphDrivers/Source/LP/pwrseq_me16.svd, Libraries/PeriphDrivers/Source/SYS/sys_me15.c, Libraries/PeriphDrivers/Source/SYS/sys_me21.c
The B revisions of the MAX32670 and MAX32672 have a new RTC enable bit in the PWRSEQ register.  This PR properly configures this bit when enabling/disabling the ERTCO.
=> Configure ERTCO enable bit.

Examples/MAX78000/CameraIF/project.mk, Examples/MAX78000/CameraIF_Debayer/project.mk, Examples/MAX78000/TFT_Demo/example_config.h, Examples/MAX78000/TFT_Demo/main.c, Examples/MAX78000/TFT_Demo/src/state_home.c, Examples/MAX78000/TFT_Demo/src/state_info.c, Examples/MAX78000/TFT_Demo/src/state_keypad.c, Libraries/MiscDrivers/Display/tft_ili9341.h
- Remove hard-coded inclusions of the EVKIT's TFT header file in state machine files
- Set `TFT_ENABLE` by default in example_config.h
- Remove TS_ENABLE for FTHR board (no drivers, demo holds after TFT test finishes)
- Reduce ili_9341 driver speed back to 10Mhz
The project should now build cleanly with `make BOARD=FTHR_RevA`
```shell
❯ make BOARD=FTHR_RevA
Loaded project.mk
CC    resources/tft_fthr/Arial12x12.c
CC    resources/tft_fthr/Arial24x23.c
CC    resources/tft_fthr/Arial28x28.c
CC    resources/tft_fthr/SansSerif16x16.c
CC    resources/tft_fthr/SansSerif19x19.c
CC    resources/tft_fthr/img_1_rgb565.c
CC    main.c
CC    src/state.c
CC    src/state_home.c
CC    src/state_info.c
CC    src/state_keypad.c
CC    src/utils.c
CC …
```
=> AI85 TFT_Demo: Fix build issue for BOARD=FTHR_RevA, enable TFT by default

Libraries/CMSIS/Device/Maxim/MAX32670/Source/GCC/max32670.ld, Libraries/CMSIS/Device/Maxim/MAX32670/Source/GCC/max32670_ram.ld, Libraries/CMSIS/Device/Maxim/MAX32670/Source/GCC/max32670_spix.ld, Libraries/CMSIS/Device/Maxim/MAX32672/Source/GCC/max32672.ld, Libraries/CMSIS/Device/Maxim/MAX32672/Source/GCC/max32672_ram.ld, Libraries/CMSIS/Device/Maxim/MAX32672/Source/GCC/max32672_scpa.ld, Libraries/CMSIS/Device/Maxim/MAX32672/Source/GCC/max32672_sla.ld, Libraries/CMSIS/Device/Maxim/MAX32675/Source/GCC/max32675.ld, Libraries/CMSIS/Device/Maxim/MAX32675/Source/GCC/max32675_ram.ld, Libraries/CMSIS/Device/Maxim/MAX32675/Source/GCC/max32675_spix.ld
New revisions of the ME15-based parts now come with ECC-enabled by default.  This reduces the overall SRAM space, as ECC requires complete ownership of the last few sysram instances.
Our linkerfiles previously did not take this into account.  As a result, startup code would cause a HardFault as the stack as expanded into the reserved ECC space on newer die revisions.
This PR re-configures the ME15, ME16, and ME21 linkerfiles to assume that ECC is enabled by default.  It reduces SRAM to the sizes specified in each parts datasheet for ECC-enabled.
Several linkerfiles (_spix, _rom, etc.) also appear to be completely unused and unmaintained.  We should address these in a later PR
=> Fix ME15, ME16, ME21 SRAM Sections for ECC

Examples/MAX32670/Flash/main.c, Examples/MAX32670/Flash_CLI/main.c, Examples/MAX32670/LP/main.c, Examples/MAX32670/WearLeveling/main.c, Libraries/PeriphDrivers/Source/RTC/rtc_me15.c, Libraries/PeriphDrivers/Source/SYS/sys_me15.c
(Flash, Fash_CLI) The ME15 RTC initialization code was failing on Rev B parts.  Rev B requires a different bit for RTC clock enable, so the ME15 RTC drivers now call the SYS driver function that properly enables the RTC clock on both revisions.  See https://github.com/Analog-Devices-MSDK/msdk/commit/e6a271a8f136f24815b8a4cc2d8b543585027e7a
(RTC, RTC_Backup) New revisions of the ME15 also enable ECC by default, which caused the Flash examples to fail.  On those examples, ECC has been completely disabled.  See https://github.com/Analog-Devices-MSDK/msdk/commit/c2cbe716dde9be66c5918e749017d230e1d9c34c https://github.com/Analog-Devices-MSDK/msdk/pull/253/commits/e8ab4f7b8541ed5b6e22d4759825e782d0376b90
(LP) Disable RAM sleep/shutdown.  It broke the example, and power savings are minimal …
=> Fix ME15 RTC Bug, Disable ECC for Flash Examples, Fix LP

Examples/MAX78000/CameraIF/README.md, Examples/MAX78000/CameraIF/main.c, Examples/MAX78002/CameraIF/README.md, Examples/MAX78002/CameraIF/main.c, Examples/MAX78002/CameraIF_Debayer/README.md, Examples/MAX78002/CameraIF_Debayer/main.c, Examples/MAX78002/CameraIF_Debayer/project.mk, Libraries/MiscDrivers/Camera/hm0360_mono.c
The primary purpose of this PR is to apply the same integration time improvements from https://github.com/Analog-Devices-MSDK/Libraries-miscDrivers/pull/14 to the HM0360 _mono_ drivers as well.  The register config change in the mono drivers (https://github.com/Analog-Devices-MSDK/msdk/commit/7a52b65acf74320febc27d66931d87740a47b18e) reduces the time required to capture a single image down from 800ms to about 65ms, a 1230% improvement.
This change uncovered some other issues in the camera examples:
* A README has been added to CameraIF for the AI85
* Disable streaming by default for the AI85 CameraIF example.  The TFT cannot keep up with the reduced integration time, but there is enough SRAM for a full buffered image capture, which actually performs better.
* HM0360_COLOR `#ifdefs` have …
=> Reduce HM0360_MONO Integration Time, Fix Camera->TFT For AI87

Examples/MAX32655/BLE_otas/dats_main.c, Examples/MAX32665/BLE_otas/dats_main.c, Examples/MAX32690/BLE_otas/dats_main.c
This includes the parameter update struct into the OTAS application which is useful when dealing with slower devices or strict ios parameters.
Found this useful when using my python application and I think this will help when using the IOS app for OTA updates, since the turkey reports disconnects because of timeouts. 
The timeouts are a result of the external flash erase taking longer than the BLE stack likes.
=> add connection parameter update to OTAS projects.

Tools/Bluetooth/BLE_hci.py
Prevents us from trying to open a None serial port and starting another thread.
=> Ignoring monitor serial if None.

.github/workflows/BLE_Examples_Test.yml, .github/workflows/ci-tests/Examples_tests/resources/serialPortReader.py, .github/workflows/ci-tests/Examples_tests/test_launcher.sh, .github/workflows/ci-tests/Examples_tests/tests/BLE_FreeRTOS.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_dat_cs.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_datc.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_dats.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_fit.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_mcs.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_ota_cs.robot, .github/workflows/ci-tests/Examples_tests/tests/BLE_otac.robot, Libraries/Cordio/platform/targets/maxim/max32655/sources/pal_timer.c
-This will pass once the 32Khz fix is made and merged into main and then main merged into this
- script accepts 3 parameters now as follows:
- device  under test in lower caps  eg:  max32655
- device serial port serial eg: DT309ZDF
- CMSIS dap serial : 4440920139230423408230424312233
- uses board_config.json to find devices instead of hard coded serial numbers
- for BLE_datc/s connected test there is a short timeout period required to enter then pin
sometimes if flashing took too long the timeout would pass. Now the script flashes them at the same time
so that they start up closer to each other and have time to enter the pin.
-
=> Ci tests update

.github/workflows/ci-tests/Examples_tests/test_launcher.sh
This is to disable ci-test for `BLE_fit` and `BLE_freeRTOS` examples for ME18 which are still a work in progress. Will be re-enabled once we get them working well.  This is related to #321 which still eludes us.
=> Disable ci-test for ME18 examples that are WIP

Libraries/CMSIS/Device/Maxim/MAX32572/Include/max32572.svd, Libraries/CMSIS/Device/Maxim/MAX32572/Include/ptg_regs.h, Libraries/CMSIS/Device/Maxim/MAX32662/Include/max32662.svd, Libraries/CMSIS/Device/Maxim/MAX32662/Include/pt_regs.h, Libraries/CMSIS/Device/Maxim/MAX32662/Include/ptg_regs.h, Libraries/CMSIS/Device/Maxim/MAX32690/Include/max32690.svd, Libraries/CMSIS/Device/Maxim/MAX32690/Include/owm_regs.h, Libraries/CMSIS/Device/Maxim/MAX32690/Include/pt_regs.h, Libraries/CMSIS/Device/Maxim/MAX32690/Include/ptg_regs.h, Libraries/PeriphDrivers/Include/MAX32572/pt.h, Libraries/PeriphDrivers/Include/MAX32662/pt.h, Libraries/PeriphDrivers/Include/MAX32690/pt.h, Libraries/PeriphDrivers/Source/PT/pt_me12.c, Libraries/PeriphDrivers/Source/PT/pt_me18.c, Libraries/PeriphDrivers/Source/PT/pt_me55.c, Libraries/PeriphDrivers/Source/PT/pt_reva.c, Libraries/PeriphDrivers/Source/PT/pt_reva.h, Libraries/PeriphDrivers/Source/PT/ptg_reva1_16pt.svd, Libraries/PeriphDrivers/Source/PT/ptg_reva1_4pt.svd, Libraries/PeriphDrivers/Source/PT/ptg_reva1_8pt.svd, Libraries/PeriphDrivers/Source/PT/ptg_reva2_16pt.svd, Libraries/PeriphDrivers/Source/PT/ptg_reva2_4pt.svd, Libraries/PeriphDrivers/Source/PT/ptg_reva2_8pt.svd, Libraries/PeriphDrivers/Source/PT/ptg_reva_regs.h
The ME12, ME18, and ME55 will have two more interrupt registers: READY_INTFL (0x18) and READY_INTEN (0x1C). I've renamed the original two interrupt registers: INTFL -> STOP_INTFL (0x08) and INTEN -> STOP_INTEN (0x0C). The ME18 and ME55 are unreleased, and I got the go-ahead to update the ME12 PTG register names.
=> PTG: Added READY and STOP registers for ME12, ME18, and ME55.

Libraries/PeriphDrivers/Source/SPI/spi_reva.c
The status variable "async" in spi_reva.c was getting overwritten by other SPI requests. Thus, if the SPI request which set the status variable to "1" had not completed yet, the callback function would not be called. To protect against this, I moved it into the spi_reva_req_state_t struct. This prevents a SPI instance from overwriting another's "async" status.
=> SPI RevA: Fixing async status variable overwrite.

.github/workflows/BLE_Examples_Test.yml
Would be beneficial to not run BLE_test on branches that are in draft, because the constant commits cause the boards to be hogged up to the PR.
Author can make all their commits in draft mode, and when they are ready to merge they can get PR out of draft mode.
Alternatively they can take it out of draft mode at anytime to test their progress.
=> do not run hardware test if PR is draft

Libraries/CMSIS/Device/Maxim/MAX32672/Include/max32672.h
aes_key_regs.h was included in max32672.h from a previous deprecated change with the AES/ECC/TRIMSIR peripherals. This line should have been removed when the AESKEYS were scrubbed.
=> ME21: Removed aes_key_regs.h inclusion from max32672.h.

Tools/Bluetooth/dtm_sweep.py, Tools/Bluetooth/dtm_sweep_vs.py
The number of packets was defaulted as an int type not a string so the strip function was failing. Not sure why this was never picked up in original tests.
=> fixed bug in dtm sweep causing CI test to fail

Libraries/MiscDrivers/ExtMemory/w25.c
I saw a similar issue with erase function in mx25 driver few months ago  https://github.com/Analog-Devices-MSDK/Libraries-miscDrivers/pull/10/files
This pr increases timeout on the reset function for w25. 
We dont see this issue with EvKits but on the FTHR board it times out.
fixes #376
=> increase busy count

Examples/MAX32672/LP/lp.ld, Examples/MAX32672/LP/main.c
This PR updates the linkerfile used for the MAX32672 LP example. SRAM 2 and 3 is shutdown in the example so the SRAM usage needs to be contained in SRAM 0 and 1.
=> [MSDK-1042]: Resolving hardfault in MAX32672 LP example.

Libraries/Cordio/controller/build/ble5-ctr/gcc/makefile, Libraries/Cordio/platform/targets/nordic/sources/pal_cfg.c
Nordic device getting hard fault with HCI UART traffic. Works okay with limited traffic, but hard fault occurs with heavy traffic in automated tests.
``` c
0x00028982 in SystemDefaultHandler () at ../../../../platform/targets/nordic/build/startup_gcc_nrf52840.c:313
313   while (forever);
(gdb) bt
#0  0x00028982 in SystemDefaultHandler () at ../../../../platform/targets/nordic/build/startup_gcc_nrf52840.c:313
#1  <signal handler called>
#2  0x000227f8 in LctrRxIso () at ../../../../controller/sources/ble/lctr/lctr_main_iso.c:676
#3  0x00023de8 in LlRecvIsoData () at ../../../../controller/sources/ble/ll/ll_main_iso.c:143
#4  0x00023c6e in lhciRecvIso () at ../../../../controller/sources/ble/lhci/lhci_evt_iso.c:131
#5  0x00017c20 in lhciService (pType=0x2003ff59 "", pLen=0x2003ff5a, …
```
=> Setting default BT_VER to 9.

Libraries/CMSIS/Device/Maxim/MAX32520/Include/i2c_regs.h, Libraries/PeriphDrivers/Source/I2C/i2c_reva_es17.svd
This PR changes the I2C slave address offset from 0x44 and 0x4C. This fix was tested while adding EEPROM_Emulator example.
=> MAX32520: Fixing I2C slave address register offset.

Libraries/PeriphDrivers/Source/ADC/adc_reva.c
Data returned from the following function is not correct. 
https://github.com/Analog-Devices-MSDK/msdk/blob/27e4f783a8c5ea709aabad22633a3a4e1f6dd097/Libraries/PeriphDrivers/Source/ADC/adc_reva.c#L328
The cast shown below causes the format of the value to be messed up.
https://github.com/Analog-Devices-MSDK/msdk/blob/27e4f783a8c5ea709aabad22633a3a4e1f6dd097/Libraries/PeriphDrivers/Source/ADC/adc_reva.c#L355
Instead of declaring the data as an int, I swiched to uint16_t to avoid this issue. Casting it as an int upon return fixes this issue and the data matches, the data coming from _MXC_ADC_GetData_
I haven't looked at the other revisions of the driver, but it is probably in them as well. 
The example doesn't catch this issue, because MXC_ADC_GetData is used directly.
=> REV A ADC Driver Fix

.github/workflows/ci-tests/Examples_tests/test_launcher.sh, Examples/MAX32655/BLE_datc/datc_main.c, Examples/MAX32655/BLE_otac/datc_main.c, Examples/MAX32655/BLE_otas/wdxs_file_ext.c, Examples/MAX32655/BLE_otas/wdxs_file_int.c, Examples/MAX32665/BLE_datc/datc_main.c, Examples/MAX32665/BLE_otac/datc_main.c, Examples/MAX32665/BLE_otas/wdxs_file_ext.c, Examples/MAX32665/BLE_otas/wdxs_file_int.c, Examples/MAX32690/BLE_datc/datc_main.c, Examples/MAX32690/BLE_otac/datc_main.c, Examples/MAX32690/BLE_otas/wdxs_file_int.c
- If client fails to discover **any** service the example will not work as intended so disconnect. 
- Minor refactor of magic number used in function call
- Removes erase function of a board that is no longer on wall-e causing BLE test jobs to fail
=> minor refactor

Libraries/Boards/MAX78002/EvKit_V1/Source/board.c
This PR initializes some pins that are pulled up to 3v3 on the MAX780002EVKIT.  The board startup file has been modified to set VSSEL of these pins to VDDIOH.
---
From [MSDK-927](https://jira.maxim-ic.com/browse/MSDK-927)
8 GPIOs are configured to use VDDIO (1.8V), but are pulled up to 3V3 via 10kohm resistors on the AI87 external EVKit. This injects current into the VDDIO/VDDA node and causes it to rise to about 2.4V in Standby, Backup and PowerDown modes.
Pin          Resistor
P0.0       R110
P1.10     R98
P1.11     R95
P1.12     R94
P1.13     R93
P1.14     R93
P1.16     R96
P2.2       R104
=> Initialize some pins to VDDIOH on MAX78002EVKIT, MSDK-927

Libraries/Boards/MAX32570/Source/tft.c, Libraries/Boards/MAX32572/Source/tft.c, Libraries/Boards/MAX32655/Source/tft.c, Libraries/MiscDrivers/Display/tft_ssd2119.c
See MSDK-1061.  The TFT driver did not properly handle the case where there is no code/data placed in the .bin_storage section.  The fix was to initialize the image data structure so that the number of bitmaps, fonts, and palettes are initialized to 0.  All functions were then checked to make sure they confirmed the image ID they were asked to use was less than then number of objects.
=> Resolve TFT Null Pointer issue.

.github/workflows/scripts/plot_per_results.py, Tools/Bluetooth/conn_sweep.py
And allow to test rx power less than -90 dBm.
=> Make a faster PER test

.github/workflows/Generate_Register_Files.yml, Libraries/PeriphDrivers/Source/UART/uart_reva_me14.svd
This PR was originally used to test the new "Generate_Register_Files" workflow, but I encountered an unexpected behavior running on the BTM-CI that needs to be resolved before I can test.
The runner shares the same workspace on the BTM-CI, and some repos weren't cleaned out before the runner picked up another job. Adding a guard around git clones is the best thing to get around leftover repos.
=> Generate_Register_Files Workflow Test

.github/workflows/Build_Examples.yml
This should fix the Python post-setup failure (ex https://github.com/Analog-Devices-MSDK/msdk/actions/runs/4389485741/jobs/7687079761) in the Build Examples action as per https://github.com/actions/setup-python/issues/475
=> Build Action:  Fix Unexpected End of JSON Input

Examples/MAX32655/Hello_World-riscv/main_riscv.c, Examples/MAX32680/Hello_World-riscv/main_riscv.c, Examples/MAX78002/CNN/imagenet-riscv/main.c
After adding missing RISC-V config files in https://github.com/Analog-Devices-MSDK/openocd/pull/18, functional testing revealed some stragglers.
* The `Hello_World-riscv` projects would never signal the M4 core
* `imagenet-riscv` for the AI87 never triggered the M4 core's ISR.  (https://github.com/MaximIntegratedAI/ai8x-synthesis/pull/284 not merged yet)
=> Fix RISC-V Debug Functional Test Errors

Examples/MAX32655/BLE_otas/wdxs_file_ext.c, Examples/MAX32665/BLE_otas/wdxs_file_ext.c
If CRC fails for some reason erase external flash so that on next boot the device does not find a fw update.
=> Erase ext flash on failed status

.github/workflows/BLE_Examples_Test.yml, .github/workflows/scripts/mass_erase_board.sh
-check to see which boards needs testing
-if at least one needs testing it locks all 3 because its safer and a lot of issues arose when only locking one and waiting for others
-test all boards
-And lastly does a mass erase of any locked boards before unlocking. **Does this at the yaml level so if test script is interrupted because of a canceled workflow the board will still be left in a known state.**
=> implements script to mass erase devices upon unlock

Libraries/PeriphDrivers/Include/MAX32570/cameraif.h, Libraries/PeriphDrivers/Include/MAX32570/mxc_pins.h, Libraries/PeriphDrivers/Source/CAMERAIF/cameraif_me13.c, Libraries/PeriphDrivers/Source/CAMERAIF/cameraif_reva.c, Libraries/PeriphDrivers/Source/SYS/pins_me13.c
MSDK-1075: MAX32570 camera interface update
P1.7 is connected to camera on EvKits (M/Q, MN/QN)
Tested with CameraIF and BarcodeDecoder example it works.
=> Update MAX32570 camera interface

.github/workflows/README.md
Fixing typos and updating the README for our workflows. Any documentation on using any of the workflows can be added here as well.
=> Workflows: Fixed typos in README.

Examples/MAX32655/Hello_World/Makefile, Libraries/CMSIS/Device/Maxim/MAX32520/Source/GCC/max32520.mk, Libraries/CMSIS/Device/Maxim/MAX32570/Source/GCC/max32570.mk, Libraries/CMSIS/Device/Maxim/MAX32572/Source/GCC/max32572.mk, Libraries/CMSIS/Device/Maxim/MAX32650/Source/GCC/max32650.mk, Libraries/CMSIS/Device/Maxim/MAX32655/Source/GCC/max32655.mk, Libraries/CMSIS/Device/Maxim/MAX32660/Source/GCC/max32660.mk, Libraries/CMSIS/Device/Maxim/MAX32662/Source/GCC/max32662.mk, Libraries/CMSIS/Device/Maxim/MAX32665/Source/GCC/max32665.mk, Libraries/CMSIS/Device/Maxim/MAX32670/Source/GCC/max32670.mk, Libraries/CMSIS/Device/Maxim/MAX32672/Source/GCC/max32672.mk, Libraries/CMSIS/Device/Maxim/MAX32675/Source/GCC/max32675.mk, Libraries/CMSIS/Device/Maxim/MAX32680/Source/GCC/max32680.mk, Libraries/CMSIS/Device/Maxim/MAX32690/Source/GCC/max32690.mk, Libraries/CMSIS/Device/Maxim/MAX78000/Source/GCC/max78000.mk, Libraries/CMSIS/Device/Maxim/MAX78002/Source/GCC/max78002.mk, Tools/Flash/flash.mk
This will allow us to ```make flash.openocd```.
I added another target for JLink ```make flash.jlink```. This isn't a part of our SDK, but I know that some of our customers prefer this to OpenOCD. 
What do we think of the file path and include in the Makefile?
=> Adding Makefile targets for flashing.

Libraries/CMSIS/Device/Maxim/MAX32655/Source/GCC/gcc.mk, Libraries/CMSIS/Device/Maxim/MAX32665/Source/GCC/gcc.mk, Libraries/CMSIS/Device/Maxim/MAX32680/Source/GCC/gcc.mk, Libraries/CMSIS/Device/Maxim/MAX32690/Source/GCC/gcc.mk, Libraries/CMSIS/Device/Maxim/MAX78000/Source/GCC/gcc.mk
This will address the same issue we had with linking the .elf files. The command line list of argmuents is too long on Windows machines. This will echo those arguments to a text file and use that file as the input the the archiver.
=> Building archives with text file arguments.

Examples/MAX32672/LP/README.md, Examples/MAX32672/LP/main.c
This PR adds instructions in the MAX32672 LP example README on how to configure the EV kit to achieve low power measurements that match what is listed in the datasheet. Additionally, a function was added in the example code that sets all GPIOs low except for the SWD pins, and the push button/UART pins if they are in use.
=> Modifying MAX32672 LP example to get lowest current measurements.

Libraries/PeriphDrivers/Include/MAX32520/i2c.h, Libraries/PeriphDrivers/Include/MAX32570/i2c.h, Libraries/PeriphDrivers/Include/MAX32572/i2c.h, Libraries/PeriphDrivers/Include/MAX32650/i2c.h, Libraries/PeriphDrivers/Include/MAX32655/i2c.h, Libraries/PeriphDrivers/Include/MAX32660/i2c.h, Libraries/PeriphDrivers/Include/MAX32662/i2c.h, Libraries/PeriphDrivers/Include/MAX32665/i2c.h, Libraries/PeriphDrivers/Include/MAX32670/i2c.h, Libraries/PeriphDrivers/Include/MAX32672/i2c.h, Libraries/PeriphDrivers/Include/MAX32675/i2c.h, Libraries/PeriphDrivers/Include/MAX32680/i2c.h, Libraries/PeriphDrivers/Include/MAX32690/i2c.h, Libraries/PeriphDrivers/Include/MAX78000/i2c.h, Libraries/PeriphDrivers/Include/MAX78002/i2c.h, Libraries/PeriphDrivers/Source/I2C/i2c_ai87.c, Libraries/PeriphDrivers/Source/I2C/i2c_es17.c, Libraries/PeriphDrivers/Source/I2C/i2c_me11.c, Libraries/PeriphDrivers/Source/I2C/i2c_me12.c, Libraries/PeriphDrivers/Source/I2C/i2c_me13.c, Libraries/PeriphDrivers/Source/I2C/i2c_me14.c, Libraries/PeriphDrivers/Source/I2C/i2c_me15.c, Libraries/PeriphDrivers/Source/I2C/i2c_me16.c, Libraries/PeriphDrivers/Source/I2C/i2c_me17.c, Libraries/PeriphDrivers/Source/I2C/i2c_me18.c, Libraries/PeriphDrivers/Source/I2C/i2c_me21.c, Libraries/PeriphDrivers/Source/I2C/i2c_me55.c
MXC_I2C_RevA_AsyncStop and MXC_I2C_RevA_AbortAsync were already implemented; support for calling these functions from each of the chip specific header/source files is added in this PR.
=> Add MXC_I2C_AsyncStop and MXC_I2C_AbortAsync Functions

.github/workflows/BLE_Examples_Test.yml, .github/workflows/scripts/test_launcher.sh
- adds more filtering to the library sources so that we do not run BLE test when for example something like an LCD library is changed, I think I have included all the peripherals used in BLE examples  for each chip which  are GPIO, TRNG, SIMO, LP, AES, FLC, TIMER, WUT , UART , SYS. So changes to those drivers on the specific part will trigger BLE test.
- Also separated Erase board into its own step seprate from locking boards, because I noticed the lock step would successfully lock boards but if it failed to erase a board then the step is considered failed and it would not unlock boards. This fixes that.
- Finally this checks out the specific RF PHY closed branch that can work with the new chips on the ME17 Evkits on wallle. This is a temp fix until we merge that all into BLEPhy
=> Ble test filtering

.github/workflows/scripts/test_launcher.sh, Libraries/Cordio/ble-profiles/sources/af/app_disc.c
Currently RF PHY for ME17B needs debugging, datc/s and otac/s connected states  are unreliable right now.
Waiting for early next week to have Evkits reworked with ME17B to debug.
=> Temporary disable datc/s and otas/c connected state tests

Examples/MAX78000/WearLeveling/README.md, Examples/MAX78000/WearLeveling/WearLeveling.launch, Examples/MAX78000/WearLeveling/include/cli.h, Examples/MAX78000/WearLeveling/include/file.h, Examples/MAX78000/WearLeveling/include/flash.h, Examples/MAX78000/WearLeveling/include/main.h, Examples/MAX78000/WearLeveling/main.c, Examples/MAX78000/WearLeveling/project.mk, Examples/MAX78000/WearLeveling/src/cli.c, Examples/MAX78000/WearLeveling/src/file.c, Examples/MAX78000/WearLeveling/src/flash.c
This PR makes changes to the existing WearLeveling example to explicitly demonstrate the flash wear leveling ability of the LittleFS library. Additionally, it builds upon the previous example by adding a command line interface that allows users to read and write files interactively.
Note: Once this PR is approved and merged, this example will be ported to all other micros in a separate PR.
=> MAX78000: Updating WearLeveling example to explicitly show flash wear leveling.

.github/workflows/Build_Examples.yml, Libraries/CMSIS/Device/Maxim/MAX32672/Include/gcr_regs.h
The old "check watch files" implementation seemed to have some issues with case sensitivity.  The new implementation from @jdk-maxim seems to be much more reliable.
Fixes #566 
Manual run on fork works great:  https://github.com/Jake-Carter/msdk/actions/runs/4886879634/jobs/8722797077
This PR should trigger a build based on its test commit as well.
=> Build Workflow:  Update Check Watch Files Implementation

Libraries/PeriphDrivers/Source/RTC/rtc_reva.c
This PR resolves the build warnings reported by GEHC where we were testing whether a uint32_t was less than 0. The variables which were involved in these comparison are now changed to type int.
=> RTC RevA: Resolving warnings in TrimCrystal function when testing if unsigned integer is negative.

Libraries/PeriphDrivers/Source/SPI/spi_reva.c
A customer reported that the MXC_SPI_RevA_SetTXThreshold function would accept values 0 and 32 (which gets masked off to 0) for the threshold parameter. Setting the threshold value to 0 is invalid because both the TX_THD interrupt and DMA_TX transactions are triggered when the FIFO count drops BELOW the threshold, therefore the interrupt and DMA transaction will never get triggered with this setting.
This PR updates the MXC_SPI_RevA_SetTXThreshold to only allow threshold values between 0x1 and 0x1f and also updates the calls to SetTXThreshold to use valid values.
Additionally, while I was looking into this bug I discovered that the MXC_SPI_RevA_SetRXThreshold function allowed threshold values greater than 30 which is also an invalid setting. So I have also updated …
=> SPI Rev. A: Updating SetTXThreshold and SetRXThreshold to only accept valid threshold values.

Libraries/PeriphDrivers/Source/FLC/flc_me11.c
MAX32660 base address is 0x0, casting it to a pointer causes null pointer access
So that instead of reading page 0-1 read page 1-2 to update cache
=> MSDK-1118: FLC:  Fix Null Pointer Bug for MAX32660 Flash Base Address

USERGUIDE.md, mkdocs.yml
The VSCode-Maxim repo used to have a page in the wiki that showed the die type to part number conversion, which was useful for navigating the peripheral driver code. 
When the wiki was moved and its content merged with the User Guide, that section appears to have not been migrated. This PR adds the same conversion table from the old wiki to [the 'Peripheral Driver API > Organization' section of the User Guide](https://analog-devices-msdk.github.io/msdk/USERGUIDE/#organization). 
To build properly, `mkdocs.yml` was also modified slightly to enable the markdown table extension. 
The `Documentation\build.py` script was run locally and a screenshot of the relevant section from the generated `docs\USERGUIDE\index.html` is shown below:
=> Add die type to part number conversion table to User Guide

Libraries/PeriphDrivers/Include/MAX32520/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32570/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32572/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32650/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32655/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32660/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32662/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32665/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32670/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32672/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32675/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32680/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32690/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX78000/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX78002/mxc_sys.h, Libraries/PeriphDrivers/Source/UART/uart_reva.c
This PR fix below issues:
#1
C:/MaximSDK/Libraries/PeriphDrivers/Include/MAX32650/mxc_sys.h:250:78: error: narrowing conversion of '4294967295' from 'unsigned int' to 'int' [-Wnarrowing]
#2
=> MSDK-1167: Fix build issues

Libraries/PeriphDrivers/Source/FLC/flc_me13.c
When updating the Flash and WearLeveling examples for the MAX32570, I discovered the examples would hang in MXC_FLC_ME13_Flash_Operation while waiting for the ICC0_Flush flag to clear. This PR fixes this bug by flushing the SFCC and ICC individually with their respective flush functions, instead of using the global cache invalidation bit in the GCR registers.
=> MSDK-1116: Preventing MAX32570 applications from hanging in MXC_FLC_ME13_Flash_Operation.

Libraries/MiscDrivers/ExtMemory/mx25.c, Libraries/MiscDrivers/ExtMemory/w25.c
Prevents the timeout variable from being optimized out.
Not sure why now and not before, but I am seeing consistent failed write page operations during OTA because of
"busy" state. This fixes the issue.
=> MiscDrivers: Adds volatile qualifier to variable used in ext flash

Libraries/PeriphDrivers/Source/TMR/tmr_reva.c
Below warnings occurs when MXC_ASSERT_ENABLE not defined.
=> MSDK-171: Fix warnings for MXC_ASSERT_ENABLE not defined cases

Libraries/CMSIS/Device/Maxim/MAX32520/Include/max32520.h, Libraries/CMSIS/Device/Maxim/MAX32570/Include/max32570.h, Libraries/CMSIS/Device/Maxim/MAX32572/Include/max32572.h, Libraries/CMSIS/Device/Maxim/MAX32650/Include/max32650.h, Libraries/CMSIS/Device/Maxim/MAX32655/Include/max32655.h, Libraries/CMSIS/Device/Maxim/MAX32660/Include/max32660.h, Libraries/CMSIS/Device/Maxim/MAX32662/Include/max32662.h, Libraries/CMSIS/Device/Maxim/MAX32665/Include/max32665.h, Libraries/CMSIS/Device/Maxim/MAX32670/Include/max32670.h, Libraries/CMSIS/Device/Maxim/MAX32672/Include/max32672.h, Libraries/CMSIS/Device/Maxim/MAX32675/Include/max32675.h, Libraries/CMSIS/Device/Maxim/MAX32680/Include/max32680.h, Libraries/CMSIS/Device/Maxim/MAX32690/Include/max32690.h, Libraries/CMSIS/Device/Maxim/MAX78000/Include/max78000.h, Libraries/CMSIS/Device/Maxim/MAX78002/Include/max78002.h
Some third party libraries/stack has __weak define.
While using SDK files with third party stack/libs, redefinition cases occurs.
=> MSDK-1170: Add include guard for __weak

Libraries/PeriphDrivers/Source/UART/uart_reva.c, Libraries/PeriphDrivers/Source/UART/uart_revb.c
As reported in [ticket #594](https://github.com/Analog-Devices-MSDK/msdk/issues/594), the UART request structure wasn't saved before the interrupts were enabled in MXC_UART_RevX_TransactionAsync; if there was an interrupt pending then execution would jump to the ISR without the information in the the request structure. This PR updates the TransactionAsync functions for UART Rev. A and B to save the request structure before interrupts are enabled.
Note: this change is not relevant for UART Rev. C because it implements this function differently.
=> fix(PeriphDrivers): Issue #594: Save UART transaction requests before enabling interrupts

Examples/MAX32670/LP/main.c
Sets all unused GPIO pins to input mode with pull-down enabled.
=> perf(Examples): Change GPIO settings in MAX32670 LP example to improve current consumption

Libraries/PeriphDrivers/Include/MAX32572/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32655/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32662/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32665/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32670/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32672/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32675/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32680/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32690/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX78000/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX78002/mxc_sys.h, Libraries/PeriphDrivers/Source/SYS/sys_ai85.c, Libraries/PeriphDrivers/Source/SYS/sys_ai87.c, Libraries/PeriphDrivers/Source/SYS/sys_es17.c, Libraries/PeriphDrivers/Source/SYS/sys_me10.c, Libraries/PeriphDrivers/Source/SYS/sys_me11.c, Libraries/PeriphDrivers/Source/SYS/sys_me12.c, Libraries/PeriphDrivers/Source/SYS/sys_me13.c, Libraries/PeriphDrivers/Source/SYS/sys_me14.c, Libraries/PeriphDrivers/Source/SYS/sys_me15.c, Libraries/PeriphDrivers/Source/SYS/sys_me17.c, Libraries/PeriphDrivers/Source/SYS/sys_me18.c, Libraries/PeriphDrivers/Source/SYS/sys_me21.c, Libraries/PeriphDrivers/Source/SYS/sys_me55.c
This PR includes improvements to the MXC_SYS_GetUSN function for all micros.
Changes in this PR include:
1. Adding code that verifies the checksum.
2. Adds a check for NULL usn/serialNumber pointers.
3. Fixes invalid calls MXC_FLC_UnlockInfoblock.
=> refactor(PeriphDrivers): Update MXC_SYS_GetUSN to verify the checksum (and fix some minor bugs)

.github/workflows/Stale_PR.yml
This new workflow will keep track of open PRs, mark them as stale after 30 days of inactivity, and closes them 7 days after the PR was marked as stale. Inactivity usually means no comments, commits, reviews, or label changes for 30 days. When a PR becomes stale, the action will comment a warning message and add a stale label to the PR. 
If the PR has a new comment, commit, review, or label change, then the stale label will be automatically removed and the PR's 30-day active interval will be reset. If no activity was detected, then the action will comment the PR has been inactive for 7 days before closing the PR.
Stale settings:
- Runs every 2 hrs every day (could change interval if needed)
- 30 Days before PR is stale
- 7 Days before PR is closed after 30-day stale warning
- PRs with …
=> feat(workflow): Add new workflow to check for stale Pull Requests

Examples/MAX32572/WearLeveling/src/cli.c, Examples/MAX32650/WearLeveling/src/cli.c, Examples/MAX32655/WearLeveling/src/cli.c, Examples/MAX32660/WearLeveling/src/cli.c, Examples/MAX32662/WearLeveling/src/cli.c, Examples/MAX32665/WearLeveling/src/cli.c, Examples/MAX32670/WearLeveling/src/cli.c, Examples/MAX32672/WearLeveling/src/cli.c, Examples/MAX32675/WearLeveling/src/cli.c, Examples/MAX32680/WearLeveling/src/cli.c, Examples/MAX32690/WearLeveling/src/cli.c, Examples/MAX78000/WearLeveling/src/cli.c, Examples/MAX78002/WearLeveling/src/cli.c
The command line interface of the Wear leveling examples for all Micros did not echo characters back to the terminal.
Described in the [MSDK-1184](https://jira.maxim-ic.com/browse/MSDK-1184).
The fix adds a UART write to the console passing in the character that is entered by the user.
=> feat(Examples): MSDK-1184 Add Local Echo to WearLeveling Examples

Examples/MAX78000/WearLeveling/src/cli.c
Below are the bugs fixed in the Wear Leveling CLI example: -
1. Handling Back Space input.
2. Handling Tab Space input.
3. Handling Arrow key input.
4. Handling abort input.
5. Handling Leading spaces input.
6. Included Macros for ASCII equivalent to increase readability. 
Included Sanity check for the input commands. 
NOTE:- This code uses memmove() function to copy data in the overlapping memory segment.
=> fix(Examples): MSDK-1184 Fix CLI bugs in Wear Leveling example.

Examples/MAX78000/Flash_CLI/main.c
1. Fixed the leading spaces issue in the Flash CLI (1st issue in the ticket).  
2. Removed magic numbers and included relevant ASCII equivalent with Macros.  
3. Included few more check to avoid unwanted echo statements (2nd issue in the ticket).  
Corresponding Jira ticket is [here](https://jira.maxim-ic.com/browse/MSDK-1192)  
Note: - Line 236 (index != 0) in the updated code would resolve the second issue in the ticket.
=> fix(Examples): MSDK-1192: Fix Leading Spaces issue in the Flash CLI example

Examples/MAX32650/I2C/main.c, Examples/MAX32655/I2C/main.c, Examples/MAX32660/I2C/main.c, Examples/MAX32662/I2C/main.c, Examples/MAX32665/I2C/main.c, Examples/MAX32670/I2C/main.c, Examples/MAX32672/I2C/main.c, Examples/MAX32675/I2C/main.c, Examples/MAX32680/I2C/main.c, Examples/MAX32690/I2C/main.c, Examples/MAX78002/I2C/main.c
Many of the I2C examples had the logic flipped for checking the return value of the verifyData function. verifyData returns E_NO_ERROR if the transaction was successful, but that would cause the program flow to print out a transaction failed message.
=> fix(Examples): Fix return value logic for verifyData function in I2C examples

Examples/MAX32655/BLE_dats/dats_main.c, Examples/MAX32665/BLE_dats/dats_main.c, Examples/MAX32690/BLE_dats/dats_main.c
Adds some visual feedback that packets are indeed being received on the sever side. Someone emailed me about throughput and was wondering if packets are indeed being received on the other side in this speed test.
=> fix(BLE,Examples): Log packet count on BLE dats speed test

Documentation/CONTRIBUTING.md, Examples/MAX32662/ADC/main.c, Examples/MAX32672/ADC/main.c, Examples/MAX32690/ADC/main.c, Examples/MAX78002/ADC/main.c, Libraries/CMSIS/Device/Maxim/MAX32662/Include/max32662.h, Libraries/CMSIS/Device/Maxim/MAX32672/Include/max32672.h, Libraries/CMSIS/Device/Maxim/MAX32690/Include/max32690.h, Libraries/CMSIS/Device/Maxim/MAX78002/Include/max78002.h, Libraries/PeriphDrivers/Include/MAX32662/adc.h, Libraries/PeriphDrivers/Include/MAX32672/adc.h, Libraries/PeriphDrivers/Include/MAX32690/adc.h, Libraries/PeriphDrivers/Include/MAX78002/adc.h, Libraries/PeriphDrivers/Source/ADC/adc_revb.c
Fixed the DMA transfer over multiple channels for ADC example in the MAX32672 board, and the corresponding JIRA ticket is [here](https://jira.maxim-ic.com/projects/MSDK/issues/MSDK-1218?filter=allopenissues)
This PR contains the fix for all example codes that uses ADC Rev B, which includes MAX32662, MAX32672, MAX32690, MAX78002.
=> fix(Examples)!: Require DMA Channel as Input Argument for ADC DMA Conversions, Fix ADC DMA Transfer Bug for Channels > 0

.github/workflows/Release.yml
This PR creates a new workflow just for created GitHub releases.
It packages up the `Examples`, `Libraries` and `Tools` folders for use elsewhere without having to download the whole repository or download the complete installer (or just to update your examples etc. without having to go through a complete re-install).
This could later be expanded on to use the same workflow for bundling the installer automatically within Actions.
I created a dummy release on the fork to test the action: https://github.com/ALofthou/msdk/releases/tag/Test_Release
=> feat(workflow): Add new workflow for Releases

Examples/MAX32572/Barcode_Decoder/src/utils.c, Examples/MAX32572/CameraIF/src/utils.c, Examples/MAX32572/MAX32572_Demo_BareMetal/src/utils.c, Examples/MAX32572/MAX32572_Demo_FreeRTOS/src/utils.c, Examples/MAX32572/TFT_Demo/src/utils.c, Examples/MAX32572/lwIP_Ping/main.c, Examples/MAX32572/lwIP_TCP/main.c, Examples/MAX32655/TFT_Demo/src/utils.c, Examples/MAX78000/CNN/faceid_evkit-riscv/src/utils.c, Examples/MAX78000/CNN/faceid_evkit/src/utils.c, Examples/MAX78000/CNN/facial_recognition/src/utils.c, Examples/MAX78000/CameraIF/utils.c, Examples/MAX78000/TFT_Demo/src/utils.c, Examples/MAX78002/CNN/faceid_evkit/src/utils.c, Examples/MAX78002/CNN/pascalvoc-retinanetv7_3/src/cnn/nms.c, Examples/MAX78002/CSI2/utils.c, Examples/MAX78002/CameraIF/utils.c
I goofed when fixing the utils_get_time_ms functions to use MXC_RTC_GetSubSeconds(...) for the latest release by removing the double type (ssec value is a 12-bit register field value).
=> fix(Examples): Fix double-type subseconds calculation for MAX32655, MAX78000, and MAX78002

.github/pull_request_template.md, .github/workflows/Build_Examples.yml, .github/workflows/PR_Title_Check.yml, .github/workflows/patch/glob_patch.patch, .github/workflows/scripts/build.py, Libraries/CMSIS/Device/Maxim/GCC/gcc.mk, Libraries/CMSIS/Device/Maxim/GCC/gcc_riscv.mk, Libraries/MiscDrivers/Camera/mipi_camera.c, commitlint.config.js
The [`$(file)` operation](https://www.gnu.org/software/make/manual/make.html#File-Function) that was being used to generate our `project_defines.h` header file (as of #628) was only supported on Make v3.82 or newer.  As a result, v3.81 or older would throw the following error:
```bash
arm-none-eabi-gcc.exe: error: C:/Users/JCarter3/repos/fork/msdk/Examples/MAX78000/CNN/mnist-riscv/build/_empty_tmp_file.c: No such file or directory
arm-none-eabi-gcc.exe: fatal error: no input files
compilation terminated.
make[1]: *** [/C/Users/JCarter3/repos/fork/msdk/Libraries/CMSIS/Device/Maxim/GCC/gcc.mk:508: /c/Users/JCarter3/repos/fork/msdk/Examples/MAX78000/CNN/mnist-riscv/build/project_defines.h] Error 1
make: *** [Makefile:56: arm] Error 2
```
This PR replaces the operation with an `echo` command …
=> fix(Build): Fix "empty.c file not found" Error on Make v3.81 or Older

.github/workflows/scripts/build.py, Libraries/libs.mk
BLE builds fail when MFLOAT_ABI = hard, e.g. with macOS 12.6.7:
```
khp@Kevins-MacBook-Pro-M1 BLE_periph_20230718 % make all VERBOSE=1 BOARD=FTHR PROJECT=BLE_periph_20230718 TARGET=MAX32665 MFLOAT_ABI=hard
.
.
.
arm-none-eabi-gcc @/Users/khp/Dropbox/Projects/Documents/MXC/Examples/BLE_periph_20230718/build/ln_args.txt
/usr/local/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: error: /Users/khp/Dropbox/Projects/Documents/MXC/Examples/BLE_periph_20230718/build/BLE_periph_20230718.elf uses VFP register arguments, /Users/khp/Dropbox/Projects/Documents/MXC/Examples/msdk/Libraries/BlePhy/MAX32665/libphy.a(pal_bb.o) does not
```
Changed libs.mk to select libphy_hard.a when appropriate.
=> fix(Build): Link with libphy_hard.a when MFLOAT_ABI = hard

Libraries/PeriphDrivers/Source/SPI/spi_reva1.c
This PR reduces the code size for the spi_reva1 implementation by 1.2KB by removing unnecessary assertions to validate the SPI register instance in every function.
Doing it once in the init struct is sufficient.  See https://github.com/Analog-Devices-MSDK/msdk/pull/674 for further discussion.
```diff
text    data     bss     dec     hex filename
<    5610             0      80    5690    163a spi_reva1.o (ex build/PeriphDriver/libPeriphDriver_softfp.a)
---
>    4413             0      80    4493    118d spi_reva1.o (ex build/PeriphDriver/libPeriphDriver_softfp.a)
```
=> perf(PeriphDrivers): Reduce SPI_RevA Code Size

Libraries/PeriphDrivers/Include/MAX32520/spi.h, Libraries/PeriphDrivers/Include/MAX32570/spi.h, Libraries/PeriphDrivers/Include/MAX32572/spi.h, Libraries/PeriphDrivers/Include/MAX32650/spi.h, Libraries/PeriphDrivers/Include/MAX32655/spi.h, Libraries/PeriphDrivers/Include/MAX32660/spi.h, Libraries/PeriphDrivers/Include/MAX32662/spi.h, Libraries/PeriphDrivers/Include/MAX32665/spi.h, Libraries/PeriphDrivers/Include/MAX32670/spi.h, Libraries/PeriphDrivers/Include/MAX32672/spi.h, Libraries/PeriphDrivers/Include/MAX32675/spi.h, Libraries/PeriphDrivers/Include/MAX32680/spi.h, Libraries/PeriphDrivers/Include/MAX32690/spi.h, Libraries/PeriphDrivers/Source/SPI/spi_es17.c, Libraries/PeriphDrivers/Source/SPI/spi_me10.c, Libraries/PeriphDrivers/Source/SPI/spi_me11.c, Libraries/PeriphDrivers/Source/SPI/spi_me12.c, Libraries/PeriphDrivers/Source/SPI/spi_me13.c, Libraries/PeriphDrivers/Source/SPI/spi_me14.c, Libraries/PeriphDrivers/Source/SPI/spi_me15.c, Libraries/PeriphDrivers/Source/SPI/spi_me16.c, Libraries/PeriphDrivers/Source/SPI/spi_me17.c, Libraries/PeriphDrivers/Source/SPI/spi_me18.c, Libraries/PeriphDrivers/Source/SPI/spi_me21.c, Libraries/PeriphDrivers/Source/SPI/spi_me55.c, Libraries/PeriphDrivers/Source/SPI/spi_reva1.c, Libraries/PeriphDrivers/Source/SPI/spi_reva1.h
While using SPI manual chip drive requires, existing SPI driver drive SS pin by HW, there is no any option to disable this behaviour, This feature exactly require while porting Zephyr/MBED... On these platform i add an patch at the top of SDK layer.
It will be nice if SDK support it on default.
=> feat(PeriphDrivers): Provide user a way to manually drive SPI slave select pin

Examples/MAX32520/Flash/main.c, Examples/MAX32572/Flash/main.c, Examples/MAX32650/Flash/main.c, Examples/MAX32655/Flash/main.c, Examples/MAX32660/Flash/main.c, Examples/MAX32662/Flash/main.c, Examples/MAX32665/Flash/main.c, Examples/MAX32670/Flash/main.c, Examples/MAX32672/Flash/main.c, Examples/MAX32675/Flash/main.c, Examples/MAX32680/Flash/main.c, Examples/MAX32690/Flash/main.c, Examples/MAX78000/Flash/main.c, Examples/MAX78002/Flash/main.c
In the last release we fixed a Flash read bug in the Flash examples by changing this line of code to use void* typecast instead of a uint32_t* typecast. That change solved the bug in the code but introduced a build error on the IAR/Keil side. The solution to both of these problems is to use MXC_FLC_Read instead of the call to memcpy.
=> fix(Examples): Update Flash examples to use MXC_FLC_Read to resolve IAR/Keil build errors

README.md
As pointed out in https://github.com/MaximIntegratedAI/refdes/issues/50, modifying `msys.bat` is not the right way to change `MAXIM_PATH` on windows.  `setenv.bat` should be used instead.
=> fix(Documentation): Fix Incorrect README Instructions for CLI Repo Setup 

Libraries/CMSIS/Device/Maxim/MAX78000/Source/GCC/max78000.mk, Libraries/CMSIS/Device/Maxim/MAX78002/Source/GCC/max78002.mk
As of #653 some build errors starting showing up in the auto-tester, but just for the AI85 Aud01_RevA BSP.  (ex [here](https://github.com/Analog-Devices-MSDK/msdk/actions/runs/5802135079/job/15727888491?pr=702), [here](https://github.com/Analog-Devices-MSDK/msdk/actions/runs/5802113840/job/15727822359?pr=703))
This turned out to be an issue with parallel builds.  RV_ARM_Loader for the AI85/AI87 failed for other boards with `make -r -j`, but randomly.  The rule for creating `riscv_common.ld` seems to have an incomplete dependency tree.  I tried several solutions to make the dependency tree more explicit, but nothing seemed to work.  The file operations for parsing the .map file for the RISC-V boot address always had some chance of modifying files that were being worked on by other parallel …
=> fix(Build): Disable Parallel Execution When Creating common_riscv.ld for `RISCV_LOAD=1`

Libraries/CMSIS/Device/Maxim/MAX32670/Include/max32670.svd, Libraries/CMSIS/Device/Maxim/MAX32670/Include/trng_regs.h
The incorrect SVD file was used to generate the ME15's trng_regs.h file. Also, the ME15 only has one AES key.
=> fix(CMSIS): Regenerate trng_regs.h using correct SVD file for MAX32670

Examples/MAX32655/ADC/main.c, Examples/MAX32680/ADC/main.c
In some driver versions, MXC_ADC_StartConversion directly returns the adc value. However, it may also returns an MXC error which can be negative. The data type of the adc value was unsigned. Therefore, the comparison is always false. This changes the type information such that the comparison can be made.
=> fix(Examples): Type overflow in ADC example

Libraries/PeriphDrivers/Source/I2C/i2c_reva.c
An FAE requested that the MXC_I2C_GetFrequency function returns the frequency of the I2C bus in HS mode. This PR adds this functionality.
=> feat(PeriphDrivers): Return HS frequency from MXC_I2C_GetFrequency when HS-Mode enabled

Examples/MAX78000/CameraIF/pc_utility/imgConverter.py, Examples/MAX78000/CameraIF_Debayer/pc_utility/imgConverter.py, Examples/MAX78000/CameraIF_Debayer/pc_utility/temo/imgConverter.py, Examples/MAX78000/ImgCapture/main.c, Examples/MAX78000/ImgCapture/utils/imgConverter.py, Examples/MAX78002/CNN/pascalvoc-retinanetv7_3/utils/imgConverter.py, Examples/MAX78002/CSI2/utils/imgConverter.py, Examples/MAX78002/CameraIF/pc_utility/imgConverter.py, Examples/MAX78002/CameraIF_Debayer/pc_utility/imgConverter.py, Examples/MAX78002/ImgCapture/main.c, Examples/MAX78002/ImgCapture/utils/imgConverter.py
Fixes #681 
There was a typo in the `rgb888_to_rgb` conversions.  They assumed 3 byte RGB sequences.  However, for RGB888 conversions the camera drivers enforce FIFO_THREE_BYTE, which outputs a 4-byte word with the MSB filled with 0.
Before:
After (ceiling tile ftw):
=> fix(Examples): Fix ImgCapture RGB888 Conversions

Libraries/PeriphDrivers/Source/SYS/sys_ai85.c, Libraries/PeriphDrivers/Source/SYS/sys_ai87.c
This PR fixes the `-Wcast-align` errors for the MAX78000 & MAX78002 USN calculations.  Our AES struct enforces 32-bit data alignment, so this solution uses an intermediate buffer and `memcpy`'s out to the user's buffers.
```shell
- CC /home/jakecarter/repos/fork/msdk/Libraries/CMSIS/../PeriphDrivers/Source/SYS/sys_ai85.c
/home/jakecarter/repos/fork/msdk/Libraries/CMSIS/../PeriphDrivers/Source/SYS/sys_ai85.c: In function 'MXC_SYS_GetUSN':
/home/jakecarter/repos/fork/msdk/Libraries/CMSIS/../PeriphDrivers/Source/SYS/sys_ai85.c:120:29: warning: cast increases required alignment of target type [-Wcast-align]
120 |         aes_req.inputData = (uint32_t *)usn;
|                             ^
/home/jakecarter/repos/fork/msdk/Libraries/CMSIS/../PeriphDrivers/Source/SYS/sys_ai85.c:121:30: warning: …
```
=> fix(PeriphDrivers): Fix `-Wcast-align` warning for MAX78000 & MAX78002 SYS Drivers

Examples/MAX32690/GPIO/main.c, Libraries/Boards/MAX32690/EvKit_V1/Source/board.c
Fixes #705 
This PR defines weak default handlers for the ports used by the pushbutton and GPIO example on the MAX32690 EVKIT.
The MAX32690 GPIO example has also been updated to be less reliant on these weak handlers, and to be less confusing in general.
GPIO Example now functions on the MAX32690EVKIT (LED1 blinks when PB0 is pressed).
=> fix(Boards, Examples): Fix MAX32690 GPIO Example 

Libraries/CMSIS/Device/Maxim/GCC/gcc_riscv.mk
This PR enables the compressed instruction set extension by default for RISC-V builds.  `MARCH` has been changed from `rv32im_zicsr_zifencei` to `rv32imc_zicsr_zifencei`.
This reduces the code size of RISC-V builds.
@rotx-maxim has also reported some performance improvements when using the compressed instruction set, so it seems (at least for now) that there are not significant performance vs code-size tradeoffs.
**Uncompressed AI85 PeriphDriver Size**
```
text    data     bss     dec     hex filename
4       0       0       4       4 mxc_assert.o (ex /home/jakecarter/repos/fork/msdk/Libraries/PeriphDrivers/bin/MAX78000/softfp_riscv/libPeriphDriver_softfp.a)
128       0       0     128      80 mxc_delay.o (ex /home/jakecarter/repos/fork/msdk/Libraries/PeriphDrivers/bin/MAX78000/softfp_risc …
```
=> perf(Build): Set Compressed Instruction Set as Default for RISC-V

Libraries/PeriphDrivers/Include/MAX32655/lpcmp.h, Libraries/PeriphDrivers/Include/MAX32680/lpcmp.h, Libraries/PeriphDrivers/Include/MAX32690/lpcmp.h, Libraries/PeriphDrivers/Include/MAX78000/lpcmp.h, Libraries/PeriphDrivers/Include/MAX78002/lpcmp.h
The `MXC_LPCMP_POL_RISE` and `MXC_LPCMP_POL_FALL` enumeration values are used to set the polarity setting for the LPCMP. However, they weren't explicitly set with the values 0 and 1, respectively, which can cause the H->L transition setting to be selected when using the `MXC_LPCMP_POL_RISE` enum value (should be `MXC_LPCMP_POL_FALL` that selects the H->L transition setting) and vice versa.
=> fix(PeriphDrivers): Explicitly set the LPCMP Polarity Setting (Rising/Falling)

Libraries/Boards/MAX32662/EvKit_V1/Include/board.h, Libraries/Boards/MAX32672/EvKit_V1/Include/board.h, Libraries/Boards/MAX32690/EvKit_V1/Include/board.h, Libraries/CMSIS/Device/Maxim/MAX32520/Source/system_max32520.c, Libraries/CMSIS/Device/Maxim/MAX32570/Source/system_max32570.c, Libraries/CMSIS/Device/Maxim/MAX32572/Source/system_max32572.c, Libraries/CMSIS/Device/Maxim/MAX32572/Source/system_riscv_max32572.c, Libraries/CMSIS/Device/Maxim/MAX32650/Source/system_max32650.c, Libraries/CMSIS/Device/Maxim/MAX32655/Source/system_max32655.c, Libraries/CMSIS/Device/Maxim/MAX32655/Source/system_riscv_max32655.c, Libraries/CMSIS/Device/Maxim/MAX32660/Source/system_max32660.c, Libraries/CMSIS/Device/Maxim/MAX32662/Source/system_max32662.c, Libraries/CMSIS/Device/Maxim/MAX32665/Source/system_max32665.c, Libraries/CMSIS/Device/Maxim/MAX32670/Source/system_max32670.c, Libraries/CMSIS/Device/Maxim/MAX32672/Source/system_max32672.c, Libraries/CMSIS/Device/Maxim/MAX32675/Source/system_max32675.c, Libraries/CMSIS/Device/Maxim/MAX32680/Source/system_max32680.c, Libraries/CMSIS/Device/Maxim/MAX32680/Source/system_riscv_max32680.c, Libraries/CMSIS/Device/Maxim/MAX32690/Source/system_max32690.c, Libraries/CMSIS/Device/Maxim/MAX32690/Source/system_riscv_max32690.c, Libraries/CMSIS/Device/Maxim/MAX78000/Source/system_max78000.c, Libraries/CMSIS/Device/Maxim/MAX78000/Source/system_riscv_max78000.c, Libraries/CMSIS/Device/Maxim/MAX78002/Source/system_max78002.c, Libraries/CMSIS/Device/Maxim/MAX78002/Source/system_riscv_max78002.c
The newlib implementation from GCC 12 depends on `_getpid` and `_kill` in some places.  Attempting to link any project using GCC 12 throws the following warnings.
```shell
/home/jakecarter/MaximSDK/Tools/GNUTools/12.3/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/bin/ld: /home/jakecarter/MaximSDK/Tools/GNUTools/12.3/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/softfp/libc.a(libc_a-signalr.o): in function `_getpid_r':
signalr.c:(.text._getpid_r+0x0): warning: _getpid is not implemented and will always fail
/home/jakecarter/MaximSDK/Tools/GNUTools/12.3/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/bin/ld: /home/jakecarter/MaximSDK/Tools/GNUTools/12.3/bin/../lib/gcc/arm-none-eabi/12.3.1/../../../../arm-none-eabi/lib/thumb/v7e …
```
=> fix(CMSIS, PeriphDrivers): Fix "warning: _kill/_getpid is not implemented and will always fail" on GCC 12

Libraries/CMSIS/Device/Maxim/GCC/gcc.mk, Libraries/CMSIS/Device/Maxim/GCC/gcc_riscv.mk
This PR fixes `.elf has a LOAD segment with RWX permissions` warnings that pop up on GCC 12.  This is a new warning added because RWX memory sections are theoretically vulnerable to security attacks.  We execute code out of SRAM frequently (most common use-case being ISRs), so this PR disables the warning via `--no-warn-rwx-segments`.
The most complicated part is detecting whether we have GCC 12+.  `--no-warn-rwx-segments` is not supported by earlier versions, or for GCC 12 from xPack.
=> fix(Build): Fix ".elf has a LOAD segment with RWX permissions" Linker Warning on GCC 12+

.github/workflows/clang-format-run-pr.yml
The other actions don't re-trigger whenever the clang-format-run workflow successfully commits the newly formatted files. That's because the repo is checked out using the built-in, default `GITHUB_TOKEN` secret. GitHub sees the bot push event as something generated by the CI instead of by an actual user, and GitHub has set up checks where any event by the CI does not re-trigger any of the other actions to avoid unintentional check loops.
The fix, **hopefully**, is to set up a personal access token secret, within the scope of the repo, with permissions to re-trigger all the checks whenever the clang-format-run workflow successfully commits the formatted files. Also due to the fact the workflow is PR-comment triggered, there are no worries about any unintentional check loops caused by this …
=> fix(workflow): Add token secret to clang-format-run workflow to retrigger other actions upon successful completion

Examples/MAX32665/USB_CDCACM/main.c
COM20; i.e USB serial device, was showing "_**This device cannot start.(Code 10)**_" error. Therefore, it was not operating successfully.
Applying the below changes made the example work properly.
* `acm_cfg.out_maxpacket = config_descriptor.endpoint_descriptor_1.wMaxPacketSize = 64`
* `acm_cfg.in_maxpacket = config_descriptor.endpoint_descriptor_2.wMaxPacketSize = 64`
* `acm_cfg.notify_maxpacket = config_descriptor.endpoint_descriptor_3.wMaxPacketSize = 64`
=> fix(Examples): Fix 'this device cannot start COM port' error in MAX32665 USB_CDCACM example

Libraries/Cordio/platform/targets/maxim/max32665/sources/pal_flash.c
The PalFlashEraseSector function comments and behavior are that of a `byte` erase function which is incorrect. The function is called assuming size is in terms of `sectors`  which it should be. In the function below `PalFlashEraseSector` is passed a value of `1` to erase one sector at a time, `PalFlashEraseSector` then decrements `1 -MXC_FLASH_PAGE_SIZE` and causes size to  underflow and the number becomes really big since it is unsigned and the function erases lots of sectors causing application to crash and be unrecoverable. 
``` 
void WsfNvmEraseDataAll(WsfNvmCompEvent_t compCback)
{
for (uint32_t eraseAddr = WSF_NVM_START_ADDR; eraseAddr < wsfNvmCb.availAddr; eraseAddr += wsfNvmCb.sectorSize) {
PalFlashEraseSector(1, eraseAddr);
}
wsfNvmCb.availAddr = WSF_NVM_START_ADDR;
if …
```
=> fix(BLE): Fix PalFlashEraseSector, Decrement Erase by Sector Size

Examples/MAX32670/SPI/main.c
Tested all MAX32670 examples for the September '23 release. Only found a bug in the SPI example when the ISR vector was not set and the example would hang in the default SPI0 IRQ handler. This PR just adds the MXC_NVIC_SetVector call in the SPI example.
=> fix(Examples): Bug fix for MAX32670 SPI example

Libraries/SDHC/Include/sdhc_lib.h, Libraries/SDHC/Source/sdhc_lib.c
`unsigned int MXC_SDHC_Lib_GetCapacity(mxc_sdhc_csd_regs_t* csd)` function returns wrong value.
If 32 GB card is inserted to the SD card slot, `MXC_SDHC_Lib_GetCapacity` function can return at most *UINT32_MAX* as a result.
Therefore, the function prototype is changed to `unsigned long long MXC_SDHC_Lib_GetCapacity(mxc_sdhc_csd_regs_t* csd)` to get the correct result.
`unsigned int MXC_SDHC_Lib_GetSectors(mxc_sdhc_csd_regs_t* csd, int i)` function is implemented in *sdhc_lib.c* file.
=> fix(SDHC): Fix SDHC Get Capacity and Implement Get Sectors functionality 

Libraries/SDHC/Include/sdhc_lib.h
Remove definition of SDHC_CLK_FREQ to resolve SDHC library multiple definitions build warning.
=> fix(SDHC): Remove second definition of SDHC_CLK_FREQ in sdhc_lib.h to resolve build warning

Libraries/MiscDrivers/ExtMemory/Ext_Flash.h, Libraries/MiscDrivers/ExtMemory/w25.c
I bumped into this minor issue recently, thought I would pass it along.
Also fixed a typo in declaration of Ext_Flash_Block_WP().
=> fix(MiscDrivers): Allow valid param `address + txlen <= W25_DEVICE_SIZE` when calling Ext_Flash_Program_Page()

Libraries/CMSIS/Device/Maxim/MAX32680/Source/GCC/max32680.ld
Add missing flashprog statement to .data section.  Without it the flash erase and write functions were located in Flash causing a HardFault to occur whenever they were executed.
=> fix(Build): Add statement to MAX32680 linker description file placing flash functions in SRAM

Examples/MAX78002/SPI_ControllerTarget/main.c, Examples/MAX78002/TFT_Demo/Makefile, Examples/MAX78002/TFT_Demo/project.mk, Libraries/PeriphDrivers/Include/MAX78002/spi.h, Libraries/PeriphDrivers/Source/SPI/spi_reva1.c
- Fix SPI FIFO register access which can cause the swapped message ordering for some parts (e.g. Transmitting or receiving the expected `00 01 02 03` message results in `01 00 03 02`).
- Add missing SPI_ControllerTarget ssIdx selection on AI87
- Remove leftover comments in AI87 spi.h
- Fix TFT_Demo makefile changes.
=> fix(Examples,PeriphDrivers): Fix SPI FIFO register access causing swapped message ordering and other minor fixes

Examples/MAX32680/Watchdog/main.c
Decrease the delay in the watchdog example so it will trigger the "too early" reset.
=> fix(Examples): Decrease the delay in the MAX32680 Watchdog example to force a watchdog reset to occur

Examples/MAX32655/RTC/main.c, Examples/MAX32655/RTC_Backup/main.c
The RTC and RTC_Backup example for the ME17 had some weird register-level initialization of the ERFO, which somehow reset the board and prevented the examples from running.
Replacing it with API calls fixes the problem and the examples run cleanly.
=> fix(Examples): Fix RTC and RTC_Backup Example ERFO Initialization for MAX32655

Libraries/PeriphDrivers/Source/I2C/i2c_reva.c
A customer reported that they were seeing the I2C callback function being called early when an I2C transaction with another slave device was executed before the master initiated an I2C transaction with our micro. Upon inspection it was discovered that the I2C will always assert the STOP flag when a stop condition is detected on the bus even if our micro is not the slave device involved in the I2C communication. When our micro received an address match the handler logic would think that the transaction had been completed and would immediately enter the callback function.
This PR adds a logic block to clear the STOP interrupt flag if it has been asserted as a result of a separate I2C transaction and re-arranges logic blocks in the I2C handler to avoid entering the callback function …
=> fix(PeriphDrivers): MSDK-1242: Fix false stop detection in I2C interrupt handler

Libraries/Cordio/platform/targets/maxim/build/cordio.mk, Libraries/Cordio/platform/targets/maxim/max32655/sources/pal_flash.c, Libraries/Cordio/platform/targets/maxim/max32665/sources/pal_flash.c, Libraries/Cordio/platform/targets/maxim/max32690/sources/pal_flash.c
Deeper look into this, the original fix in #726 was for `PalFlashEraseSector` since this is called by `WsfNvmEraseDataAll` and was caught at some point. However nothing calls `PalFlashEraseChip` , nonetheless PAL_NVM_SIZE should be a multiple of MXC_FLASH_PAGE_SIZE
Fixes #771
=> fix(BLE,Build): Fix default PAL_NVM_SIZE, add compiler checks for NVM erase functions

Examples/MAX32655/BLE_periph/README.md, Examples/MAX32665/BLE_periph/README.md, Examples/MAX32690/BLE_periph/README.md
Updated documentation for BLE_periph example noting the application shows bear bones use. 
Documents issue brought up in  #710
BLE_periph is a bare bones example with no security features and therefore is not guaranteed to connect to platforms like IOS or Android. The example is intended to be used with loosely controlled embedded devices for demonstration purposes only.
=> docs(BLE): Updated documentation regarding BLE_periphs intentional use case

Libraries/CMSIS/Device/Maxim/MAX32690/Include/max32690.svd, Libraries/PeriphDrivers/Source/SPI/spi_me18.c
* Fixed typos in SPI request select for SPI3 and SPI4. It was preventing SPI transactions from working in DMA mode for MAX32690GWE+
* Added updated SVD file for debugging MAX32690GWE+. Peripherals SPI3 and SPI4 were missing.
=> fix(PeriphDrivers,CMSIS): SBISYS-216: Fix typos in SPI Rx Request Select, new SVD file for MAX32690

Libraries/PeriphDrivers/Include/MAX32650/uart.h, Libraries/PeriphDrivers/Include/MAX32665/uart.h, Libraries/PeriphDrivers/Source/UART/uart_me10.c, Libraries/PeriphDrivers/Source/UART/uart_me14.c, Libraries/PeriphDrivers/Source/UART/uart_reva.c
While updating the MAX32650 SDHC_FAT example to use the new CLI library it was discovered that the UART Rev. A driver did not allow async transactions to be initiated from the UART callback function, a mechanism that the CLI library heavily relies on. The faulty behavior was caused by the driver calling the callback function before stopping the transaction. Calling the functions in this order disables interrupts immediately after enabling them in MXC_UART_TransactionAsync, meaning the CLI would never  detect when another character had been received. 
This PR updates the UART Rev. A library to call the callback function after the previous transaction has been stopped, thereby allowing for the next async transaction to be initiated in the callback function. While I was making those I …
=> refactor(PeriphDrivers): Update UART Rev. A to support TransactionAsync calls from callback function

Libraries/PeriphDrivers/Include/MAX32672/mxc_pins.h, Libraries/PeriphDrivers/Include/MAX32672/uart.h, Libraries/PeriphDrivers/Source/SYS/pins_me21.c, Libraries/PeriphDrivers/Source/UART/uart_me21.c
Closes #733 
Adds `MXC_UART_SetPinMapping` and `MXC_UART_GetPinMapping` for the MAX32672, and pin definitions to pins_me21.c.
Setter should be called _before_ UART_Init...
```C
MXC_UART_SetPinMapping(MXC_UART0, MAP_B);
MXC_UART_Init(MXC_UART0, ...);
// ...
```
Also fixed UART2A mapping being incorrect.  It was pointing to UART2B...
=> feat(PeriphDrivers): Add Ability to Set UART Pin Mapping for MAX32672

Libraries/PeriphDrivers/Include/MAX32520/i2c.h, Libraries/PeriphDrivers/Include/MAX32570/i2c.h, Libraries/PeriphDrivers/Include/MAX32572/i2c.h, Libraries/PeriphDrivers/Include/MAX32650/i2c.h, Libraries/PeriphDrivers/Include/MAX32655/i2c.h, Libraries/PeriphDrivers/Include/MAX32660/i2c.h, Libraries/PeriphDrivers/Include/MAX32662/i2c.h, Libraries/PeriphDrivers/Include/MAX32665/i2c.h, Libraries/PeriphDrivers/Include/MAX32670/i2c.h, Libraries/PeriphDrivers/Include/MAX32672/i2c.h, Libraries/PeriphDrivers/Include/MAX32675/i2c.h, Libraries/PeriphDrivers/Include/MAX32680/i2c.h, Libraries/PeriphDrivers/Include/MAX32690/i2c.h, Libraries/PeriphDrivers/Include/MAX78000/i2c.h, Libraries/PeriphDrivers/Include/MAX78002/i2c.h
Closes #752 
None of our I2C init functions actually set the I2C frequency.
=> fix(Documentation): Remove Misleading Doxygen Comment for I2C Init (Doesn't Set Speed)

Libraries/PeriphDrivers/Source/I2C/i2c_reva.c
=> perf(PeriphDrivers): Remove Redundant `if` Statement in I2C Rev A

Libraries/SDHC/Include/sdhc_lib.h, Libraries/SDHC/ff13/Source/diskio.c, Libraries/SDHC/ff14/Source/diskio.c, Libraries/SDHC/ff15/source/diskio.c, Libraries/libs.mk, USERGUIDE.md
Closes #784 
The SDHC clock frequency can now be overridden with the new `SDHC_CLK_FREQ` build configuration variable.  Since the SDHC library is a larger library with multiple components, this warrants a build variable instead of a simple compiler definition.  
The default is 40Mhz.  Changing the value will affect the native and SPI-emulated SDHC implementations.  Ex:
```Makefile
SDHC_CLK_FREQ  = 25000000
```
=> feat(SDHC): Add Ability to Override SDHC_CLK_FREQ

Libraries/MiscDrivers/Touchscreen/tsc2046.h
Closes #785 
`TS_MAX_BUTTONS` can now be defined per-project.  Ex:
```Makefile
PROJ_CFLAGS += -DTS_MAX_BUTTONS=30
```
=> feat(MiscDrivers): Add Ability to Override TS_MAX_BUTTONS for TSC2046

Libraries/Boards/MAX32570/MN_EvKit_V1/Source/board.c, Libraries/Boards/MAX32570/M_EvKit_V1/Source/board.c, Libraries/Boards/MAX32570/QN_EvKit_V1/Source/board.c, Libraries/Boards/MAX32570/Q_EvKit_V1/Source/board.c, Libraries/Boards/MAX32655/EvKit_V1/Source/board.c, Libraries/Boards/MAX78000/EvKit_V1/Source/board.c
A customer discovered that the MAX32570_Demo examples were hanging after the touchscreen was pressed. After doing a little digging I discovered it was stuck in an undefined GPIO IRQ handler that had previously been defined in the pb.c files. This PR adds a default touchscreen IRQ handler for each board which has a touchscreen controller.
=> fix(Boards): Add default interrupt handlers for the touchscreen

Libraries/CMSIS/Device/Maxim/MAX32690/Include/max32690.svd, Libraries/CMSIS/Device/Maxim/MAX32690/Include/owm_regs.h, Libraries/PeriphDrivers/Source/OWM/owm_reva_me18.svd
OWM_STAT.presense_detect field should be at bit position 7 for MAX32690.
=> fix(CMSIS): Update OWM_STAT.presence_detect field position [7] for MAX32690

Libraries/CMSIS/Device/Maxim/GCC/gcc.mk, Libraries/CMSIS/Device/Maxim/GCC/gcc_riscv.mk
For some dual-core builds on GCC 12+, the `--no-warn-rwx-segments` would get added to the RISC-V linker flags when the compiler doesn't support it.  This PR prevents this from happening by renaming the variables to avoid namespace conflict.
=> fix(Build): Fix unrecognized option '--no-warn-rwx-segments' on riscv

Libraries/Cordio/ble-profiles/sources/af/app_slave.c
Cordio now will only cancel connection parameter update requests upon max attempts or connection interval agreement.
At the app layer, when requesting a connection update, a request goes through periodically until the update is successful or the max attempts have been reached. However, the stack does not differentiate between Master and Slave requests. So if the Master requests a connection update, the slaves request will be cancelled. Therefore, the parameters the application wants are never obtained. This change will stop trying for updates once the connection interval is accepted based on the range given by the user, or max attempts have been reached.
=> fix(BLE): Connection-Parameter-Update

Libraries/CMSIS/Device/Maxim/MAX32650/Include/max32650.svd, Libraries/CMSIS/Device/Maxim/MAX32650/Include/owm_regs.h, Libraries/CMSIS/Device/Maxim/MAX32655/Include/max32655.svd, Libraries/CMSIS/Device/Maxim/MAX32655/Include/owm_regs.h, Libraries/CMSIS/Device/Maxim/MAX32680/Include/max32680.svd, Libraries/CMSIS/Device/Maxim/MAX32680/Include/owm_regs.h, Libraries/CMSIS/Device/Maxim/MAX78000/Include/max78000.svd, Libraries/CMSIS/Device/Maxim/MAX78000/Include/owm_regs.h, Libraries/CMSIS/Device/Maxim/MAX78002/Include/max78002.svd, Libraries/CMSIS/Device/Maxim/MAX78002/Include/owm_regs.h, Libraries/PeriphDrivers/Source/OWM/owm_me17.c, Libraries/PeriphDrivers/Source/OWM/owm_me18.c, Libraries/PeriphDrivers/Source/OWM/owm_reva_ai87.svd, Libraries/PeriphDrivers/Source/OWM/owm_reva_me10.svd, Libraries/PeriphDrivers/Source/OWM/owm_reva_me17.svd, Libraries/PeriphDrivers/Source/SYS/pins_ai87.c, Libraries/PeriphDrivers/Source/SYS/pins_me10.c, Libraries/PeriphDrivers/Source/SYS/pins_me17.c, Libraries/PeriphDrivers/Source/SYS/pins_me18.c
- MAX32655/ MAX78000/ MAX78002 presence detect bit is 7 not 5
- MAX32655 OWM GPIO alternate function 2 not 1
- MAX32655/MAX32690 OWM GPIO mapping B pins defined
- Unneeded code which set voltage source deleted from drivers
- Voltage source selected as VDDIOH to provide 3.3V.
Test output on MAX32655 with MAX31825 target
ROM ID read succeeded.
PS: It will be nice to update init function to it take map parameters to select related gpio mapping but I am not sure whether API should be changed now or not. Changing API will break existing customer build system but i am not sure whether is there any one customer to use OWM API or not.
See [MAX32570 OWM init function](https://github.com/Analog-Devices-MSDK/msdk/blob/main/Libraries/PeriphDrivers/Include/MAX32570/owm.h#L104)
=> fix(PeriphDrivers): Fix OWM Presence Detect Bit and GPIO Alternate Functions, Use VDDIOH by Default

Libraries/PeriphDrivers/Include/MAX32655/wdt.h, Libraries/PeriphDrivers/Include/MAX32662/wdt.h, Libraries/PeriphDrivers/Include/MAX32670/wdt.h, Libraries/PeriphDrivers/Include/MAX32672/wdt.h, Libraries/PeriphDrivers/Include/MAX32675/wdt.h, Libraries/PeriphDrivers/Include/MAX32680/wdt.h, Libraries/PeriphDrivers/Include/MAX32690/wdt.h, Libraries/PeriphDrivers/Include/MAX78000/wdt.h, Libraries/PeriphDrivers/Include/MAX78002/wdt.h, Libraries/PeriphDrivers/Source/WDT/wdt_ai87.c, Libraries/PeriphDrivers/Source/WDT/wdt_me12.c, Libraries/PeriphDrivers/Source/WDT/wdt_me15.c, Libraries/PeriphDrivers/Source/WDT/wdt_me17.c, Libraries/PeriphDrivers/Source/WDT/wdt_me18.c, Libraries/PeriphDrivers/Source/WDT/wdt_me21.c, Libraries/PeriphDrivers/Source/WDT/wdt_revb.c, Libraries/PeriphDrivers/Source/WDT/wdt_revb.h
WDT peripheral of MAX32655, MAX32662, MAX32670, MAX32672, MAX32675, MAX32680, MAX32690, MAX78000 and MAX78002 supports selecting different clock sources which are given in user guide. 
Added a new function to set clksel register on revB WDT driver.
Added a new function to select supported clock sources for these part numbers.
=> feat(PeriphDrivers): Add clock selection feature to WDT

Libraries/CMSIS/5.9.0/Core/Include/core_rv32.h, Libraries/CMSIS/Device/Maxim/MAX32655/Source/GCC/startup_riscv_max32655.S, Libraries/CMSIS/Device/Maxim/MAX78000/Source/GCC/startup_riscv_max78000.S
Inside the startup script for the RISCV MAX32655, the vector table was being set to 0, instead of the the ISR vector table so interrupts were not working correctly.
=> fix(CMSIS): Vector table address now properly set

Libraries/PeriphDrivers/Source/ADC/adc_revb.c
ADC RevB peripherals can select different clock sources. In `MXC_ADC_RevB_Init(...)` and `MXC_ADC_RevB_ClockSelect(...)` functions, setting `clkctrl` register fot clock source was not correct. Also setting `clkctrl` and `sampclkctrl` registers' fields are not single bit fields, so using `|=` operation to set these fields could be causes problems. Because of these reasons, updated controlling these registers with using `MXC_SETFIELD(...)` macro.
=> fix(PeriphDrivers): Fix ADC RevB clock source configurations

Examples/MAX32690/Bluetooth/BLE_fcc/Makefile, Examples/MAX32690/Bluetooth/BLE_fcc/main.c
A continuous stream of modulated data is what i needed for FCC. This updated the TX tests to use continuous PRBS15.
=> feat(Examples, BLE): BLE_fcc now uses PRBS15 continuous instead of AA packteized 

Libraries/PeriphDrivers/Source/TMR/tmr_revb.c
For PWM mode when timer period end the tmr->count is reset to 0x00000001 and the timer resumes counting. 
On edge case (pwm==0) flow stuck in while loop, tmr->cnt newer become bigger than pwm so that +8 added.
Test detail
If tolerance value be +8
If tolerance value be +2
As can be seen below due to if checks it is hard to catch exact 0x000001 value, there should be a tolerance value, so that i set it as 8 (TMR clock is PCLK,   prescaler=1)
=> fix(PeriphDrivers): Fix Stuck Timer When PWM is set to 0

Libraries/PeriphDrivers/Source/OWM/owm_me14.c, Libraries/PeriphDrivers/Source/WDT/wdt_me17.c, Libraries/PeriphDrivers/Source/WDT/wdt_revb.c
WDT1(LPWDT0) clock sources order of MAX32655 is wrong in user guide.
To test clock source selection feature on MAX32655 for LPWDT0, selected ERTCO(CLK1) as clock source and disabled it but WDT continued to work. Switched selected clock source to CLK2 which is INRO clock's slot according to the user guide and disabled ERTCO clock, then WDT stopped working. Given clock source order in user guide is wrong. Updated clock sources order for WDT1.
=> fix(PeriphDrivers): Fix MAX32655 WDT clock source order

Libraries/PeriphDrivers/Source/TMR/tmr_revb.c
- In shutdown function, ctrl0 register set as 0. This causes problem because it disables timer clock before the timer. Thats why cnt register starts counting in next timer initialization when clk_en_x field is enabled even en_x field read as 0. To fix this problem, called stop function before setting ctrl0 register to 0.
For these 2 programs, timer shutdown and reinitialize for each configuration. Output 1 is current revB driver's output and output 2 is updated version's output.
=> fix(PeriphDrivers): Fix TMR Shutdown Bug, Stop Timer Before Clearing CTRL0

Libraries/PeriphDrivers/Include/MAX32675/hart_uart.h, Libraries/PeriphDrivers/Include/MAX32680/hart_uart.h, Libraries/PeriphDrivers/Source/AFE/afe.c, Libraries/PeriphDrivers/Source/AFE/hart_uart.c
Corrects AFE initialization issue on latest MAX32675 silicon.
Changes to AFE driver to speed up communications.  Increased SPI clock rate from 100KHz, to 1Mhz, and added define AFE_SPI_TRANSCEIVE_SAFE_BUT_SLOWER to allow compile time choice between timer based infinite loop protection, as was previously used, and the faster version without timeouts used by default now.
Adds HART_TEST_MODE_EXTERNAL this "Tristates" the HART Uart pins to allows them to be driven from off board PC.  This mode is required during HART registration testing as a Modem (Secondary Master). 
Validated working on MAX32675.
=> fix(PeriphDrivers): Fix MAX32675, MAX32680 A5 Silicon AFE Init, and Speedups

Examples/MAX32690/ADC/main.c
feat(Examples): Add Ref Trim procedure to MAX32690 ADC Example
Adds functions to the MAX32690 ADC example project to perform the reference trim for all ADC reference sources.
=> feat(Examples): Add Ref Trim procedure to MAX32690 ADC Example

Libraries/PeriphDrivers/Source/TMR/tmr_me21.c
=> fix(PeriphDrivers): Fix MAX32672 `MXC_TMR_GetPeriod` for 16-32Mhz Clock

Libraries/CMSIS/Device/Maxim/MAX32690/Source/GCC/max32690_memory.mk
Total SRAM size shall be 1MB.
In linker file SRAM size calculated by below formula ARM_SRAM_SIZE = _SRAM_SIZE - _RISCV_SRAM_SIZE;
ARM SRAM size shall be less than total incase of riscv core enabled.
This condition causes issue while working on DAPLink fw for MAX32690.
=> fix(CMSIS): Fix MAX32690 SRAM Size Calculation

Libraries/Cordio/controller/sources/ble/lhci/lhci_cmd_vs.c, Libraries/Cordio/controller/sources/ble/lhci/lhci_cmd_vs_adv_master_ae.c, Libraries/Cordio/controller/sources/ble/lhci/lhci_int.h
Added HCI commands to enable/disable PHY as well as capture an RSSI sample. 
The RSSI sample returns a static value now as it requires a feature in the PHY not yet present in the MSDK. This will be updated upon the next PHY update.
=> fix(BLE): Cordio HCI now has implementation in HCI for RSSI and Phy Enable/Disable

.github/workflows/Generate_Register_Files.yml, .github/workflows/Verify_Register_SVD.yml, .github/workflows/scripts/test_launcher.sh
Update all the workflows, that use runners from the BTM-CI, to run a shallow clone to conserve storage space.
=> fix(workflow): Run shallow clone for workflows running from BTM-CI

Libraries/PeriphDrivers/Source/TMR/tmr_revb.c
Closes #823 
There's a new note about clock selection in Rev 4 of the MAX32670 UG (See section 13.4)
In the past, the settings for the "A" timer were assumed to propagate through to the "B" timer in 32-bit cascade mode. It seems like there was a bug, so now we should match the clock selection for A/B on initialization to ensure proper operation in the 32-bit modes.
=> fix(PeriphDrivers): Fix TMR Rev B Initialization Bug with Non-Default Clock Sources

Libraries/PeriphDrivers/Source/LP/lp_me11.c, Libraries/PeriphDrivers/Source/LP/lp_me14.c
MXC_LP_EnterShutDownMode function name does not match with .h and .c files. To it match with other part number too, ShutDown prefered instead of Shutdown which match with rest of the usage in the file like MXC_LP_SRCCShutdown ...
See: 
https://github.com/Analog-Devices-MSDK/msdk/blob/main/Libraries/PeriphDrivers/Include/MAX32660/lp.h#L197
https://github.com/Analog-Devices-MSDK/msdk/blob/main/Libraries/PeriphDrivers/Include/MAX32665/lp.h#L390
=> chore(PeriphDrivers): Fix typo

Libraries/PeriphDrivers/Include/MAX32660/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32670/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32675/mxc_sys.h, Libraries/PeriphDrivers/Source/SYS/sys_me11.c, Libraries/PeriphDrivers/Source/SYS/sys_me15.c
MAX32670 and MAX32660 has prescaler register that can be used to div system clock to specific value, this commit add related function to provide this feature
https://www.analog.com/media/en/technical-documentation/user-guides/max32660-user-guide.pdf
https://www.analog.com/media/en/technical-documentation/user-guides/max32670max32671-user-guide.pdf
=> feat(PeriphDrivers): Add System Clock Div APIs for MAX32670 and MAX32660

.github/workflows/Build_Examples.yml
This PR fixes missed build tests for the following conditions:
- When a commit is pushed to main
- When a PR is opened from a fork, and the source branch is also named 'main'
If implemented correctly, the "Build Examples" test should fully run for this PR.
=> fix(workflow): Fix Skipped Build Tests

Libraries/MiscDrivers/Display/tft_ssd2119.c, Libraries/MiscDrivers/Display/tft_st7735.c
GCC 13.2 warning clearance for tft_ssd2119.c
In the latest compiler version, the array bounds warnings appear. This was an internal issue and I tried building MAX78000 kws20_demo example and saw warnings myself. 
The changes are in:
1. MXC_TFT_Init function: Optional and tested for both GCC Versions (10.3 and 13.2) on MAX78000 kws20_demo.
2. MXC_TFT_Printf function: This one works incorrect when using GCC v13.2 - so should be merged. Tested with MAX32662 Demo Example.
=> fix(MiscDrivers): MSDK-1240: Clear out of bounds warnings seen with GCC v13.2

Libraries/PeriphDrivers/Source/I2C/i2c_reva.c
@alperenguclu faced a problem while trying to receive more than 256-byte data from I2C channel and we found that `MXC_I2C_RevA_MasterTransaction` has a bug in rx part. His team tested it with MAX32690.
=> fix(PeriphDrivers): Add I2C RX FIFO status check to receive more than 256-byte of data for I2C synchronous transactions

Examples/MAX78002/TFT_Demo/main.c
TFT_Demo Example for MAX78002 with Adafruit Featherwing TFT Display was not working properly.
-main.c is changed in order to initiate the TFT Display, then the Touchscreen.
After the change, the example works fine:
=> fix(Examples): Fix MAX78002 TFT_Demo Example for TFT=ADAFRUIT

Libraries/CMSIS/Device/Maxim/MAX32662/Source/system_max32662.c, Libraries/CMSIS/Device/Maxim/MAX32672/Source/system_max32672.c, Libraries/CMSIS/Device/Maxim/MAX32675/Source/system_max32675.c
MAX32662, MAX32672 and MAX32675 has the OVR bit to operate CPU voltage with different modes and this affects also the IPO clock. We need to consider this when calculating the system core clock.
PS. This has already done for MAX32660 in [here](https://github.com/Analog-Devices-MSDK/msdk/blob/b71d6f576b70670144f35bf898ddd7ef4e92c53a/Libraries/CMSIS/Device/Maxim/MAX32660/Source/system_max32660.c#L65)
=> fix(CMSIS): MSDK-1249: Add OVR Correction to SystemCoreClock Calculation for MAX32662 MAX32672 MAX32675

Tools/Flash/flash.mk
The MSDK includes [Makefile targets for flashing](https://analog-devices-msdk.github.io/msdk/USERGUIDE/#flashing-on-the-command-line) via a `flash.mk` file.  This target depends on a rule for creating a .hex file.  The .hex file is added as an explicit dependency of the flashing targets so that it's built before attempting the flash.  On Windows + MSYS2 the file path was mal-formed.  `cygpath` is required to correct the path, but the code that detected the availability of `cygpath` was not working correctly.
This PR fixes the OS auto-detection in `flash.mk`, which fixes `make flash.openocd` on Windows.
Fixes #872
=> fix(Build): Fix broken `make flash.openocd` on Windows + MSYS2

Libraries/PeriphDrivers/Include/MAX32660/gpio.h, Libraries/PeriphDrivers/Include/MAX32670/gpio.h, Libraries/PeriphDrivers/Include/MAX32675/gpio.h
Most of MAX32 MCUs has pull-up/down and weak pull-up/down feature But some of MCUs only has pull-up/down, this differentiation create delta between gpio interface function and so that it make it hard to develop high level common interface functions.
The purpose of this commit is to align padding definition to provide common interface for gpio.h file
Without this addition it requires add extra macro/definition... to develop common fw which drive MAX32 MCUs, Like below
=> chore(PeriphDrivers): Define `MXC_GPIO_PAD` Enum Consistently Across All Parts

Libraries/PeriphDrivers/Include/MAX32520/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32570/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32662/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32672/mxc_sys.h, Libraries/PeriphDrivers/Source/SYS/sys_es17.c, Libraries/PeriphDrivers/Source/SYS/sys_me12.c, Libraries/PeriphDrivers/Source/SYS/sys_me13.c, Libraries/PeriphDrivers/Source/SYS/sys_me21.c
The additions in [PR#857](https://github.com/Analog-Devices-MSDK/msdk/pull/857) are propagated to MAX32662, MAX32672, MAX32570, MAX32520 as per of need.
=> feat(PeriphDrivers): Add System Clock Div APIs for MAX32 MCUs

Libraries/PeriphDrivers/Source/GPIO/gpio_ai85.c, Libraries/PeriphDrivers/Source/GPIO/gpio_ai87.c, Libraries/PeriphDrivers/Source/GPIO/gpio_es17.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me10.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me11.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me12.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me13.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me14.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me17.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me18.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me20.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me55.c
Voltage Rail selection should be made before padding configuration. A hesitation came from Clayton:
> For the MXC_GPIO_Config function, the last thing done is to select the voltage rail (gpio_me18.c). This creates a situation where damage to the part can occur. The GPIO on parts with multiple rails defaults to VDDIO (1.8V) with pullup/pulldown disabled. If a customer has 3.0V on a GPIO pin (say I2C pullups), and the code turns on the pullup before selecting the VDDIOH rail, the 3.0V back powers VDDIO, potentially causing damage to the pads.
=> fix(PeriphDrivers): MSDK-1245: Re-order VSSEL selection to avoid possible damages on pads

Libraries/PeriphDrivers/Source/SPI/spi_me14.c
fixes #396  . Add Chip Select configuration to MXC_SPI_Init using pre-existing me14_pins gpio cfg structs. SPI Example tested showing successful transactions and proper SPI Chip Select Behavior. 
Second image shows green LED1 on EVK, which indicates a successful run of the SPI example. 
**fix** 
**PeriphDrivers**
=> fix(PeriphDrivers): Add GPIO Chip Select Configuration for MAX32665 SPI driver

Libraries/PeriphDrivers/Include/MAX32662/gpio.h, Libraries/PeriphDrivers/Source/GPIO/gpio_me12.c
ME12 only supports high-impedance, weak pullup and weak pulldown options.
This commit removes other options and corrects related register values of PAD configuration.
=> fix(PeriphDrivers): Update MAX32662 GPIO PAD configuration

Libraries/CMSIS/Device/Maxim/MAX32660/Include/max32660.svd, Libraries/CMSIS/Device/Maxim/MAX32660/Include/rtc_regs.h, Libraries/CMSIS/Device/Maxim/MAX32670/Include/max32670.svd, Libraries/CMSIS/Device/Maxim/MAX32670/Include/rtc_regs.h, Libraries/CMSIS/Device/Maxim/MAX32672/Include/max32672.svd, Libraries/CMSIS/Device/Maxim/MAX32672/Include/rtc_regs.h, Libraries/CMSIS/Device/Maxim/MAX32675/Include/max32675.svd, Libraries/CMSIS/Device/Maxim/MAX32675/Include/rtc_regs.h, Libraries/PeriphDrivers/Source/RTC/rtc_reva_me11.svd, Libraries/PeriphDrivers/Source/RTC/rtc_reva_me15.svd, Libraries/PeriphDrivers/Source/RTC/rtc_reva_me21.svd
RTC SEC and SSEC register size is 32bit and 12bits This value is set to 8bits for MAX32670, MAX32660, MAX32672.
This commit set register size to the correct values.
Links:
https://www.analog.com/media/en/technical-documentation/user-guides/max32670max32671-user-guide.pdf
https://www.analog.com/media/en/technical-documentation/user-guides/max32672-user-guide.pdf
https://www.analog.com/media/en/technical-documentation/user-guides/max32660-user-guide.pdf
Register size as per of UGs
=> fix(PeriphDrivers): Update RTC SEC and SSEC register size

Libraries/PeriphDrivers/Include/MAX32662/i2c.h
Most of MAX32 MCUs supports 4 different I2C speeds and these speeds defined in 'i2c.h' file of MCU. But these definitions missed for MAX32662.
The purpose of this commit is adding these definitions for MAX32662 to provide common interface for I2C speed.
=> chore(PeriphDrivers): Define I2C Speeds for MAX32662

Libraries/PeriphDrivers/Source/UART/uart_me15.c
=> fix(PeriphDrivers): Fix MXC_UART_Shutdown Typo for LPUART0 Pin De-Initialization

Examples/MAX78000/CNN/actionrecognition-demo/project.mk
#851 did not have the CAM02 BSP merged in yet, so a build test failure slipped in.  This changes the example to throw an error on any board other than the MAX78000FTHR.
=> fix(ignore): Hotfix for actionrecognition-demo Build Test Failure

Examples/MAX32660/SPIMSS_DMA/.cproject, Examples/MAX32660/SPIMSS_DMA/.project, Examples/MAX32660/SPIMSS_DMA/.settings/language.settings.xml, Examples/MAX32660/SPIMSS_DMA/.settings/org.eclipse.cdt.codan.core.prefs, Examples/MAX32660/SPIMSS_DMA/.settings/org.eclipse.cdt.core.prefs, Examples/MAX32660/SPIMSS_DMA/.vscode/README.md, Examples/MAX32660/SPIMSS_DMA/.vscode/c_cpp_properties.json, Examples/MAX32660/SPIMSS_DMA/.vscode/flash.gdb, Examples/MAX32660/SPIMSS_DMA/.vscode/launch.json, Examples/MAX32660/SPIMSS_DMA/.vscode/settings.json, Examples/MAX32660/SPIMSS_DMA/.vscode/tasks.json, Examples/MAX32660/SPIMSS_DMA/Makefile, Examples/MAX32660/SPIMSS_DMA/README.md, Examples/MAX32660/SPIMSS_DMA/SPIMSS.launch, Examples/MAX32660/SPIMSS_DMA/main.c, Examples/MAX32660/SPIMSS_DMA/project.mk, Libraries/PeriphDrivers/Include/MAX32650/spimss.h, Libraries/PeriphDrivers/Include/MAX32660/dma.h, Libraries/PeriphDrivers/Include/MAX32660/spimss.h, Libraries/PeriphDrivers/Source/SPI/spi_me11.c, Libraries/PeriphDrivers/Source/SPIMSS/spimss_me10.c, Libraries/PeriphDrivers/Source/SPIMSS/spimss_me11.c, Libraries/PeriphDrivers/Source/SPIMSS/spimss_reva.c, Libraries/PeriphDrivers/Source/SPIMSS/spimss_reva.h
There is no transaction API over DMA for SPIMSS driver in MSDK. In addition, we don't have example application which shows how to make SPIMSS master transaction by using DMA. 
Implemented Example:
SPIMSS_DMA example code is added for MAX32660 EVSYS
Implemented API Features:
SPIMSS DMA "Auto handlers". Auto handling is disabled by default.
APIs for using application defined DMA handlers and channels.
New API for SPIMSS Master Dma Transaction:
int MXC_SPIMSS_MasterTransDMA(mxc_spimss_regs_t *spi, mxc_spimss_req_t *req);
New APIs for Assigning DMA Channels:
int MXC_SPIMSS_SetTXDMAChannel(mxc_spimss_regs_t *spi, unsigned int channel);
int MXC_SPIMSS_SetRXDMAChannel(mxc_spimss_regs_t *spi, unsigned int channel);
int MXC_SPIMSS_GetTXDMAChannel(mxc_spimss_regs_t *spi);
int …
=> feat(Examples,PeriphDrivers): Add SPIMSS_DMA example and SPIMSS Master Trans DMA APIs

Libraries/CMSIS/Device/Maxim/MAX32662/Include/system_max32662.h, Libraries/PeriphDrivers/Source/SYS/sys_me12.c
1) INRO/NANORING clock is 80kHz according to the UG. But, it was defined as 8kHz in system_max32662.h. See page 36 -> https://www.analog.com/media/en/technical-documentation/user-guides/max32662-ug-7640.pdf 
2) Logic error exists related to if controls in MXC_SYS_ClockDisable and MXC_SYS_ClockEnable functions. See sys_me12.c
=> fix(CMSIS,PeriphDrivers): Fix logic error in SYS Clock Enable/Disable functions and INRO frequency for MAX32662

Libraries/Boards/MAX32690/WLP_V1/Source/board.c
Removed TFT include from WLP_V1 for the MAX32690, a board with no TFT.
=> fix(Boards): Remove TFT Lib include from board with no TFT

Libraries/CMSIS/Device/Maxim/MAX32570/Include/max32570.h, Libraries/MiscDrivers/Display/tft_ssd2119.c, Libraries/PeriphDrivers/Include/MAX32570/tmr.h
Related to issue https://github.com/Analog-Devices-MSDK/msdk/issues/900
This PR fixes the build errors for MAX32570A as a result of the changes made for the MAX32572 and MAX32570B.
The previous changes made in `tmr.h` were directed towards the MAX32570B, but did not take into account of the existing MAX32570A naming convention.
The TFT drivers used the incorrect SPI definitions for the MAX32570A.
=> fix(MiscDrivers,PeriphDrivers): Fix TMR and TFT build errors for MAX32570

Libraries/PeriphDrivers/Source/SPI/spi_reva1.c
Fixes #879 by adding some extra logic to handle the edge case where the transaction length is less than the FIFO size.  In this case, there is nothing left for the DMA to do after the FIFO is pre-loaded.  The previous implementation would enable the DMA with a transfer count of 0, so the callbacks would never get triggered.
AFAIK the FIFO pre-load works around some hardware issues on some parts and is required.
=> fix(PeriphDrivers): Fix SPI RevA1 DMA Bug When Transaction Length is Less Than the FIFO Size

Libraries/CMSIS/Device/Maxim/GCC/gcc.mk, Libraries/CMSIS/Device/Maxim/GCC/gcc_riscv.mk
Previous builds defined `TARGET=MAXxxxxx`, but the pre-processor can't do string comparisons.  This PR defines `MAXxxxxx` to enable checks like
```C
#ifdef MAX32665
...
#endif
```
=> feat(Build): Add Compiler Flag for Checking Target Micro

Libraries/Boards/MAX32572/BCB/board.mk, Libraries/Boards/MAX32572/EvKit_V1/adapters.txt, Libraries/PeriphDrivers/Source/UART/uart_me55.c
Some fixes that were discovered for ME55 since release.
1. UART3 was treated as a special LP UART case for `MXC_UART_SetFrequency(...)` and `MXC_UART_GetFrequency(...)`, when all UARTs are the same type for ME55.
2. BCB had some build errors since last syncup.
3. Add Olimex selection to ME55 EVKIT adapters.
=> chore(Boards,PeriphDrivers): Add Olimex selection, treat UART3 as other UARTs, and fix BCB build errors for MAX32572

Examples/MAX32670/RTC/README.md, Examples/MAX32670/RTC/main.c, Libraries/Boards/MAX32655/EvKit_V1/examples.txt
The incorrect switch name in the MAX32670 RTC example has been corrected.
The example list under the MAX32655-EvKit_V1 board has been updated so that the I2C_EEPROM example appears in the project creation wizard.
=> fix(Examples, Boards): Fix Max32670 RTC example, update MAX32655 board example list

Libraries/CMSIS/Device/Maxim/MAX32675/Source/IAR/startup_max32675.s, Libraries/PeriphDrivers/Include/MAX32675/mxc_device.h
- Added missing vector table information in cstartup file.
- Removed reference to the RTEComponents.h (this file is used when using CMSIS pack files).
=> fix(ThirdParty): Remove IAR build errors for the MAX32675

Libraries/CMSIS/Device/Maxim/MAX32572/Source/system_max32572.c
The performance of the ME55 is greatly diminished with the SPIXF cache controller disabled when using the external flash. This change will enable the SFCC by default in SystemInit.
=> feat(CMSIS): Enable SPIXF cache controller (SFCC) in SystemInit for MAX32572

Libraries/CMSIS/Device/Maxim/GCC/gcc.mk, Libraries/CMSIS/Device/Maxim/GCC/gcc_riscv.mk
Add the `make query` target.  This allows IDEs and scripts to query the value of a specific build variable for a project by also setting `QUERY_VARIABLE`.
Useful for https://github.com/Analog-Devices-MSDK/MSDKGen/commit/17017774f9e7945a07e09f93f5ef0485287bc2e0
Ex:
```shell
~/repos/msdk/Examples/MAX78000/Hello_World (feat/query*) » make query QUERY_VAR=TARGET
Loaded project.mk
TARGET=MAX78000
```
The output must still be parsed, since other Makefiles might print extra `$(info)` statements.  This could be improved in a future PR that implements some sort of log-level mechanism for suppressing all `$(info)` output.
=> feat(Build): Add Ability to Selectively Introspect Build Variables

Libraries/PeriphDrivers/Include/MAX32650/i2c.h, Libraries/PeriphDrivers/Include/MAX32650/spi.h, Libraries/PeriphDrivers/Include/MAX32650/uart.h, Libraries/PeriphDrivers/Include/MAX32660/i2c.h, Libraries/PeriphDrivers/Include/MAX32660/spi.h, Libraries/PeriphDrivers/Include/MAX32662/i2c.h, Libraries/PeriphDrivers/Include/MAX32662/spi.h, Libraries/PeriphDrivers/Include/MAX32662/uart.h, Libraries/PeriphDrivers/Include/MAX32672/i2c.h, Libraries/PeriphDrivers/Include/MAX32672/spi.h, Libraries/PeriphDrivers/Include/MAX32672/uart.h, Libraries/PeriphDrivers/Include/MAX32675/i2c.h, Libraries/PeriphDrivers/Include/MAX32675/spi.h, Libraries/PeriphDrivers/Include/MAX32675/uart.h, Libraries/PeriphDrivers/Include/MAX32680/i2c.h, Libraries/PeriphDrivers/Include/MAX32680/spi.h, Libraries/PeriphDrivers/Include/MAX32680/uart.h, Libraries/PeriphDrivers/Source/I2C/i2c_me10.c, Libraries/PeriphDrivers/Source/I2C/i2c_me11.c, Libraries/PeriphDrivers/Source/I2C/i2c_me12.c, Libraries/PeriphDrivers/Source/I2C/i2c_me21.c, Libraries/PeriphDrivers/Source/SPI/spi_me10.c, Libraries/PeriphDrivers/Source/SPI/spi_me11.c, Libraries/PeriphDrivers/Source/SPI/spi_me12.c, Libraries/PeriphDrivers/Source/SPI/spi_me16.c, Libraries/PeriphDrivers/Source/SPI/spi_me21.c, Libraries/PeriphDrivers/Source/UART/uart_me12.c, Libraries/PeriphDrivers/Source/UART/uart_me16.c, Libraries/PeriphDrivers/Source/UART/uart_me21.c
This PR can be considered as part of 
https://github.com/analogdevicesinc/msdk/pull/730
https://github.com/analogdevicesinc/msdk/pull/809
The clock disable mechanism propagated other devices.
Changes applied to below peripherals.
- I2C
- SPI
- UART
=> feat(PeriphDrivers): Allow Skipping Clock and GPIO Initialization

.github/workflows/clang-format-run-pr.yml
Node.js 16 is deprecated - updating to Node.js 20. Also, removed an undefined and unnecessary token secret.
=> fix(workflow): Update clang-format workflow to Node.js 20 and remove undefined token

Libraries/Cordio/platform/targets/maxim/max32665/sources/pal_timer.c, Libraries/Cordio/platform/targets/maxim/max32690/sources/pal_timer.c
Updated the code for calibrating the PalTimer against the 32MHz clock.  Original implementation only added adjustment on 100ms (PAL_TMR_CALIB_TIME) boundaries.  In cases where the timer time was in between 100ms intervals, the timer could be severely early or late depending on how large usecDiff is.
``
The math could be accomplished by simply running `(expUsec * palTimerCb.usecDiff) / PAL_TMR_CALIB_TIME;` however there is not enough objective evidence for the max values of expUsec and usecDiff to show the multiplication won't overflow 32-bits.  The math could be done in 64-bits, however the modulo method was used to keep this within a 32-bit scope.
=> fix(BLE): PalTimer Calibration

Libraries/PeriphDrivers/Include/MAX32662/tmr.h, Libraries/PeriphDrivers/Source/TMR/tmr_me12.c
Rename INRO clock Enum definition for MAX32662. See #895
=> fix(PeriphDrivers): Update INRO clock Enum name for MAX32662.

Examples/MAX78000/CNN/facial_recognition/include/ffconf.h, Libraries/PeriphDrivers/Source/GPIO/gpio_me18.c, Libraries/PeriphDrivers/Source/I2S/i2s_reva.c, Libraries/PeriphDrivers/Source/SEMA/sema_reva.c, Libraries/PeriphDrivers/Source/UART/uart_revb.c, Libraries/PeriphDrivers/Source/WUT/wut_reva.c
IAR's compiler generates a few warnings not caught by GCC.  This PR resolves those warnings.
=> fix(PeriphDrivers): Resolve compiler warnings for the MAX32690 libraries when building with IAR's Embedded Workbench

.github/workflows/clang-format-run-pr.yml
Added a new repo secret (similar to old MSDK repo location), so any commits made by a runner (like for clang-format-run) would automatically re-trigger all other actions.
=> fix(workflow): Add token permissions to automatically re-trigger actions after a commit

.github/workflows/clang-format-run-pr.yml
ADI organization requires SSO with the token when a runner pushes a commit... Repo-specific secrets are a bust when you need all actions to re-trigger after a runner makes a commit, but the created secret will remain available in case for future use. Need to find an alternative to retrigger workflows, if possible.
=> revert(workflow): Remove token usage from clang-format-run workflow

Libraries/PeriphDrivers/Include/MAX32662/can.h, Libraries/PeriphDrivers/Include/MAX32690/can.h, Libraries/PeriphDrivers/Source/CAN/can_me12.c, Libraries/PeriphDrivers/Source/CAN/can_me18.c
This PR can be considered as part of https://github.com/analogdevicesinc/msdk/pull/730 https://github.com/analogdevicesinc/msdk/pull/809 https://github.com/analogdevicesinc/msdk/pull/932
The clock disable mechanism propagated other devices.
Changes applied to the below peripherals.
- CAN
=> feat(PeriphDrivers): Allow Skipping Clock and GPIO Initialization on CAN

Tools/Flash/flash.mk
Updated the flash.mk file to include the necessary breakpoints to halt the CPU once the bootloader unlocks the SWD.  This change is analogous to Commit [3055fd1](https://github.com/Analog-Devices-MSDK/openocd/commit/3055fd15e87301f760fc36a4b4ab9b9937f629fe) for OpenOCD, just simplified for single use with JLink in the Makefile context.
=> fix(Tools): JLink Flashing for MAX32670/75

.github/workflows/scripts/zephyr-hal.sh, .github/workflows/zephyr-hal.yml
The Zephyr port for the MAX32xxx devices uses files from this repo.  The port will not be accepted by the Zephyr review committee if it contains too many extraneous files.  This workflow will copy only the files that Zephyr needs into a stand-alone, slimmed down repository.
=> ci(workflow): Add workflow for copying necessary files to Zephyr HAL repo

Libraries/PeriphDrivers/Source/TMR/tmr_reva.c
Fixes #947 
The ME10 UG has a mistake that propagated itself to our periphdrivers.  The logic table skips from `0b000` to `0b010` at the transition between 256 -> 512.  This causes 512 - 2048 to be twice what they should, and 4096 to roll over to an invalid setting that behaves like a divisor of 1.
This PR updates the divisor settings to remove the skip
=> fix(PeriphDrivers): Fix Bitwise Logic for TMR RevA Prescaler Init

Libraries/CMSIS/Device/Maxim/MAX32675/Include/max32675.h, Libraries/CMSIS/Device/Maxim/MAX32675/Source/GCC/startup_max32675.S
The MAX32675 was missing the GPIOWAKE vector.
=> fix(CMSIS): Add GPIOWAKE_IRQn to MAX32675

Libraries/PeriphDrivers/Include/MAX32520/gpio.h, Libraries/PeriphDrivers/Include/MAX32570/gpio.h, Libraries/PeriphDrivers/Include/MAX32572/gpio.h, Libraries/PeriphDrivers/Include/MAX32650/gpio.h, Libraries/PeriphDrivers/Include/MAX32655/gpio.h, Libraries/PeriphDrivers/Include/MAX32660/gpio.h, Libraries/PeriphDrivers/Include/MAX32662/gpio.h, Libraries/PeriphDrivers/Include/MAX32665/gpio.h, Libraries/PeriphDrivers/Include/MAX32670/gpio.h, Libraries/PeriphDrivers/Include/MAX32672/gpio.h, Libraries/PeriphDrivers/Include/MAX32675/gpio.h, Libraries/PeriphDrivers/Include/MAX32680/gpio.h, Libraries/PeriphDrivers/Include/MAX32690/gpio.h, Libraries/PeriphDrivers/Include/MAX78000/gpio.h, Libraries/PeriphDrivers/Include/MAX78002/gpio.h
Hope this makes sense - let me know if not.
This PR updates the GPIO drive strength documentation to make it clear that it does not represent the GPIO drive strength level, but rather what the GPIO drive strength registers `GPIO_DS[2]` are set to. The actual drive strength values are not used in the enum names because the drive strength values can vary from pin-to-pin and the state of the GPIO pin (alternate function and voltage setting). 
Refer to https://github.com/analogdevicesinc/msdk/issues/983 for more info.
=> fix(PeriphDrivers): Clarify GPIO drive strength enum documentation

Libraries/MiscDrivers/Display/tft_ssd2119.c
After #880, @aniktash reported the TFT on the MAX78000EVKIT was broken/blank.  None of the demos were working.
It turns out that the driver simply did not initialize the vddioh member of an internal struct describing the SPI pins, so it was initialized to a random undefined value and optimized out by the compiler.  The SPI pins then got initialized to 1.8V instead of 3.3V. 
After this fix, all the TFT-based demos should be working again.
=> fix(MiscDrivers): Fix Blank MAX78000EVKIT TFT Display

Libraries/PeriphDrivers/Source/TMR/tmr_me16.c
This PR fix timer warning.
Incase of assert disabled below warning occur during build.
=> fix(PeriphDrivers): Fix MAX32675 timer warning

Examples/MAX32655/Bluetooth/RF_Test/main.c, Examples/MAX32665/Bluetooth/RF_Test/main.c, Examples/MAX32690/Bluetooth/RF_Test/main.c
This provides a work around to support Issue #995, where the low priority test task is directly calling the BLE's  LL functions, causing a condition where the LL task wakes up prior to all the necessary data being set.
=> fix(Examples): RF Test RTOS Scheduling Work Around

Libraries/Cordio/wsf/sources/targets/freertos/wsf_timer.c
Resolved an issue in WsfTimerStop where if the head of the queue is removed, both the tail and head are set to NULL, effectively resetting the queue, rather than the head becoming the next list item.    Updated file style based on clang-format and cpplint outputs.
=> fix(BLE): Fixed error in FreeRTOS Timer queue

.github/workflows/zephyr-hal.yml
Trying new secrets to push the latest MSDK changes into [`analogdevicesinc/hal_adi`](https://github.com/analogdevicesinc/hal_adi/tree/develophttps://github.com/analogdevicesinc/hal_adi/tree/develop).
And trying a new GitHub actions account in the workflow.
=> fix(workflow): Update permissions in zephyr-hal workflow

.github/workflows/scripts/build.py
#1013 introduced a build error that was only present on the Github Actions runners for some BLE projects [(Ex)](https://github.com/analogdevicesinc/msdk/actions/runs/9065017515/job/24904593363).  Some outdated cached copies of the Cordio library builds seemed to be causing it.
This PR updates the build test workflow to clean the Cordio library file for BLE projects.  BLE projects are detected if:
- The file path has `Bluetooth` in it
- The project name has `BLE` in it
=> fix(workflow): Fix BLE Project Build Test Failures

Libraries/CMSIS/Device/Maxim/MAX32520/Source/system_max32520.c, Libraries/CMSIS/Device/Maxim/MAX32570/Source/system_max32570.c, Libraries/CMSIS/Device/Maxim/MAX32572/Source/system_max32572.c, Libraries/CMSIS/Device/Maxim/MAX32572/Source/system_riscv_max32572.c, Libraries/CMSIS/Device/Maxim/MAX32650/Source/system_max32650.c, Libraries/CMSIS/Device/Maxim/MAX32655/Source/system_max32655.c, Libraries/CMSIS/Device/Maxim/MAX32655/Source/system_riscv_max32655.c, Libraries/CMSIS/Device/Maxim/MAX32657/Source/system_max32657.c, Libraries/CMSIS/Device/Maxim/MAX32660/Source/system_max32660.c, Libraries/CMSIS/Device/Maxim/MAX32662/Source/system_max32662.c, Libraries/CMSIS/Device/Maxim/MAX32665/Source/system_max32665.c, Libraries/CMSIS/Device/Maxim/MAX32670/Source/system_max32670.c, Libraries/CMSIS/Device/Maxim/MAX32672/Source/system_max32672.c, Libraries/CMSIS/Device/Maxim/MAX32675/Source/system_max32675.c, Libraries/CMSIS/Device/Maxim/MAX32680/Source/system_max32680.c, Libraries/CMSIS/Device/Maxim/MAX32680/Source/system_riscv_max32680.c, Libraries/CMSIS/Device/Maxim/MAX32690/Source/system_max32690.c, Libraries/CMSIS/Device/Maxim/MAX32690/Source/system_riscv_max32690.c, Libraries/CMSIS/Device/Maxim/MAX78000/Source/system_max78000.c, Libraries/CMSIS/Device/Maxim/MAX78000/Source/system_riscv_max78000.c, Libraries/CMSIS/Device/Maxim/MAX78002/Source/system_max78002.c, Libraries/CMSIS/Device/Maxim/MAX78002/Source/system_riscv_max78002.c
Declares _getpid() and _kill() function stubs as weak to avoid conflicting with similar function stubs defined in zephyr libc-hooks. This fixes linker errors when building zephyr with newlib on max32 boards.
Reported in zephyrproject-rtos/zephyr#73606
Hotfix applied to downstream fork in zephyrproject-rtos/hal_adi#1
Tested locally with Zephyr:
```
$ twister -p max32690evkit/max32690/m4 -T tests/lib/cpp/ -T tests/lib/c_lib/
```
And in Zephyr CI:
https://github.com/zephyrproject-rtos/zephyr/actions/runs/9332489979
=> fix(CMSIS): Declare libc function stubs as weak

Libraries/PeriphDrivers/Include/MAX32657/lp.h, Libraries/PeriphDrivers/Source/TMR/tmr_me30.c, Libraries/PeriphDrivers/Source/TMR/tmr_revb.c
To build and test PWM on ME30 below modifications are applied.
- Necessary ifndef statement added to tmr_revb.c to get output from timer module.
- Unnecessary pin option is removed from tmr_me30.c
- Unnecessary enumeration is removed from lp.h
- [x ] PR Title follows correct guidelines.
- [x ] Description of changes and all other relevant information.
=> fix(PeriphDrivers): Fix PWM to work with ME30

Libraries/CMSIS/Device/Maxim/MAX32520/Source/system_max32520.c, Libraries/CMSIS/Device/Maxim/MAX32570/Source/system_max32570.c, Libraries/CMSIS/Device/Maxim/MAX32572/Source/system_max32572.c, Libraries/CMSIS/Device/Maxim/MAX32572/Source/system_riscv_max32572.c, Libraries/CMSIS/Device/Maxim/MAX32650/Source/system_max32650.c, Libraries/CMSIS/Device/Maxim/MAX32655/Source/system_max32655.c, Libraries/CMSIS/Device/Maxim/MAX32655/Source/system_riscv_max32655.c, Libraries/CMSIS/Device/Maxim/MAX32660/Source/system_max32660.c, Libraries/CMSIS/Device/Maxim/MAX32662/Source/system_max32662.c, Libraries/CMSIS/Device/Maxim/MAX32665/Source/system_max32665.c, Libraries/CMSIS/Device/Maxim/MAX32670/Source/system_max32670.c, Libraries/CMSIS/Device/Maxim/MAX32672/Source/system_max32672.c, Libraries/CMSIS/Device/Maxim/MAX32675/Source/system_max32675.c, Libraries/CMSIS/Device/Maxim/MAX32680/Source/system_max32680.c, Libraries/CMSIS/Device/Maxim/MAX32680/Source/system_riscv_max32680.c, Libraries/CMSIS/Device/Maxim/MAX32690/Source/system_max32690.c, Libraries/CMSIS/Device/Maxim/MAX32690/Source/system_riscv_max32690.c, Libraries/CMSIS/Device/Maxim/MAX78000/Source/system_max78000.c, Libraries/CMSIS/Device/Maxim/MAX78000/Source/system_riscv_max78000.c, Libraries/CMSIS/Device/Maxim/MAX78002/Source/system_max78002.c, Libraries/CMSIS/Device/Maxim/MAX78002/Source/system_riscv_max78002.c
This PR updates requires to peripheral drivers being used on zephyr side.
There are two commits one for MAX32662 being build, second for building zephyr with newlib.
MAX32662 build issue
Newlib buld issue: https://github.com/zephyrproject-rtos/zephyr/issues/73606
```
[168/173] Linking CXX executable zephyr/zephyr_pre0.elf
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map /Users/luisubieda/zephyrproject/zephyr/twister-out/max32690evkit_max32690_m4/tests/lib/cpp/cxx/cpp.main.newlib/zephyr/zephyr_pre0.map 
: && ccache /Users/luisubieda/zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++  -gdwarf-4 zephyr/CMakeFiles/zephyr_pre0.dir/misc/empty_file.c.obj -o zephyr/zephyr_pre0.elf  zephyr/CMakeFiles/offsets.dir/./arch/arm/core/offsets/offsets.c.obj  -fuse-ld=bfd  -T …
```
=> fix(CMSIS): Fix zephyr build issues

Libraries/zephyr/MAX/Include/wrap_max32_dma.h
MAX32657 driver functions require DMA instances. Because of that, I moved it into MAX32665/6 section. Also, I moved necessary register macros for MAX32657 into this section.
I added wrapper version of 'MXC_DMA_EnableInt' due to MSDK driver's changes.
=> chore(Other): Update Zephyr DMA wrapper for MAX32657

Libraries/zephyr/MAX/Include/wrap_max32_uart.h
Interrupt status need to be checked on zephyr side, to provide common interface we need a wrapper function due to MAX32662 int_en register named as inten.
Wrap_MXC_UART_GetRegINTEN function added.
=> chore(Other): Add a function in wrap_uart

Libraries/PeriphDrivers/Source/GPIO/gpio_me30.c
MAX32657: Does not support VSEL selection
=> fix(PeriphDrivers): MAX32657 does not support VSEL

Libraries/PeriphDrivers/Source/SYS/sys_ai85.c, Libraries/PeriphDrivers/Source/SYS/sys_ai87.c, Libraries/PeriphDrivers/Source/SYS/sys_me12.c, Libraries/PeriphDrivers/Source/SYS/sys_me14.c, Libraries/PeriphDrivers/Source/SYS/sys_me15.c, Libraries/PeriphDrivers/Source/SYS/sys_me16.c, Libraries/PeriphDrivers/Source/SYS/sys_me17.c, Libraries/PeriphDrivers/Source/SYS/sys_me18.c, Libraries/PeriphDrivers/Source/SYS/sys_me21.c
Fixes #1006 
This PR updates `MXC_SYS_GetUSN` to prevent buffer overflow.  The application-side buffer should be `MXC_SYS_USN_LEN`, but we were using `MXC_SYS_USN_CHECKSUM_LEN` which is a larger buffer size with some additional padding used for the internal CRC calculation.
=> fix(PeriphDrivers): Fix `MXC_SYS_GetUSN` Buffer Overflow

Libraries/PeriphDrivers/Source/GPIO/gpio_me30.c
This commit updates MXC_GPIO_Config according to GPIO hardware design. The register definitions shows similar padding functionality to MAX32675.
=> fix(PeriphDrivers): Fix Pulldown/Pullup Configuration for ME30

Libraries/PeriphDrivers/Source/CSI2/csi2_reva.c
It can happen that the g_frame_complete flag is never set, thus the device gets stuck in an endless loop. This is now checked by a timing constraint
=> fix(PeriphDrivers): Add CSI Capture Timeout

Libraries/CMSIS/Device/Maxim/MAX32650/Include/system_max32650.h, Libraries/PeriphDrivers/Source/SDHC/sdhc_ai87.c, Libraries/PeriphDrivers/Source/SDHC/sdhc_me10.c, Libraries/PeriphDrivers/Source/SDHC/sdhc_me13.c, Libraries/PeriphDrivers/Source/SDHC/sdhc_me14.c
According to the UG, SDHC peripheral is driven by always 96 MHz. Therefore, using System clock in the function MXC_SDHC_Get_Input_Clock_Freq results failure in SDHC peripheral when SytemClock is configured other than 96 MHz. Moreover, according to the UG the SDHC is driven by the 96 MHz Internal High-Speed Oscillator. Similar situations occur for ME10, ME13 and AI87 and commits relating to these MCUs will be pushed after this commit, discussions and related tests.
=> fix(PeriphDrivers): Fix SDHC Peripheral Failure for Alternative System Clocks

Examples/MAX78000/FreeRTOSDemo/project.mk, Libraries/FreeRTOS/Makefile, USERGUIDE.md
FreeRTOS gives some flexibility in the memory allocation scheme used to allow optimizing size/speed/heap fragmentation risk. The FreeRTOS documentation indicates that _heap_2.c is considered outdated_, and that _applications should at a minimum use heap_4 as an alternative_. Heap 4 uses a smarter allocation algorithm for avoiding heap fragmentation (first-fit algorithm + aggregates free RAM segments). 
Sources for info: 
https://www.freertos.org/a00111.html
https://github.com/FreeRTOS/FreeRTOS-Kernel-Book/blob/main/ch03.md
- Changed default FreeRTOS heap allocation to heap_4.c -heap_4 is recommended by FreeRTOS as an updated alternate to heap_2 for avoiding heap fragmentation 
- Added **FREERTOS_HEAP_TYPE** compile time macro to select the heap allocation method 
- Default value is 4, but …
=> perf(Other): Use FreeRTOS Heap Allocation Scheme 4, Allow Changing FreeRTOS Heap Allocation Scheme 

Libraries/Cordio/ble-profiles/include/app_api.h, Libraries/Cordio/ble-profiles/sources/af/app_master_ae.c
Updated the Extended scan functionality to allow the user to specify if duplicate packets should be filtered during the scanning process.  This was previously hard coded to TRUE.  The legacy Scan function remains hard coded for simplicity of use and compatibility with existing code bases.
All existing BLE example applications use the legacy AppScanStart call. This was tested against a customer project using the AppExtScanStart capability.
=> feat(BLE): Added User Configurable Duplicate Filtering

Libraries/PeriphDrivers/Source/UART/uart_reva.c, Libraries/PeriphDrivers/Source/UART/uart_revb.c
Fixes #998 
As the internal UART state struct was only initialized per _used_ UART instance, attempting to use UART1 (or higher) with DMA auto handlers would never trigger the user's callback functions.  The state struct's DMA channel values would be initialized to 0 instead of -1, which the drivers would assume was a valid channel acquisition.
This PR fixes the bug by initializing the UART state array correctly.
=> fix(PeriphDrivers): Fix UART DMA Callbacks for UART1+

Libraries/PeriphDrivers/Source/SPI/spi_ai87.c, Libraries/PeriphDrivers/Source/SPI/spi_es17.c, Libraries/PeriphDrivers/Source/SPI/spi_me11.c, Libraries/PeriphDrivers/Source/SPI/spi_me12.c, Libraries/PeriphDrivers/Source/SPI/spi_me13.c, Libraries/PeriphDrivers/Source/SPI/spi_me14.c, Libraries/PeriphDrivers/Source/SPI/spi_me15.c, Libraries/PeriphDrivers/Source/SPI/spi_me16.c, Libraries/PeriphDrivers/Source/SPI/spi_me17.c, Libraries/PeriphDrivers/Source/SPI/spi_me18.c, Libraries/PeriphDrivers/Source/SPI/spi_me21.c, Libraries/PeriphDrivers/Source/SPI/spi_me30.c, Libraries/PeriphDrivers/Source/SPI/spi_me55.c
This pull request addresses an issue in the DMA-based SPI transaction implementation where the DMA request would not be executed under specific conditions.
- **Issue**: When `MXC_SPI_MasterTransactionDMA` is called with `txData == NULL` and `rxData != NULL` in `SPI_WIDTH_STANDARD` (full duplex) mode, the function sets `reqselTx` to `-1`. However, in `MXC_SPI_RevA1_MasterTransactionDMA`, `MXC_SPI_RevA1_TransSetup` may additionally set `txData` based on the request. This leads to the [use of an invalid request selector](https://github.com/analogdevicesinc/msdk/blob/e1cae5bbb0bed43a754e487a99995dd85ca37b6a/Libraries/PeriphDrivers/Source/SPI/spi_reva1.c#L1019), causing the DMA to not be executed and resulting in an infinite wait state.
- **Call Stack**:
- …
=> fix(PeriphDrivers): Resolve incorrect DMA request in DMA-based SPI transactions for all parts

Libraries/zephyr/MAX/CMakeLists.txt, Libraries/zephyr/MAX/Source/MAX32655/CMakeLists.txt, Libraries/zephyr/MAX/Source/MAX32680/CMakeLists.txt, Libraries/zephyr/MAX/Source/MAX32690/CMakeLists.txt
Configures the zephyr build system to use the appropriate cmsis system startup and peripheral driver sources based on the target core architecture. The mxc lock driver is not implemented for risc-v and emits a build warning (which twister promotes to an error), therefore the zephyr build system is configured to build it only for arm.
Before this patch, we could only build zephyr for arm targets, but now we can build zephyr for arm or risc-v targets.
=> feat(Other): Enable building zephyr for risc-v targets

Libraries/PeriphDrivers/Source/SPI/spi_reva1.c
This pull request contains three commits to ensure that the `req->completeCB` callback of `MXC_SPI_MasterTransactionDMA` is only executed once. Previously, the `MXC_SPI_MasterTransactionDMA` function could trigger the `req->completeCB` callback multiple times, which is different from users' expectations (see Background & Problem).
The `MXC_SPI_MasterTransactionDMA` function initiates DMA requests up to two times. To execute `req->completeCB` only for the last DMA callback, there is an internal DMA callback counting mechanism.
1. [req->completeCB](https://github.com/analogdevicesinc/msdk/blob/b7b5ff1f5705434e025fd2755b9b0ed760f97972/Libraries/PeriphDrivers/Source/SPI/spi_reva1.h#L67): A user-provided callback that should be executed once after `MXC_SPI_MasterTransactionDMA` completes.
2. …
=> fix(PeriphDrivers): Ensure single execution of DMA-based SPI transaction callback for all parts

Libraries/Boards/MAX32690/EvKit_V1/board.mk, Libraries/PeriphDrivers/Source/I2C/i2c_me18.c
This PR adds a check for the `MAX32690GTK_PACKAGE_TQFN` compiler definition to work around MAX32690 Rev A2 Errata #16 (See https://www.analog.com/media/en/technical-documentation/data-sheets/max32690_a2_errata_rev2.pdf)
Testing found that the `MXC_I2C_Recover` function would fail for this package, but only if the unrouted set of pins were enabled.
The new definition is added to the board.mk file in the BSP for the EVKIT.  In this way, BSPs that use the TQFN package can match the hardware.
As implemented in #958, the WLP package enables both sets as recommended by the errata.  However, for the TQFN this seems to be problematic.  The I2C "scl" status bit in the control register always indicates the pin is at logic level 0 if the unrouted GPIOs are configured.
=> fix(PeriphDrivers): Fix MAX32690 I2C Recovery Failures for TQFN Package

.github/workflows/zephyr-hal.yml
The zepher-hal workflow is failing for PRs against forks because permission to write to remote repo is not granted. Changing the event type to `pull_request_target` grants these triggered workflows with write permissions.
=> fix(workflow): Grant PRs against forks access to write permissions

Libraries/PeriphDrivers/Include/MAX32690/mxc_sys.h, Libraries/PeriphDrivers/Source/SYS/sys_me18.c, Libraries/zephyr/MAX/Include/wrap_max32_sys.h
MAX32690 Support sysclk-div as per of [MAX32690-UG](https://www.analog.com/media/en/technical-documentation/user-guides/ug7618.pdf) and related register definition already added in CMSIS files.
This PR enable set and get sysclk-div feature.
Tested on MAX32690 with zephyr, it works.
=> feat(PeriphDrivers): Enable sysclk-div for MAX32690

Examples/MAX78002/ADC/main.c, Examples/MAX78002/CNN/facial_recognition/include/record.h, Examples/MAX78002/CNN/facial_recognition/src/record.c, Examples/MAX78002/CNN/kws20_demo/main.c, Examples/MAX78002/CNN/pascalvoc-retinanetv7_3/src/camera/camera.h, Examples/MAX78002/CNN/pascalvoc-retinanetv7_3/src/cnn/nms.c, Examples/MAX78002/CNN/pascalvoc-retinanetv7_3/src/sram/aps6404.c, Examples/MAX78002/CNN/pascalvoc-retinanetv7_3/src/sram/aps6404.h, Examples/MAX78002/CNN/pascalvoc-retinanetv7_3/src/sram/fastspi.c, Examples/MAX78002/CSI2/src/sram/aps6404.c, Examples/MAX78002/CSI2/src/sram/aps6404.h, Examples/MAX78002/CSI2/src/sram/fastspi.c, Examples/MAX78002/QSPI/aps6404.h, Examples/MAX78002/QSPI/fastspi.c, Examples/MAX78002/QSPI/main.c, Examples/MAX78002/Watchdog/main.c, Libraries/MiscDrivers/Camera/mipi_camera.c, Libraries/MiscDrivers/Camera/mipi_camera.h, Libraries/PeriphDrivers/Include/MAX78002/csi2.h, Libraries/PeriphDrivers/Source/CSI2/csi2_ai87.c, Libraries/PeriphDrivers/Source/CSI2/csi2_reva.c, Libraries/PeriphDrivers/Source/CSI2/csi2_reva.h, Libraries/PeriphDrivers/max78002_files.mk
Primarily fixes `-wtrict-prototype` warnings for the MAX78002 peripheral driver builds.  While I was at it I also fixed double promotion and some other misc. warnings in the examples.
The build system now skips CSI2 and mxc_lock driver files for RISC-V builds (i.e. when `RISCV_CORE = 1`) to avoid those warnings as well.
=> fix(PeriphDrivers): Fix `-wstrict-prototype` and other Misc. MAX78002 Warnings

Libraries/CMSIS/Device/Maxim/GCC/gcc_riscv.mk
If you try to build `https://github.com/analogdevicesinc/msdk/tree/main/Examples/MAX78002/RV_ARM_Loader`, this will fail because of a hardcoded interruption. I would propose to remove this line as it does not seem to serve anything and when removed the system builds without issues.
=> build(CMSIS): pointless RISC-V build system interruption

Libraries/Cordio/controller/sources/ble/ll/ll_main_dtm.c
Reference count now properly decremented when HCI abort is called.
=> fix(BLE): HCI Reset Reference Count

Libraries/CMSIS/Device/Maxim/MAX32572/Source/system_max32572.c
In the MAX32572, the `GCR_CLKCTRL.cryptoclk_div` value is set to 1 (not 0 as documented) on reset. This makes the CTB block run at half speed (ISO/2). This PR sets the CTB clock to its max speed (ISO) on startup.
=> fix(CMSIS): Set CTB clock to max frequency for MAX32572 startup

Libraries/PeriphDrivers/Source/TMR/tmr_me21.c
When MXC_ASSERT not enabled timer_id uses without being set for MAX32672 timer driver, this causes run timer issue and compiler gives warnings, see below.
This PR includes fix for this.
=> fix(PeriphDrivers): MAX32672 timer issue

Libraries/PeriphDrivers/Source/TMR/tmr_ai87.c
According to `data-sheets/MAX78002.pdf` page 43, IBRO is connected to LPTMR0 and LPTMR1.  
I actually tested this as I needed LPTMR0 to output IBRO.  
Therefore, `if (tmr_id > 3)` is wrong.
=> fix(PeriphDrivers): IBRO_CLK is connected to timers 4-5

Libraries/PeriphDrivers/Source/TPU/tpu_reva.c
=> fix(PeriphDrivers): Fix MAA Operator Setter for TPU Drivers

Libraries/Boards/MAX32690/EvKit_V1/Source/board.c, Libraries/MiscDrivers/Display/tft_st7735.c, Libraries/MiscDrivers/Display/tft_st7735.h
Slight modifications to the TFT LCD display drivers on the MAX32690 EV Kit V1 board.
- Removed delays in ``TFT_SPI_Write()`` to reduce the screen refresh time from 0.87129 seconds to 0.120858 seconds -- an 86% improvement.
- ``MXC_TFT_PrintFont()`` would use the initially set background color around the printed text. Added a function to offer color selection of both the background and the font text.
=> perf(Boards, MiscDrivers): Removed TFT CS delay and added new TFT function

Libraries/PeriphDrivers/Source/ADC/adc_me12.c, Libraries/PeriphDrivers/Source/ADC/adc_me21.c
Fixed build warning of ADC for MAX32672 and MAX32662 SoCs.
=> fix(PeriphDrivers): Fix build warnings for MAX32672 and MAX32662 ADC

Libraries/PeriphDrivers/Include/MAX32655/mxc_device.h
Adding PeriphDriver option for MAX32655 B1
=> chore(PeriphDrivers): Adding option for MAX32655 B1 0x4231.

Libraries/PeriphDrivers/Include/MAX32572/uart.h, Libraries/PeriphDrivers/Include/MAX32655/uart.h, Libraries/PeriphDrivers/Include/MAX32662/uart.h, Libraries/PeriphDrivers/Include/MAX32690/uart.h, Libraries/PeriphDrivers/Include/MAX78000/uart.h, Libraries/PeriphDrivers/Include/MAX78002/uart.h, Libraries/PeriphDrivers/Source/UART/uart_ai85.c, Libraries/PeriphDrivers/Source/UART/uart_me12.c, Libraries/PeriphDrivers/Source/UART/uart_me17.c, Libraries/PeriphDrivers/Source/UART/uart_me55.c
This PR is an extended addon to https://github.com/analogdevicesinc/msdk/pull/1108 for the UART RevB drivers. Since the parameters for the `MXC_UART_RevB_SetFrequency` were changed, the parts without these new functions did not properly set the baud rate.
Only tested on ME17 so far.
=> fix(PeriphDrivers): Add UART Clock Setter API for all parts using UART RevB Drivers

Libraries/Cordio/platform/include/pal_version.h
This API will be used to get version information from pre-built libraries. Library versions can also be seen by inspecting the library objects.
``` bash
arm-none-eabi-objdump -a libphy.a | grep "version"
pal_version_v0.0.0+988c0c7a.20240805.o:     file format elf32-littlearm
rw-rw-r-- 1000/1000   3728 Aug  5 13:14 2024 pal_version_v0.0.0+988c0c7a.20240805.o
```
=> feat(BLE): Adding header file for PAL version.

Libraries/CMSIS/Device/Maxim/GCC/gcc.mk, Libraries/CMSIS/Device/Maxim/GCC/gcc_riscv.mk
Add the --print-memory-usage option to the linker arguments for a end-of-build breakdown of usage.
```
- LD /c/Workspace/MSDK_Development/brentk-adi-fork/Examples/MAX32650/CLCD_FreeRTOS/build/CLCD_FreeRTOS.elf
Memory region         Used Size  Region Size  %age Used
ROM:          0 GB        64 KB      0.00%
FLASH:       60880 B         3 MB      1.94%
SRAM:      637696 B         1 MB     60.82%
arm-none-eabi-size --format=berkeley /c/Workspace/MSDK_Development/brentk-adi-fork/Examples/MAX32650/CLCD_FreeRTOS/build/CLCD_FreeRTOS.elf
text    data     bss     dec     hex filename
58300    2580  634624  695504   a9cd0 C:/Workspace/MSDK_Development/brentk-adi-fork/Examples/MAX32650/CLCD_FreeRTOS/build/CLCD_FreeRTOS.elf
```
=> feat(Build): Add --print-memory-usage to linker options

Libraries/PeriphDrivers/Source/UART/uart_reva.c, Libraries/PeriphDrivers/Source/UART/uart_revb.c, Libraries/PeriphDrivers/Source/UART/uart_revc.c
The UART drivers' 'states' variable was not statically limited in scope to their respective files. Aside from potentially corrupting data, since the name 'states' is fairly common, could cause conflict with user's legacy code which might have a 'states' global.
=> fix(PeriphDrivers): Static scoping for UART driver variables

Libraries/Cordio/controller/sources/ble/bb/bb_ble_int.h
Using definition of 150 us for default TIFS time.
=> fix(BLE): Setting default TIFS time

Libraries/Cordio/platform/targets/maxim/max32655/sources/pal_uart.c, Libraries/Cordio/platform/targets/maxim/max32690/sources/pal_uart.c
PalUartInit operates in an async fashion and relies on interrupts, but did not enable them as needed. This PR handles that.
=> fix(BLE): Enable IRQ in PalUartInit

Libraries/Cordio/controller/sources/ble/init/init.c, Libraries/Cordio/platform/targets/maxim/build/config_maxim.mk
Separating PHY features from EXT. Using default 16 us for window widening constant.
=> fix(BLE): PHY features and Window Widening constant

Libraries/zephyr/MAX/Include/wrap_max32_spi.h
For MAX32657 and MAX32662, DMA TX and RX enable fields are named `MXC_F_SPI_DMA_TX_EN` and `MXC_F_SPI_DMA_RX_EN` respectively. Handle these differences in zephyr SPI wrapper.
=> fix(Other): Fix SPI DMA enable field mapping for MAX32657 and MAX32662

Examples/MAX32660/TMR/main.c
Fixes #1122 
Also fixes warning about using a function in a constant expression.
=> fix(Examples): Fix DUTY_CYCLE Functionality for MAX32660 TMR Example

Libraries/PeriphDrivers/Source/UART/uart_revb.c
This prevent un-intended interrupts, causing txCnt to exceend txLen. If the HE interrupt is enabled while we're filling the FIFO, then we can get the interrupt while we're filling. This interrupts the filling process, leading to txCnt exceeding txLen. 
This is only an issue in the initial fill, since we're probably not in the interrupt context. When we're in the interrupt context, we may get another HE interrupt flag from the UART, but it won't interrupt the CPU, and we clear the flag after completing the fill.
=> fix(PeriphDrivers): Leaving UART HE interrupt disabled during initial fill.

Libraries/PeriphDrivers/Include/MAX78002/spi.h, Libraries/PeriphDrivers/Source/SPI/spi_ai87.c, Libraries/PeriphDrivers/Source/SPI/spi_ai87_v2.c
AI87 SPI drivers don't have 'MXC_SPI_HWSSControl' function. I added this function to both SPI driver. For v1, I called related revA1 function and for v2, do nothing.
=> fix(PeriphDrivers): Add SPI hardware SS control function for AI87

Libraries/PeriphDrivers/Source/GPIO/gpio_ai85.c, Libraries/PeriphDrivers/Source/GPIO/gpio_ai87.c, Libraries/PeriphDrivers/Source/GPIO/gpio_es17.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me13.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me14.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me17.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me18.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me20.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me30.c, Libraries/PeriphDrivers/Source/GPIO/gpio_me55.c, Libraries/PeriphDrivers/Source/GPIO/gpio_revb.c, Libraries/PeriphDrivers/Source/SYS/pins_me18.c
Apparently most UGs have this flipped.  _Strong_ should set the `ps` field to 0, while _weak_ should set it to `1`.
=> fix(PeriphDrivers): Flip strong vs weak pull-up bit values

Libraries/PeriphDrivers/Source/ADC/adc_me18.c, Libraries/PeriphDrivers/Source/ADC/adc_revb.c, Libraries/PeriphDrivers/Source/ADC/adc_revb.h, Libraries/PeriphDrivers/Source/TMR/tmr_me18.c, Libraries/PeriphDrivers/Source/TMR/tmr_revb.c, Libraries/PeriphDrivers/Source/TMR/tmr_revb.h, Libraries/PeriphDrivers/Source/UART/uart_me18.c, Libraries/PeriphDrivers/Source/UART/uart_revb.c, Libraries/PeriphDrivers/Source/UART/uart_revb.h
Closes [CFSIO-2300](jira.analog.com/browse/CFSIO-2300)
Only issue a full reset to ADC, TMR, & UART if the clock source has not already been previously locked.  Otherwise CFS's clock config will be clobbered.
=> fix(PeriphDrivers): MAX32690 Only Reset ADC, TMR, UART if Clock is not Locked

Libraries/PeriphDrivers/Include/MAX32665/dma.h, Libraries/PeriphDrivers/Source/DMA/dma_me14.c, Libraries/PeriphDrivers/Source/I2C/i2c_reva.c
This PR fixes various I2C DMA issues that are caused by slaves that intentionally NACK their I2C address, such as the [MS8607](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FMS8607-02BA01%7FB3%7Fpdf%7FEnglish%7FENG_DS_MS8607-02BA01_B3.pdf%7FCAT-BLPS0018).
Fixes #987 
Ex:
Previously, `MXC_I2C_MasterTransactionDMA` would send the read request and then immediately start reading from the I2C RX FIFO with DMA.  If the slave NACKs that address, no further bytes will be sent.  Therefore the DMA request will never complete and DMA callbacks will never be hit, all the while the master locks up and holds the SCL line low.
Now, we wait to see if we got an ACK or a NACK immediately after we send the read request.  If we get a NACK, we abort the …
=> fix(PeriphDrivers): Fix I2C DMA Issues When Slave Does Not ACK Address, Fix 1-length I2C DMA Transactions

Libraries/CMSIS/Device/Maxim/MAX32675/Include/max32675.h, Libraries/PeriphDrivers/Include/MAX32670/uart.h, Libraries/PeriphDrivers/Include/MAX32672/uart.h, Libraries/PeriphDrivers/Include/MAX32675/uart.h, Libraries/PeriphDrivers/Source/AFE/hart_uart.c, Libraries/PeriphDrivers/Source/UART/uart_me15.c, Libraries/PeriphDrivers/Source/UART/uart_me16.c, Libraries/PeriphDrivers/Source/UART/uart_me21.c, Libraries/PeriphDrivers/Source/UART/uart_me30.c, Libraries/PeriphDrivers/Source/UART/uart_revb.c
Fixes functional regression caused by #1113 
Calls to MXC_UART_RevB_SetFrequency weren't updated for these parts after changing the RevB API.  As a result, `MXC_UART_RevB_GetTXFIFOAvailable` would eventually hang as the UART FIFO compeltely fills up and is never emptied due to misconfiguration.
Symptoms were that `printfs` would eventually infinitely hang.  i.e. even `Hello_World` wouldn't work.
This PR should fix the regressions.
Also removed `MXC_UART1` and `MXC_UART3` definitions for ME16.  These don't exist on the micro.
=> fix(PeriphDrivers): Fix UART Functional Regression for MAX32670, MAX32672, MAX32675, MAX32657

Examples/MAX32690/Hello_World/README.md
Adds a note that the UART pins on the APARD board are only available on the SWD connector, and aren't available on other emulators like a Segger JLink.
=> fix(Documentation): MAX32690 Hello_World add note on UART

Libraries/PeriphDrivers/Source/UART/uart_ai87.c, Libraries/PeriphDrivers/Source/UART/uart_me12.c, Libraries/PeriphDrivers/Source/UART/uart_me30.c, Libraries/PeriphDrivers/Source/UART/uart_me55.c
Now that MXC_UART_RevB_SetFrequency doesn't set the OSR value, set it in all the drivers that call this function if it isn't set there already. The impact of the issue was that MAX78002 wasn't working at the requested baud rate.
The MSDK repo follows a custom rule set based on the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard. The pull request titles will follow this format:
`type(scope)<!>: Subject`
The list of possible types are:
1.  **fix** – a bug fix has occurred
2.  **feat** – a new feature was introduced
3.  **chore** – changes that do not relate to a fix or feature, or a catch-all type for changes that don’t really fit under any of the other types
4.  **refactor** – refactored code that neither fixes a bug nor adds a new feature
5.  **docs** – …
=> fix(PeriphDrivers): Set default osr value

Libraries/PeriphDrivers/Source/SYS/sys_me30.c, Libraries/zephyr/MAX/CMakeLists.txt, Libraries/zephyr/MAX/Source/MAX32657/partition_max32657.h
This PR apply fix for MAX32657 zephyr.
- MXC_SYS_LockDAP_Permanent should be called only for secure mode
- Empty partition_max32657.h file added to it build on zephyr side as it is
=> chore(Other, PeriphDrivers): Fix MAX32657 build issue

Examples/MAX32690/Dual_Core_Sync/Dual_core_sync_arm/README.md, Examples/MAX32690/Dual_Core_Sync/Dual_core_sync_riscv/README.md, Examples/MAX32690/Hello_World/README.md, Examples/MAX78002/Hello_World/README.md, Examples/MAX78002/RV_ARM_Loader/README.md
Only doing this for MAX32690 and MAX78002 template examples. We should roll out to other READMEs in due course.
- Specify that you need to connect an emulator
- Specify that if you're using a non-PICO, and it's a MAX32690 FTHR or APARD, you can't get UART
- Add connections for Loader example for MAX78002
- Fix name of USB socket to match boards
The MSDK repo follows a custom rule set based on the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard. The pull request titles will follow this format:
`type(scope)<!>: Subject`
The list of possible types are:
1.  **fix** – a bug fix has occurred
2.  **feat** – a new feature was introduced
3.  **chore** – changes that do not relate to a fix or feature, or a catch-all type for changes that don’t really fit under any of …
=> fix(Examples): Try to clarify UART capabilities

Libraries/PeriphDrivers/Source/UART/uart_me12.c, Libraries/PeriphDrivers/Source/UART/uart_me15.c, Libraries/PeriphDrivers/Source/UART/uart_me16.c, Libraries/PeriphDrivers/Source/UART/uart_me17.c, Libraries/PeriphDrivers/Source/UART/uart_me18.c, Libraries/PeriphDrivers/Source/UART/uart_me21.c
While adding MXC_UART_SetClockSource(uart, clock); function it seems zephyr build been broken
this commit fix them for UART
=> chore(Other, PeriphDrivers): Fix MAX32xxx UART build issue

Libraries/zephyr/MAX/Source/MAX32657/CMakeLists.txt
MAX32657 does not have a separate I2C controller. Replace I2C with I3C in Zephyr's CMakeLists.txt.
=> fix(Other): Add I3C to MAX32657 Zephyr build

Libraries/PeriphDrivers/Include/MAX78002/mxc_sys.h, Libraries/PeriphDrivers/Source/SYS/sys_ai87.c
MAX78002 Support sysclk-div as per of [MAX78002-UG](https://www.analog.com/media/en/technical-documentation/user-guides/max78002-user-guide.pdf) and related register definition already added in CMSIS files.
This PR enable set and get sysclk-div feature.
=> feat(PeriphDrivers): Enable sysclk-div for MAX78002

Libraries/zephyr/MAX/Include/wrap_max32_tmr.h
Added ISO clock as a timer clock source for MAX32655 and MAX32680.
=> fix(Other): Add ISO as a timer clock source for MAX32655 and MAX32680

Libraries/CMSIS/Device/Maxim/MAX32657/Include/max32657.h
Use cmsis_gcc_m for MAX32657 if CMSIS version equal to [v6.0](https://github.com/ARM-software/CMSIS_6/blob/v6.0.0/CMSIS/Core/Include/cmsis_version.h)
With CMSIS 6.0 cmsis_gcc.h file has been replaced with cmsis_gcc_m.h.
[TF-M uses CMSIS v6.0](https://github.com/zephyrproject-rtos/trusted-firmware-m/blob/main/platform/ext/cmsis/CMSIS/Core/Include/cmsis_version.h) to support TF-M without adding a wrapper file max32657.h file has been updated.
After cmsis v6.0 ([v6.1](https://github.com/ARM-software/CMSIS_6/blob/v6.1.0/CMSIS/Core/Include/cmsis_version.h)) , cmsis_gcc.h file added inside CMSIS files so exception case should be executed just for v6.0
=> feat(CMSIS): Add CMSIS 6.0 support to MAX32657

Libraries/PeriphDrivers/Source/TMR/tmr_revb.c
We have a locking mechanism so that if we've locked the TMR clock, then calling MXC_TMR_Init() function doesn't reset them.
However, the lock check is implemented in MXC_TMR_RevB_SetClockSource, which is called by MXC_TMR_SetClockSource. However, MXC_TMR_SetClockSource also calls MXC_TMR_RevB_SetClockSourceFreq, which has no lock check.
The result is that if MXC_TMR_Init is called with a clock source of, say, ERFO, then we cache the new frequency, 32MHz, but then don't reconfigure the MMRs to actually run using ERFO. So the TMR driver operates believing it is running at 32MHz, but actually running at something else. This means that things like the Stop Watch timer report the wrong wall time.
=> fix(PeriphDrivers): Don't cache TMR clock frequency if locked

Libraries/PeriphDrivers/Include/MAX32670/uart.h, Libraries/PeriphDrivers/Include/MAX32672/uart.h, Libraries/PeriphDrivers/Include/MAX32675/uart.h, Libraries/PeriphDrivers/Source/UART/uart_ai85.c, Libraries/PeriphDrivers/Source/UART/uart_ai87.c, Libraries/PeriphDrivers/Source/UART/uart_me12.c, Libraries/PeriphDrivers/Source/UART/uart_me15.c, Libraries/PeriphDrivers/Source/UART/uart_me16.c, Libraries/PeriphDrivers/Source/UART/uart_me17.c, Libraries/PeriphDrivers/Source/UART/uart_me18.c, Libraries/PeriphDrivers/Source/UART/uart_me21.c
With new UART RevB clock source selection updates, some problems occurred on Zephyr RTOS side. Also, I noticed some problems about MSDK side too. In this PR, 
- Fixed these build issues.
- Disabled GPIO and clock enablement for Zephyr side.
- To avoid from duplication, I moved clock source enablement from init function to clock source selection function.
- Added get function for clock source for ME15 and ME21
=> fix(PeriphDrivers): Fix UART clock source issues

Libraries/PeriphDrivers/Source/TMR/tmr_reva.c, Libraries/PeriphDrivers/Source/TMR/tmr_revb.c, Libraries/PeriphDrivers/Source/TMR/tmr_revc.c
When the timer frequency is small, e.g. 1.8MHz, then dividing this frequency by 1000000 as an integer gives a huge error since it will round down to 1. Improve things by only dividing by 1000 rather than 1000000. We can multiply by 1000 in the numerator, because the prescale value is at most 128, and so 128 * 1000000 fits in uint32_t, and this is then multiplied by ticks which is also 32 bits but widened to 64 bits for the multiply. So the numerator won't overflow.
=> fix(PeriphDrivers): Improve accuracy of timer stop watch

Libraries/PeriphDrivers/Source/SYS/pins_me17.c, Libraries/PeriphDrivers/Source/SYS/pins_me18.c
Addresses issues #1182 and #1181
The pins definition for the external clock was wrong. 
It is only available on P0.3, not P0.12 and P0..13. Furthermore, the alternate function was wrong. It is ALT1 not ALT2 
The image above is for the WLP, but the pin mapping is true for all package variants. 
Antenna control 0 and 1 was flipped for ME18
=> fix(PeriphDrivers): Corrected pin definitions for BLE chips

Libraries/PeriphDrivers/Source/SYS/sys_me12.c, Libraries/PeriphDrivers/Source/SYS/sys_me15.c, Libraries/PeriphDrivers/Source/SYS/sys_me17.c
- On ME17, the **BLE4_ctrl** and **BLE5_ctrl** examples were failing a checksum verification in `MXC_SYS_GetUSN()` and were unable to finish executing `PalCfgLoadData()`.
- This error was also found on boards with a similar implementation of `MXC_SYS_GetUSN()`. Namely, ME12 and ME15.
- Change the length of a USN buffer from 13 to 16, which is 4-byte aligned, to successfully pass the checksum verification in `MXC_SYS_GetUSN()`.
- Only the board's respective `sys_me1x.c` file is affected.
The following code snippet may be used to duplicate the error:
```C
/**
* @file    main.c
* @brief   Hello World!
* @details This example uses the UART to print to a terminal and flashes an LED.
*/
/***** Includes *****/
#include <stdio.h>
#include <stdint.h>
#include "mxc_device.h"
#include "led.h" …
```
=> fix(PeriphDrivers): Resize the USN buffer in checksum verification for MAX32655, MAX32662, and MAX32670

Libraries/CMSIS/Device/Maxim/GCC/gcc.mk, Libraries/CMSIS/Device/Maxim/GCC/gcc_riscv.mk
This was added after the March 2024 release. Before this change, I noticed a non-critical python error at the beginning of the build.
=> fix(Build): Don't update version when working in non-GitHub environments

Libraries/CMSIS/Device/Maxim/MAX32675/Include/afe_adc_one_regs.h, Libraries/CMSIS/Device/Maxim/MAX32675/Include/afe_adc_zero_regs.h, Libraries/CMSIS/Device/Maxim/MAX32680/Include/afe_adc_one_regs.h, Libraries/CMSIS/Device/Maxim/MAX32680/Include/afe_adc_zero_regs.h, Libraries/PeriphDrivers/Source/AFE/afe_adc_one_reva.svd, Libraries/PeriphDrivers/Source/AFE/afe_adc_zero_reva.svd
Temp Sensor Defeatured.
Part ID register address in for ADC Zero was incorrect.
=> fix(CMSIS): Purge MAX32675, MAX32680 Temp Sensor defines, Fix Part ID Address

Libraries/PeriphDrivers/Include/MAX32665/uart.h
Docstring for return of ``MXC_UART_Init`` now correctly states E_NO_ERROR is returned if successful.
=> fix(Documentation): Update MXC_UART_Init return docstring

Libraries/PeriphDrivers/Source/AFE/afe.c, Libraries/PeriphDrivers/Source/AFE/hart_uart.c
Use APB clock for HART UART to avoid case where UART clock is faster than system/periph clock to ensure UART interrupt actually vector.
Prevent bogus byte transmission due to interrupt occurring during manual FIFO load.
Minor corrections from previous PR code review.
=> fix(PeriphDrivers): Correct HART UART Driver Transmit Bugs

Libraries/PeriphDrivers/Source/FLC/flc_me30.c
Info block unlock sequence changes device to device to use same function as it is unlock function need to be overwritten.
This PR make it weak to it be done.
=> feat(PeriphDrivers): Allow info block unlock function be overwritten

Libraries/PeriphDrivers/Source/LP/lp_me12.c
Shutdown function is defined as `MXC_LP_EnterShutDownMode` in lp.h however is implemented as `MXC_LP_EnterPowerDownMode` in lp_me12.c. Change its name in lp_me12.c to `MXC_LP_EnterShutDownMode` to make it consistent.
=> fix(PeriphDrivers): Fix Mismatched Implementation for MAX32662 `MXC_LP_EnterShutDownMode`

Libraries/Boards/MAX78000/FTHR_RevA/Source/board.c
One of the customers reported that they can't use P2.3 pin on MAX78000 FTHR even they enable interrupt and configure callback function. Interrupt is not triggered, and callback function is not called.
I figured out that GPIO2_IRQ_Handler was not defined even as a weak function in board.c file. I thought it might be better to have a weak definition for GPIO2 interrupts as well. So, users can also override this function in their application if needed.
=> fix(Boards): Add GPIO2_IRQ_Handler for MAX78000 FTHR_RevA

Libraries/CMSIS/Device/Maxim/MAX32672/Include/max32672.h
Remove inclusion of trimsir_regs.h and aes_regs.h from max32672.h. They are causing redefinition warnings for `#define __I volatile const` macro in some cases.
=> chore(CMSIS): Remove unused includes for MAX32672

Examples/MAX32655/UART_DMA/main.c, Examples/MAX32665/Bluetooth/Bootloader/README.md, Examples/MAX32665/Bluetooth/Bootloader/boot_lower.S, Examples/MAX32665/Bluetooth/Bootloader/bootloader.ld
Final PR to fix a warning for release.
Also tacks on a fix for failing Build_Examples workflow with a memory overflow issue.
**Create a merge commit**, NOT a squash and merge.
=> fix(Examples): Fix warning in MAX32655/UART_DMA example and increase Bootloader app size for MAX32665

Libraries/CMSIS/Device/Maxim/MAX32657/Include/gpio_regs.h, Libraries/CMSIS/Device/Maxim/MAX32657/Include/max32657.svd, Libraries/CMSIS/Device/Maxim/MAX32657/Include/spi_regs.h, Libraries/CMSIS/Device/Maxim/MAX32657/Include/trimsir_regs.h, Libraries/PeriphDrivers/Include/MAX32657/gpio.h, Libraries/PeriphDrivers/Source/GPIO/gpio_me30.c, Libraries/PeriphDrivers/Source/GPIO/gpio_reva_me30.svd, Libraries/PeriphDrivers/Source/RTC/rtc_me30.c, Libraries/PeriphDrivers/Source/SPI/spi_reva_me30.svd, Libraries/PeriphDrivers/Source/SYS/SVD/trimsir_me30.svd, Libraries/PeriphDrivers/Source/WUT/wut_me30.c
- fix build errors
- remove TS3 from SPI registers. ME30 only supports 3 target select lines
- update GPIO pad controls to match ME12 design
=> fix(CMSIS,PeriphDrivers): Remove SPI TS3, fix GPIO pad controls, and fix build errors for MAX32657

Libraries/PeriphDrivers/Source/ADC/adc_ai87.c
Fixed build warnings of ADC driver for MAX78002 SoC.
=> fix(PeriphDrivers): Fix build warnings for MAX78002 ADC

Libraries/Cordio/platform/targets/maxim/max32655/sources/pal_uart.c, Libraries/Cordio/platform/targets/maxim/max32690/sources/pal_uart.c
Previously, the UART clock was fed off of the ``APB`` clock, which is derived from the ``IPO``. Nonproduction parts commonly have inaccurate trims for the ``IPO``. This makes the UART not work as the baud rate is off. ``IBRO`` is a slower more accurate clock, which does not have this issue. 
Changes:
- Initialize all UART using ``pal_uart`` to be on ``IBRO``
=> fix(BLE): Update PAL UART to derive clock via IBRO

.github/workflows/clang-format-run-pr.yml
Clang-format workflow not working. Not sure if it's because of the deprecated Node16.js that the workflow was using or if it's a permission issue with this repo.
=> fix(workflow): Update clang-format-run-pr.yml to Node20.js and update permissions

.github/workflows/BLE_Examples_Test.yml, Libraries/Cordio/controller/sources/ble/init/init.c
- `LlInitSetRtCfg()` was first implemented in the [mallinfo PR](https://github.com/analogdevicesinc/msdk/pull/1179/files#diff-7d918cdc331800eea5a880227f42b3b870c5b4529dc90a38978c1f218cd6c08a)
- `totalMemUsed` was not utilized.  `memUsed` was incremented -- instead of overwritten -- when calling `LlInitSetLlRtCfg()` in addition to the preceding `LlInitSetBbRtCfg()`, whose memory usage was already accounted for. This is not accurate.
- Leverage `totalMemUsed`
- Overwrite `memUsed` when calling either `LlInitSetLlRtCfg()` or `LlInitSetBbRtCfg()`
=> fix(BLE): Resolve double increment of memory management in LlInitSetRtCfg

Libraries/PeriphDrivers/Include/MAX32657/gpio.h
Zephyr drivers requires pullup and pulldown definition. This commit fix build issue on zephyr side
=> fix(PeriphDrivers): Zephyr build issue

Libraries/libs.mk
The libs.mk file used an undefined variable (LIBRARY_VARIANT) when selecting which version of the nfc library to include.  The correct variable to use is MFLOAT_ABI.
=> Fix error in libs.mk when building for NFC

Libraries/CMSIS/5.9.0/Core/Include/core_rv32.h
Added Arm's ``NVIC_GetEnableIRQ`` for RV32.
Returns 1 if IRQ is enabled. 
Returns 0 otherwise.
=> feat(CMSIS): Added NVIC_GetEnableIRQ for RV32

Libraries/libs.mk
The libs.mk file used an undefined variable (LIBRARY_VARIANT) when selecting which version of the nfc library to include. The correct variable to use is MFLOAT_ABI.
=> build(Other): Fix incorrect variable name used for NFC library selection for MAX32670, MAX32671, and MAX32672

Examples/MAX32655/Bluetooth/RF_Test/main.c, Examples/MAX32665/Bluetooth/RF_Test/main.c, Examples/MAX32690/Bluetooth/RF_Test/main.c
Updated example to pass the coded mode option instead of the S2 or S8 option.
Addresses #1249
=> fix(Examples): Fixed PHY selection bug in RF Test

Libraries/CMSIS/Device/Maxim/GCC/gcc.mk
Added CXX_STANDARD flag used in project.mk as ``CXX_STANDARD=14``.Which results in ``-std=c++14`` default value is 17 if not specified
=> feat(Build): Added CXX_STANDARD flag to override default when compiling for C++

Libraries/PeriphDrivers/Source/I2C/i2c_reva.c
Fixed issues in ``MXC_I2C_RevA_MasterTransaction`` where after stop condition sent, the code spun on the stop condition send bit being cleared. The ``MSTRCTRL`` stop bit is cleared when the stop condition has started, we spin while that bit is 0, therefore we always spin since it clears instantly, or at least faster than the processor can read it.  
The original interrupt flag check is wrong too, since it detects when a stop condition occurs. The correct logic is to wait on the send bit until hardware clears it for us. This most likely previously worked because of this line 
``i2c->intfl0 = MXC_F_I2C_REVA_INTFL0_DONE;``. Meaning although "safer" we probably don't need to wait for the stop condition to be sent.
Address #1261
=> fix(PeriphDrivers): I2C REVA Inifnite Loop

Libraries/zephyr/MAX/Source/MAX32655/CMakeLists.txt, Libraries/zephyr/MAX/Source/MAX32657/CMakeLists.txt
When BT is selected during a zephyr build, need to also include msdk hal driver support for aes as we do not have any zephyr aes driver in zephyr layer.
=> fix(BLE): Zephyr: enable aes driver when BT selected.

Libraries/Cordio/platform/targets/maxim/max32655/sources/pal_cfg.c, Libraries/Cordio/platform/targets/maxim/max32665/sources/pal_cfg.c, Libraries/Cordio/platform/targets/maxim/max32690/sources/pal_cfg.c
This solves a Bluetooth test mode problem when receiving long packets. Increasing the sync time to 10 ms prevents the receiver from timing out while receiving packets from the tester.
=> fix(BLE): Setting dtmRxSyncMs to 10.

Libraries/PeriphDrivers/Include/MAX32675/mxc_pins.h, Libraries/PeriphDrivers/Include/MAX32680/mxc_pins.h, Libraries/PeriphDrivers/Source/AFE/hart_uart.c, Libraries/PeriphDrivers/Source/SYS/pins_me16.c, Libraries/PeriphDrivers/Source/SYS/pins_me20.c
Use dedicated gpio structure for HART UART to avoid collision issues with multiple mappings.
=> fix(PeriphDrivers): Fix GPIO Structure Collision for HART UART

Examples/MAX32657/Bluetooth/BLE5_ctr/project.mk
The BLE5_ctr example for the MAX32657 was failing to find the `libphy.a` file. The `project.mk` file was modified accordingly.
=> fix(Examples): Link to the libphy.a directory in MAX32657 BLE5_ctr

Libraries/PeriphDrivers/Source/UART/uart_me16.c
ME16 (MAX32675) will currently always fail to initialize its UART. This is because the logic inside the SetClockSource function uses an || instead of an && for checking mutually exclusive conditions:
```C
// FIXME: CHANGE FROM || TO &&
if (MXC_UART_GET_IDX(uart) != 0 || MXC_UART_GET_IDX(uart) != 2) { 
return E_BAD_PARAM;
}
```
Because the UART is for sure _either_ 0 or 2, this check will always fail. The correct operation is to use && for this sort of check. That's the only change in this PR.
=> fix(PeriphDrivers): Fix bad logic on ME16 UART IDX checking in MXC_UART_SetClockSource.

Libraries/zephyr/MAX/Include/wrap_max32_adc.h, Libraries/zephyr/MAX/Include/wrap_max32_dma.h, Libraries/zephyr/MAX/Include/wrap_max32_i2c.h, Libraries/zephyr/MAX/Include/wrap_max32_lp.h, Libraries/zephyr/MAX/Include/wrap_max32_owm.h, Libraries/zephyr/MAX/Include/wrap_max32_spi.h, Libraries/zephyr/MAX/Include/wrap_max32_sys.h, Libraries/zephyr/MAX/Include/wrap_max32_tmr.h, Libraries/zephyr/MAX/Include/wrap_max32_trng.h, Libraries/zephyr/MAX/Include/wrap_max32_uart.h, Libraries/zephyr/MAX/Include/wrap_max32_wdt.h
The 'if defined(FOO) || BAR' lines are not clear
$ sed 's, (CONFIG_SOC, defined(CONFIG_SOC,g' -i $(git grep --name-only  if.defined\(.*\|\|.\() $ sed 's,||\s*\\$,\|\| \\,g' -i $(git grep --name-only '||.*\\$')
Not much to add other than the subject of the single git commit above.
=> style(Other): Update conditional compilation directives for `CONFIG_SOC_*` definitions in Zephyr wrapper

Libraries/PeriphDrivers/Source/FLC/flc_me30.c
This PR updates the Unlock/Lock Info Block functions using the correct unlock sequence.
It has a different sequence from the FLC RevA drivers.
=> fix(PeriphDrivers): Update the info block unlock sequence for the MAX32657

Libraries/CMSIS/Device/Maxim/MAX32655/Include/max32655.svd, Libraries/CMSIS/Device/Maxim/MAX32655/Include/tmr_regs.h, Libraries/CMSIS/Device/Maxim/MAX32657/Include/max32657.svd, Libraries/CMSIS/Device/Maxim/MAX32657/Include/tmr_regs.h, Libraries/CMSIS/Device/Maxim/MAX32670/Include/max32670.svd, Libraries/CMSIS/Device/Maxim/MAX32670/Include/tmr_regs.h, Libraries/CMSIS/Device/Maxim/MAX32672/Include/max32672.svd, Libraries/CMSIS/Device/Maxim/MAX32672/Include/tmr_regs.h, Libraries/CMSIS/Device/Maxim/MAX32675/Include/max32675.svd, Libraries/CMSIS/Device/Maxim/MAX32675/Include/tmr_regs.h, Libraries/CMSIS/Device/Maxim/MAX32690/Include/max32690.svd, Libraries/CMSIS/Device/Maxim/MAX32690/Include/tmr_regs.h, Libraries/CMSIS/Device/Maxim/MAX78000/Include/max78000.svd, Libraries/CMSIS/Device/Maxim/MAX78000/Include/tmr_regs.h, Libraries/CMSIS/Device/Maxim/MAX78002/Include/max78002.svd, Libraries/CMSIS/Device/Maxim/MAX78002/Include/tmr_regs.h, Libraries/PeriphDrivers/Source/TMR/tmr_revb.svd, Libraries/PeriphDrivers/Source/TMR/tmr_revb_me15.svd, Libraries/PeriphDrivers/Source/TMR/tmr_revb_me17.svd, Libraries/PeriphDrivers/Source/TMR/tmr_revb_me21.svd, Libraries/PeriphDrivers/Source/TMR/tmr_revb_me30.svd, Libraries/PeriphDrivers/Source/TMR/tmr_revb_regs.h, Libraries/PeriphDrivers/Source/UART/uart_revb_regs.h
This PR adds the missing TMR register field `TMRn_CTRL1.async[15]` which allows asynchronous reads to the TMR PWM and CNT registers. Only the parts with the TMR RevB IP are affected by this change.
Also regenerated the UART RevB register file to include the new UART one byte remaining interrupt.
=> fix(CMSIS,PeriphDrivers): Add TMR RevB `CTRL1.async` field which allows asynchronous reads to the PWM and CNT registers

Libraries/PeriphDrivers/Source/SPI/spi_me30.c
This PR makes following changes to MAX32657 SPI driver.
1. Configure correct pins during MAX32657 SPI initialization.
- MOSI: P0.2
- MISO: P0.4
- CS0: P0.3
- SCK: P0.6
2. Use correct peripheral clock rate.
Input clock for MAX32657 SPI should be APB / 2. Otherwise we get half of the calculated frequency on the SCK pin.
=> fix(PeriphDrivers): Fix SPI pins and peripheral clock for MAX32657

Libraries/CMSIS/Device/Maxim/MAX32657/Include/system_max32657.h, Libraries/CMSIS/Device/Maxim/MAX32657/Source/system_max32657.c, Libraries/PeriphDrivers/Include/MAX32657/mxc_pins.h, Libraries/PeriphDrivers/Include/MAX32657/mxc_sys.h, Libraries/PeriphDrivers/Source/SYS/pins_me30.c, Libraries/PeriphDrivers/Source/SYS/sys_me30.c
Uncomment clock selection code to allow external clock input to be used as system clock since external clock pin and system clock selection bits are now known.
Set INRO clock frequency to 131kHz.
=> feat(CMSIS,PeriphDrivers): Enable external clock selection on MAX32657

Libraries/PeriphDrivers/Source/I3C/i3c_reva.c
Default timeout values used for transactions fall short on large data transfers. Use data size and SCL frequency to calculate a proper timeout value.
Below formulas are used to come up with rough estimations.
`timeout = (40 * period_in_us) * writeCount`
`timeout = (80 * period_in_us) * readCount`
=> fix(PeriphDrivers): Calculate I3C timeout based on data size

.github/workflows/scripts/zephyr-hal.sh, Libraries/MAXUSB/include/core/usb_protocol.h, Libraries/MAXUSB/src/core/musbhsfc/usb.c, Libraries/zephyr/MAX/CMakeLists.txt
The purpose of this PR is enabling USB support for MAX32 MCUs on Zephyr RTOS. 
- Added required MAXUSB files into 'hal_adi' repository by updating CI workflow.
- Added these files into Zephyr source and include directories.
- Handled differences between MSDK and Zephyr with "USE_ZEPHYR_USB_STACK" flag and solved warning problem and race condition situation.
=> feat(Other): Enable USB support for Zephyr by adding MAXUSB

Libraries/CMSIS/Device/Maxim/MAX32657/Include/max32657.svd, Libraries/CMSIS/Device/Maxim/MAX32657/Include/trng_regs.h, Libraries/PeriphDrivers/Source/TRNG/trng_revc_me30.svd
The TRNG block for the MAX32657 does not support AES key generation. This PR removes all registers related to it.
=> fix(CMSIS): Remove AES Key Generation (unsupported) feature from MAX32657

Libraries/zephyr/MAX/Source/MAX32657/max32xxx_system.c
Enabling the instruction cache in the Zephyr startup.
=> fix(CMSIS): Enabling instruction cache.

Libraries/PeriphDrivers/Source/FLC/flc_me30.c
Erasing flash will also erase the ECC bits. These bits are not updated until a flash write. Reading from erased memory will signal a ECC error that is falsely corrected from 0xFF to 0xFD on the 16th byte of each 128-bit line.
This PR applies a workaround by setting the 16th byte of each line to 0xFF to handle this issue for max32657.
This is tested with zephyr/tests/drivers/flash/common. The result is indicated below.
=> fix(PeriphDrivers): Fix flash ecc issue for MAX32657

Libraries/PeriphDrivers/Include/MAX32657/uart.h, Libraries/PeriphDrivers/Source/UART/uart_me18.c, Libraries/PeriphDrivers/Source/UART/uart_me30.c, Libraries/zephyr/MAX/Include/wrap_max32_uart.h
This PR solves UART clock source selection problems for ME18 and ME30. Problems:
- For ME18, "MXC_UART_SetFrequency" function changes clock source but it is not a good approach. There is "MXC_UART_SetClockSource" function and user should use this function to change clock source of UART.
- Removed "MXC_UART_ERTCO_CLK" enum from ME30 files because it does not used by UART.
- Fixed build error of ME30 caused by "MSDK_NO_GPIO_CLK_INIT" flag's line.
- Moved clock source enablement into "MXC_UART_SetClockSource" function for ME30.
Also, this PR adds wrapper function of "MXC_UART_SetClockSource" to Zephyr "hal_adi" to enable clock source selection feature in Zephyr. It handles clock source index differences between MSDK and Zephyr.
=> fix(PeriphDrivers, Other): Fix UART clock source selection

Libraries/zephyr/MAX/Include/wrap_max32_dma.h
Add a DMA channel conversion function to convert chanel numbers between Zephyr and MSDK. For example, if an SoC has two DMA instances named DMA0 and DMA1, with 4 channels each, DMA1 channel numbers should be offset by 4 before passing to MSDK.
| Zephyr DMA0 | MSDK DMA0 |
|--------|--------|
| 0 | 0 |
| 1 | 1 |
| 2 | 2 |
| 3 | 3 |
| Zephyr DMA1 | MSDK DMA1 |
|--------|--------|
| 0 | 4 |
| 1 | 5 |
| 2 | 6 |
| 3 | 7 |
MAX32657 DMA is an exception to this.
=> feat(Other): Add DMA channel number conversion for Zephyr

Libraries/zephyr/MAX/Include/wrap_max32_can.h
The MSDK API for `MXC_CAN_Init` differs between the MAX32662 and MAX32690 boards. The former expects an additional GPIO configuration parameter. In Zephyr, because GPIO config is done by the zephyr layer and not msdk, this parameter is unused anyways (see `MSDK_NO_GPIO_CLK_INIT`).
This PR adds a `Wrap_MXC_CAN_Init` function to allow the `can_max32` driver (currently only available via innersource) to work on the MAX32662 as well (it currently only supports MAX32690). This seems to be the only tweak required to support this board.
I have tested that this properly works with a basic CAN send-recv example on a MAX32662 board and that it builds successfully for the MAX32690.
=> feat(Other): Add zephyr CAN wrapper for MAX32662, MAX32690

Examples/MAX32657/Bluetooth/BLE5_ctr/.vscode/launch.json, Examples/MAX32657/Hello_World/.vscode/launch.json, Examples/MAX32657/Hello_World_TZ/NonSecure/.vscode/launch.json, Examples/MAX32657/Hello_World_TZ/Secure/.vscode/launch.json
Removed RISC-V debug configurations from MAX32657 examples since the MAX32657 part does not have a RISC-V core.
Shipping this debug configuration with these examples can be confusing to the user.
=> fix(Examples): Remove RISC-V debug configs from MAX32657 examples

Libraries/Cordio/wsf/sources/targets/baremetal/wsf_trace.c
Conditionally check for trace being enabled to assert a trace callback. If there is no trace, we don't need a callback. This issue must have been introduced recently because we have not had this issue in the past. 
Address #1301
=> fix(BLE): WSF Assertion Checking for callback when not enabled. 

Libraries/PeriphDrivers/Source/ICC/icc_me30.c
MAX32657 cache controller only accessibly by secure world. 
This PR add guard to invalid access from non-secure world
=> fix(PeriphDrivers): MAX32657 Cache Access

Libraries/PeriphDrivers/Include/MAX32657/rtc.h, Libraries/PeriphDrivers/Source/RTC/rtc_me30.c, Libraries/zephyr/MAX/Include/wrap_max32_rtc.h
This PR solves RTC clock source selection problem for ME30. It adds a function to set clock source and creates wrapper function for MXC_RTC_Init to select clock source for ME30.
=> fix(PeriphDrivers, Other): Fix RTC clock source selection

Libraries/CMSIS/Device/Maxim/MAX32657/Include/max32657.svd, Libraries/CMSIS/Device/Maxim/MAX32657/Include/uart_regs.h, Libraries/PeriphDrivers/Source/UART/uart_revb_me30.svd
The UART PIN register is not supported for the MAX32657.
=> fix(CMSIS): Remove UART PIN register from MAX32657

Libraries/CMSIS/Device/Maxim/MAX32657/Include/gcr_regs.h, Libraries/CMSIS/Device/Maxim/MAX32657/Include/max32657.svd, Libraries/PeriphDrivers/Include/MAX32657/lp.h, Libraries/PeriphDrivers/Include/MAX32657/mxc_sys.h, Libraries/PeriphDrivers/Include/MAX32657/rtc.h, Libraries/PeriphDrivers/Source/LP/lp_me30.c, Libraries/PeriphDrivers/Source/RTC/rtc_me30.c, Libraries/PeriphDrivers/Source/SYS/SVD/gcr_me30.svd, Libraries/PeriphDrivers/Source/SYS/sys_me30.c, Libraries/zephyr/MAX/Include/wrap_max32_lp.h, Libraries/zephyr/MAX/Include/wrap_max32_rtc.h, Libraries/zephyr/MAX/Include/wrap_max32_sys.h
This PR updates MAX32657 low power API as listed below.
1. Implement standby mode. 
2. Implement SRAM retention.
3. Remove unsupported API functions.
4. Update _wrap_max32_lp.h_ to map wrapper functions to MAX32657 low power modes.
5. Fixed position of Wake-up Timer wake enable bit.
6. Moved 32K system clock source selection into sys_me30.c.
=> feat(PeriphDrivers): Implement low power modes for MAX32657

Libraries/PeriphDrivers/Include/MAX32657/mxc_sys.h, Libraries/PeriphDrivers/Source/LP/lp_me30.c, Libraries/PeriphDrivers/Source/SYS/sys_me30.c
Adding non-blocking functions for clock measurement. 
Clearing SLEEPDEEP bit after exiting standby mode. This will prevent the WFI instruction from causing the MCU to enter standby.
=> feat(PeriphDrivers): Add MAX32657 non-blocking clock measurement

Libraries/zephyr/MAX/Include/wrap_max32_flc.h
FLC write functions require disabling ICC first. I added this operation to fix problems of Zephyr flash tests for MAX32690 boards.
=> fix(Other): Add FLC wrap file to fix Zephyr flash problems for MAX32690

Libraries/zephyr/MAX/Include/wrap_max32_can.h
Fixes a bug introduced by #1306, which added a Zephyr wrapper for `MXC_CAN_Init`, whose signature differs between the MAX32662 and MAX32690.
The previous implementation declared `Wrap_MXC_CAN_Init` as `void` and discarded the return value of the underlying `MXC_CAN_Init` calls. This is incompatible with the can_max32 driver which does error checking and expects an `int` return value.
While this is a "breaking" change, no code currently depends on this wrapper, because its signature is invalid and could not be properly used in the can_max32 driver.
This is entirely my fault, as I was rushing to get some zephyr can_max32 changes in, on the last Friday before the winter holiday break. (I am now well aware of how stupid that is...)
While working on this wrapper, I used the following forks: …
=> fix(Other): Fix Wrap_MXC_CAN_Init signature

Examples/MAX32650/SPI/README.md, Examples/MAX32650/SPI/main.c, Examples/MAX32650/SPI/project.mk
Updated the MAX32650 SPI example project to allow the user to select the SPI instance to test. All of the driver logic remained the same, the additions updated the instance and IRQ constants and loopback instructions during startup, as well as documentation.
This was based on a customer request regarding confusion on the SPI drivers, as well as identifying the MISO and MOSI lines when leveraging SPI3.
=> feat(Examples): Expand MAX32650 SPI example to select SPI instance

.github/workflows/scripts/zephyr-hal.sh, .github/workflows/zephyr-hal.yml
Current workflow sends some commits which has only "msdk_sha" file change. To avoid these commits, I implemented a solution which protects "msdk_sha" file from remove operation.
Also, I updated workflow to send commits to "hal_adi" with same description and author information as MSDK commits.
=> ci(workflow): Update Zephyr-HAL workflow

Libraries/PeriphDrivers/Include/MAX78000/spi.h
This commit adds MXC_SPI_HWSSControl function declaration to the MAX78000 spi header.
- The MXC_SPI_HWSSControl function is implemented at spi_me17.c
but not declared for MAX78000 board. This commit adds MXC_SPI_HWSSControl
function declaration to the MAX78000 spi header.
=> feat(PeriphDrivers): Add MXC_SPI_HWSSControl declaration to MAX78000 spi.h

Libraries/zephyr/MAX/Source/MAX32650/CMakeLists.txt
This PR adds icc_common.c source file to the MAX32650 Cmake.
=> fix(Other): Fix MAX32650 zephyr cmake

Libraries/zephyr/MAX/Include/wrap_max32_lp.h
This commit adds the missing Low Power defines for MAX32650 for the zephyr build system.
There are generally two main groups in the wrap_max32_xx files. MAX32650 fits the first group for Low Power. However, there is no MXC_LP_EnterShutDownMode() function provided for MAX32650 so the MXC_LP_EnterBackupMode() function was chosen as best fit.
=> fix(Other): Zephyr: MAX32650: Add missing LP wrappers

Libraries/MAXUSB/include/core/usb.h, Libraries/MAXUSB/src/core/musbhsfc/usb.c
According to [USB 2.0 spec](https://www.usb.org/document-library/usb-20-specification); if data length is less than host requested and equal to or multiple of MPS, host requests ZLP to understand it is last packet.
<image src="https://github.com/user-attachments/assets/d3d4b6af-14da-4b95-8635-da79f2487fc3" width="700">
This patch adds `has_zlp` flag to `MXC_USB_Req_t `structure to understand if ZLP is needed. If `has_zlp `is set, ZLP is sent after data packet. This patch only has affects if driver used for Zephyr USB stack.
=> feat(MAXUSB): Add sending ZLP feature after data packet if it is needed

Libraries/PeriphDrivers/Source/HPB/hpb_me10.c, Libraries/PeriphDrivers/Source/HPB/hpb_me18.c
Matching other peripheral drivers, this makes clock and GPIO configuration optional if `MSDK_NO_GPIO_CLK_INIT` is defined, to be used by the HPB Zephyr driver which does it's own clock and pinctrl setup.
Second of two PRs to split up #1361
_______________________________________________________________________________
=> refactor(PeriphDrivers): Make HPB clock/gpio setup conditional

Examples/MAX32520/LP/README.md, Examples/MAX32520/LP/main.c, Examples/MAX32650/LP/README.md, Examples/MAX32650/LP/main.c, Examples/MAX32655/LP/README.md, Examples/MAX32655/LP/main.c, Examples/MAX32660/LP/README.md, Examples/MAX32660/LP/main.c, Examples/MAX32662/LP/README.md, Examples/MAX32662/LP/main.c, Examples/MAX32665/LP/README.md, Examples/MAX32665/LP/main.c, Examples/MAX32670/LP/README.md, Examples/MAX32670/LP/main.c, Examples/MAX32672/LP/README.md, Examples/MAX32672/LP/main.c, Examples/MAX32675/LP/README.md, Examples/MAX32675/LP/main.c, Examples/MAX32680/LP/README.md, Examples/MAX32680/LP/main.c, Examples/MAX32690/LP/README.md, Examples/MAX32690/LP/main.c, Examples/MAX78000/LP/README.md, Examples/MAX78000/LP/main.c, Examples/MAX78002/LP/README.md, Examples/MAX78002/LP/main.c
Add a 2-second delay to the beginning of ALL LP examples. Also add a warning snippet to the README regarding LP debug interface issues and a small snippet for implementing lockout protection via a GPIO input. 
Built all LP examples locally and using CI before creating PR. 
https://github.com/Brandon-Hurst/msdk/actions/runs/13186818626
=> fix(Examples): Add LP Lockout protection to all LP examples

Libraries/PeriphDrivers/Source/TRNG/trng_ai85.c, Libraries/PeriphDrivers/Source/TRNG/trng_ai87.c, Libraries/PeriphDrivers/Source/TRNG/trng_me10.c, Libraries/PeriphDrivers/Source/TRNG/trng_me12.c, Libraries/PeriphDrivers/Source/TRNG/trng_me14.c, Libraries/PeriphDrivers/Source/TRNG/trng_me15.c, Libraries/PeriphDrivers/Source/TRNG/trng_me16.c, Libraries/PeriphDrivers/Source/TRNG/trng_me17.c, Libraries/PeriphDrivers/Source/TRNG/trng_me18.c, Libraries/PeriphDrivers/Source/TRNG/trng_me20.c, Libraries/PeriphDrivers/Source/TRNG/trng_me21.c, Libraries/PeriphDrivers/Source/TRNG/trng_me30.c
TRNG clock setup depends on MSDK_NO_GPIO_CLK_INIT on initialization however it is disabled unconditionally on shutdown. Add the same dependency on shutdown too.
=> fix(PeriphDrivers): Make TRNG clock shutdown optional for all parts

Libraries/CMSIS/Device/Maxim/MAX32657/Include/mcr_regs.h, Libraries/PeriphDrivers/Source/LP/lp_me30.c, Libraries/zephyr/MAX/Include/wrap_max32_lp.h
Added wrapper functions for Zephyr use of Backup mode for MAX32657.
Part of enabling low-power mode integration in Zephyr
=> feat(PeriphDrivers): Add backup power mode wrappers

Libraries/zephyr/MAX/Include/wrap_max32_lp.h
Added ifdef guard to power modes for targets that
don't support backup or SRAM retention.
=> fix(PeriphDrivers): Guard power mode wrapper

Libraries/CMSIS/Device/Maxim/MAX32670/Source/system_max32670.c, Libraries/PeriphDrivers/Source/LP/lp_me15.c
The Max32670 LP and SYS driver functions currently have a couple small inaccuracies that are both capable of significantly mis-configuring the system under Low-Power use-cases. This was found by attempting to set Vcore in software using the SetOVR function in the LP driver, and also by trying to rely on its SystemClockUpdate call to automatically update the IPO when Vcore cannot drive a high-frequency clock. 
- Flash Controller LVE Bit set in lp_me15.c SetOVR function needs to be set when Vcore <= 1.0V. Currently checks only 0.9V.
- SystemClockUpdate function currently does not set IPO frequency properly accounting for the current Vcore / OVR setting. Added this change.
I validated this on the EV Kit Rev B with the attached code. This was able to set Vcore to 0.9V and correctly throttle …
=> fix(CMSIS, PeriphDrivers): Fix MAX32670 OVR & SystemCoreClock Update settings for LP operation

Libraries/PeriphDrivers/Source/UART/uart_revb.c
Currently, the private AsyncTxRequests and AsyncRxRequests arrays are used to track transactions in progress for uart_revb.c. The Tx/Rx Async Callbacks check for a callback function before clearing the Requests:
```C
mxc_uart_req_t *req = (mxc_uart_req_t *)AsyncTxRequests[uart_num];
if ((req != NULL) && (req->callback != NULL)) {
AsyncTxRequests[uart_num] = NULL;
req->callback(req, retVal);
}
```
This means that if the user does not supply an explicit callback function, a transaction never gets cleared, causing problems after just one transaction.
This commit resolves this by moving the cleanup of this important struct outside of the conditional check for a callback function.
```C
mxc_uart_req_t *req = (mxc_uart_req_t *)AsyncTxRequests[uart_num];
if ((req != NULL) && (req->callback != …
```
=> fix(PeriphDrivers): Fix UART RevB Driver not cleaning up Async Transactions

Libraries/PeriphDrivers/Source/FLC/flc_me10.c
Corrected a bug in how the flash physical address (relative to flash base) was calculated which caused a block of pages' addresses to be incorrectly masked. This ultimately caused issues when doing single page erases whenever bit 20 of the Flash address was set.
In the original implementation, -1 was done on the FLASH_MEM_SIZE to presumably get a valid mask. This works when the memory size is a power of 2.  However, since the memory on the MAX32650 is 3MB (0x300000), subtracting 1 results in a mask of 0x2FFFFF, where Bit 20 is 0.  All pages with Bit 20 set to 1 will have an incorrect address calculated.
The solution was to just subtract the base address, since the range was already validated in the if block.  This is the same implementation that the MAX32690 (also with 3MB of Flash) does.
=> fix(PeriphDrivers): MAX32650 (ME10) Flash Address Fix

Libraries/PeriphDrivers/Source/UART/uart_reva_me10.svd, Libraries/PeriphDrivers/Source/UART/uart_reva_me11.svd
This PR  fixes svd register names of
uart_reva_me10 and uart_reva_me11.
The names were changed because to add MAX32660 and
MAX32650 boards to the zephyr.
=> fix(PeriphDrivers): Fix Uart SVD register field names for MAX32650 and MAX32660

Libraries/PeriphDrivers/Source/SPI/spi_me10.c, Libraries/zephyr/MAX/Include/wrap_max32_dma.h, Libraries/zephyr/MAX/Include/wrap_max32_i2c.h, Libraries/zephyr/MAX/Include/wrap_max32_spi.h, Libraries/zephyr/MAX/Include/wrap_max32_tmr.h, Libraries/zephyr/MAX/Include/wrap_max32_wdt.h
This PR enables Zephyr support for MAX32650 for DMA, SPI, I2C, TMR and WDT peripherals by updating Zephyr wrapper files of these peripherals.
`spi_num` parameter causes "unused variable" warning. Because of that, I changed assert with an if condition which also checks instance limit.
=> feat(Other): Update Zephyr wrappers to enable MAX32650 support

Libraries/zephyr/MAX/Include/wrap_max32_tmr.h
This commit adds 'static inline' keywords to missed Zephyr timer wrapper functions to fix "multiply-defined symbols" errors.
=> fix(Other): Add 'static inline' keywords to Zephyr Timer Wrapper functions

Libraries/PeriphDrivers/Source/ADC/adc_ai87.c, Libraries/PeriphDrivers/Source/ADC/adc_me12.c, Libraries/PeriphDrivers/Source/ADC/adc_me18.c, Libraries/PeriphDrivers/Source/ADC/adc_me21.c
The loop in MXC_ADC_SlotConfiguration iterated one more than the number of slots passed in.
I can't think of any obvious reason why this is not incorrect.
=> fix(PeriphDrivers): Correct slot configuration loop in ADC SAR12

Libraries/PeriphDrivers/Source/SPI/spi_reva1.c
Fixes multiple potential issues with the SPI DMA handler which could cause SPI transactions to falsely get callbacks and terminated, or some transactions to never get callbacks or terminate under various conditions.
If there are 2 active SPI peripherals using DMA (for the example say SPI0 and SPI1).  If SPI0 is currently being configured via `MXC_SPI_RevA1_MasterTransactionDMA` and the DMA interrupt occurs for SPI1, it is possible for the interrupt to be handled as if SPI0 was the source, causing SPI1 to never complete.
This only occurs when the DMA interrupt happens between reassigning the state's req, and before clearing req_done https://github.com/analogdevicesinc/msdk/blob/2ec3f4ed1ecc5fafe1c687e61d1a38dc98220e76/Libraries/PeriphDrivers/Source/SPI/spi_reva1.c#L709
``` …
```
=> fix(PeriphDrivers): SPI RevA1 DMA Handler Fix

Libraries/PeriphDrivers/Source/SPI/spi_me18_v2.c
For MAX32690 there is a little mistake in the SPI_v2 configuration function. When Target Select for the SS1 is enabled SS0 gets  enabled instead.
This PR fixes this.
=> fix(PeriphDrivers): Fix SPIv2 TS1 GPIO init issue for MAX32690

Libraries/PeriphDrivers/Source/I2C/i2c_reva.c
In the Master Transaction function, add a checking to return BUSY if the I2C bus is not ready.
=> fix(PeriphDrivers): Issue #1293: MAX32670 I2C Driver causes a Double-Read

Libraries/PeriphDrivers/Include/MAX32650/lp.h, Libraries/zephyr/MAX/Include/wrap_max32_spi.h
This PR adds `MXC_LP_ClearWakeStatus` functions descriptor to MAX32650's `lp.h` header file to avoid warnings. Also, it adds correct SPI macros to Zephyr SPI wrapper file to solve build failure.
=> fix(PeriphDrivers, Other): Add missing parts for MAX32650

Libraries/zephyr/MAX/Include/wrap_max32_adc.h
There are BM driver changes in PR https://github.com/analogdevicesinc/msdk/pull/1386. These changes cause problem on Zephyr side. This PR updates Zephyr ADC wrapper according to ADC revB driver changes.
=> fix(Other): Update Zephyr ADC wrapper according to BM driver changes

Libraries/CMSIS/Device/Maxim/MAX32650/Source/sla_header_MAX32650.c, Libraries/zephyr/MAX/CMakeLists.txt, Libraries/zephyr/MAX/Source/MAX32650/CMakeLists.txt
This PR adds 'sla_header_MAX32650.c' file to Zephyr source library to implement SBT to Zephyr for MAX32651 SoC. It also defines 'USE_ZEPHYR_SECTIONS' flag because Zephyr has different section names. If this flag is defined, 'sb_header' structure will be placed in the '.rom_start' section.
=> feat(CMSIS, Other): Initial support for SBT implementation for MAX32651

Libraries/zephyr/MAX/Source/MAX32655/CMakeLists.txt, Libraries/zephyr/MAX/Source/MAX32680/CMakeLists.txt, Libraries/zephyr/MAX/Source/MAX32690/CMakeLists.txt, Libraries/zephyr/MAX/Source/MAX78000/CMakeLists.txt, Libraries/zephyr/MAX/Source/MAX78002/CMakeLists.txt
Enable the timer and GPIO peripheral code for a few more possible Zephyr Kconfig flags.
This is a precursor to expanded RV32 core Zephyr support, which includes a new system timer using a timer peripheral.
=> feat(Other): Adjust built drivers for new Zephyr configs

Libraries/PeriphDrivers/Source/FLC/flc_me18.c
When flushing after a flash operation, we should be flushing a different base address depending on which flash instance was involved in the operation.
Found this issue while working on support for flash operations from the RV32 core on MAX32690, using the FLC1 instance, since the RV32 core can't really use FLC0. Without the change, the flush attempts to access the flash base address that isn't even accessible to the RV32, which causes an exception.
Work around this by passing which flash instance was part of the operation to `MXC_FLC_ME18_Flash_Operation` so it can determine what base address to use for flushing the cache.
=> fix(PeriphDrivers): Flush using a per-instance base address.

Libraries/PeriphDrivers/Include/MAX32690/adc.h, Libraries/PeriphDrivers/Source/ADC/adc_me18.c, Libraries/PeriphDrivers/Source/ADC/adc_revb.c, Libraries/PeriphDrivers/Source/ADC/adc_revb.h, Libraries/zephyr/MAX/Include/wrap_max32_adc.h
Added functions are all new in order to not break anything existing. 
They are modification of existing functionalities but with 
different flags in order to achieve Zephyr stream with MAX32690 ADC.
=> feat(Other, PeriphDrivers): Add ADC support for Zephyr stream

Libraries/zephyr/MAX/Include/wrap_max32_sys.h
Some scenarios (power on reset, at least), trigger checksum failures on some supported targets, so disable checking the USN checksum by passing NULL for that parameter.
Some Zephyr tests (secure storage, hwinfo) encounter periodic failures, who's exact nature is still being investigated, but at a minimum:
* On MAX78002, the checksum process will fail for valid data on a power on reset. I suspect an issue with the AES peripheral, but that is still being investigated.
To avoid that specific issue, update our SYS wrapper to skip the checksum process (for now).
=> fix(Other): Skip USN checksum checking for Zephyr wrapper

Libraries/PeriphDrivers/Include/MAX32572/spi.h, Libraries/PeriphDrivers/Include/MAX32690/spi.h, Libraries/PeriphDrivers/Include/MAX78002/spi.h, Libraries/PeriphDrivers/Source/SPI/spi_reva2.c
This PR addresses three issues that were found with the SPI V2 driver code:
1. Some SPI and DMA interrupt flags were being cleared with |= potentially clearing other 1WC flags in the register.  This was addressed by replacing the '!=' operators with '=" operators where necessary.
2. The SPI START bit was being set before all other SPI configuration had been completed.  The fix here was to make sure the START bit was the last field to be set in each of the transaction functions.
3. There was no way to distinguish the reason for a callback being issued.  To resolve this, an enumeration of possible callback reasons was created.  The second parameter of the SPI callback function now contains one of the values from that enumeration to indicate the reason for the callback.
=> fix(PeriphDrivers): Fix limitations of the SPI V2 driver code

Libraries/PeriphDrivers/Source/I2C/i2c_reva.c
Add a waiting for the Transaction to finish between writing and reading section.
_______________________________________________________________________________
=> fix(PeriphDrivers): Update I2C driver which causes a Double-Read (#1293)

Libraries/PeriphDrivers/Source/I2S/i2s_reva.c
Fix bug in setting I2S RX threshold
We need to clear the field before or'ing in a new value.
Use the MXC_SETFIELD macro to do that.
In MXC_I2S_RevA_SetRXThreshold.
_______________________________________________________________________________
=> fix(PeriphDrivers): Fix setting of I2S RX Threshold

Libraries/PeriphDrivers/Source/DMA/dma_reva.c
while working on zephyr i2s drivers support for MAX32655, we found issue with priority. 
We found that OR'ing enum values could cause undefined behavior due to ctrl config corruption. 
we fixed it by shifting them to proper bit positions
=> fix(PeriphDrivers): Shift dma enum values to corresponding bit positions in adv config API

Libraries/CMSIS/Device/Maxim/MAX32690/Include/gcr_regs.h, Libraries/CMSIS/Device/Maxim/MAX32690/Include/max32690.svd, Libraries/PeriphDrivers/Source/LP/lp_me18.c, Libraries/PeriphDrivers/Source/SYS/SVD/gcr_me18.svd
Revision A4 and later of the device may inadvertently reset when exiting Standby or UPM if the power fail monitoring is enabled during these events.  The fix is to always disable the power fail reset just before entering one of these low power modes.  Once the part wakes up, the code then should wait for the power to be stable again before re-enabling the power fail monitor.
=> fix(PeriphDrivers): ME18-191: Add code to workaround a power fail issue when entering and exiting Standby or UPM modes on the MAX32690

Libraries/PeriphDrivers/Include/MAX78002/mxc_pins.h, Libraries/PeriphDrivers/Source/SYS/pins_ai87.c, Libraries/PeriphDrivers/Source/UART/uart_ai87.c
For MAX78002, if you tried to use the MXC_UART_SetFlowCtrl function, your code didn't build because it referenced undefined uart2 flow control pin variables.
Delete the code that used them, and also delete declarations of uart3 flow control pins, and declarations and definitions of uart1 flow control pins. The latter were set to P0.14 and P0.15 but those pins don't have UART signals on them according to the data sheet.
=> fix(PeriphDrivers): Remove unsupported UART flow control stuff

Libraries/PeriphDrivers/Source/ICC/icc_me10.c
The code was not properly disabling the ICC1 instance.
=> fix(PeriphDrivers): Fix an error in the MXC_ICC_Disable function of the MAX32650
