analogdevicesinc/msdk

- Tools/Bluetooth/RS_fsl3.py
> Fixing typo with class name.

- Examples/MAX78000/CNN/kws20_demo/README.md
- Examples/MAX78000/CNN/kws20_demo/Utility/bin2wav.py
- Add `-a` option to convert all sample audio files to wave in all subdirectories while skipping the ones that have already been converted.
- Update README.md file accordingly.
> Update `bin2wav.py' script

- Examples/MAX32680/AES/main.c
- Examples/MAX32680/DMA/main.c
- Examples/MAX32680/Flash/main.c
- Examples/MAX32680/Flash/project.mk
- Examples/MAX32680/Flash_CLI/main.c
- Examples/MAX32680/I2C/main.c
- Examples/MAX32680/I2C_SCAN/main.c
- Examples/MAX32680/I2S/main.c
- Examples/MAX32680/LP/main.c
- Examples/MAX32680/Watchdog/main.c
- Libraries/Boards/MAX32680/EvKit_V1/examples.txt
MAX32680 examples reviewed.
Detail [here](https://confluence.maxim-ic.com/display/MSW/MSDK+Example+Validation+and+Adding+Missing+Boards)
Unresolved JIRA tickets
[MAX32680](https://jira.maxim-ic.com/browse/MSDK-658)
> Dev me20 examples

- .gitignore
- Examples/MAX78002/ImgCapture/.cproject
- Examples/MAX78002/ImgCapture/.project
- Examples/MAX78002/ImgCapture/.settings/language.settings.xml
- Examples/MAX78002/ImgCapture/.settings/org.eclipse.cdt.codan.core.prefs
- Examples/MAX78002/ImgCapture/.settings/org.eclipse.cdt.core.prefs
- Examples/MAX78002/ImgCapture/.vscode/README.md
- Examples/MAX78002/ImgCapture/.vscode/c_cpp_properties.json
- Examples/MAX78002/ImgCapture/.vscode/flash.gdb
- Examples/MAX78002/ImgCapture/.vscode/launch.json
- Examples/MAX78002/ImgCapture/.vscode/settings.json
- Examples/MAX78002/ImgCapture/.vscode/tasks.json
- Examples/MAX78002/ImgCapture/ImgCapture.launch
For some reason project files for ImgCapture got lost in https://github.com/Analog-Devices-MSDK/msdk/pull/216 ...
Re-adding them here.
> Add ImgCapture Project Files

- Libraries/CMSIS/Device/Maxim/MAX32670/Include/max32670.svd
- Libraries/CMSIS/Device/Maxim/MAX32670/Include/pwrseq_regs.h
- Libraries/PeriphDrivers/Source/LP/pwrseq_me16.svd
- Libraries/PeriphDrivers/Source/SYS/SVD/gcr_me16.svd
Changes:
- Named PWRSEQ_LPCN[31] to ERTCO_PD.
- Removed PWRSEQ_LPCN[30] (TM_LPMODE).
- Added pwrseq_me16.svd since ME15B is different to the ME16.
> ME15: Named PWRSEQ_LPCN[31] to ERTCO_PD.

- Libraries/CMSIS/Device/Maxim/MAX32672/Include/max32672.h
- Libraries/CMSIS/Device/Maxim/MAX32672/Include/max32672.svd
- Libraries/PeriphDrivers/Source/CTB/ctb_reva.c
- Libraries/PeriphDrivers/Source/SYS/pins_me21.c
Most of the ME21-B2 examples worked out of the box, however a few examples required these small fixes.
> Bug fixes for ME21-B2 examples.

- Libraries/PeriphDrivers/Include/MAX32675/uart.h
- Libraries/PeriphDrivers/Source/UART/uart_me16.c
- Libraries/PeriphDrivers/Source/UART/uart_revb.c
Not sure if I missed anything. There were fewer changes than I thought...
> ME16: Updated WriteCharacter functions.

- Libraries/Boards/MAX32570/MN_EvKit_V1/Include/board.h
- Libraries/Boards/MAX32570/MN_EvKit_V1/Source/board.c
- Libraries/Boards/MAX32570/M_EvKit_V1/Include/board.h
- Libraries/Boards/MAX32570/M_EvKit_V1/Source/board.c
- Libraries/Boards/MAX32570/QN_EvKit_V1/Include/board.h
- Libraries/Boards/MAX32570/QN_EvKit_V1/Source/board.c
- Libraries/Boards/MAX32570/Q_EvKit_V1/Include/board.h
- Libraries/Boards/MAX32570/Q_EvKit_V1/Source/board.c
- Libraries/CMSIS/Device/Maxim/MAX32570/Include/max32570.h
- Libraries/MiscDrivers/Touchscreen/tsc2046.c
> ME13:  Fix tsc2046 build errors, add TS_SPI transport functions

- .github/workflows/ci-tests/Examples_tests/local_testLauncher.sh
device seems to have changed since the original file  was made
> wrong UART device

- Tools/Bluetooth/dtm_sweep.py
- Tools/Bluetooth/dtm_sweep_vs.py
For now I just renamed the vendor specific command script, but both DTMs are essentially the same, so we may just want to delete one.
> updated description texts for dtm sweep scripts and renamed vendor specific sweep script

- Libraries/Cordio/wsf/sources/targets/freertos/wsf_assert.c
- Libraries/Cordio/wsf/sources/targets/freertos/wsf_cs.c
- Libraries/Cordio/wsf/sources/targets/freertos/wsf_timer.c
Fixing a bug where the tail pointer is not updated when removing the tail item.
> Wsf freertos timer

- Libraries/Boards/MAX32690/Source/pb.c
- Libraries/PeriphDrivers/Source/GPIO/gpio_me18.c
This PR adds support for GPIO4 in the ME18 GPIO API. The ME18 pushbutton code was also updated to call the GPIO functions.
> MSDK-1013: Adding ME18 GPIO4 support.

- .gitignore
- Examples/MAX32655/BLE5_ctr/project.mk
- Examples/MAX32690/BLE5_ctr/project.mk
- Libraries/Cordio/platform/targets/maxim/max32655/sources/pal_sys.c
- Libraries/Cordio/platform/targets/maxim/max32665/sources/pal_sys.c
- Libraries/Cordio/platform/targets/maxim/max32690/sources/pal_sys.c
This partially reverts commit d0a34e3f32497625900c5a5ca2b1f46b26b54cbc.
> Reverting unintended changes made in EEPROM_Emulator add PR.

- .gitignore
- Libraries/Boards/MAX32690/TQFN_DB/Include/board.h
- Libraries/Boards/MAX32690/WLP_DB/Include/board.h
- Libraries/PeriphDrivers/Source/SYS/sys_me18.c
Added correct UART definitions for HCI and console on ME18 TQFN and WLP and changed Board name from WLP to TQFN in TQFN_DB
> Updated board files for ME18

- Documentation/build.py
- Examples/MAX32672/LP/lp-nonsecure.ld
- Examples/MAX32672/LP/lp-sla.ld
- Examples/MAX32672/LP/project.mk
Resolves #393 
@Jacob-Scheiffler can you check the other LP examples?  We may need this across the board.
> Add SBT vs non-SBT Linkerfile Selection to LP Example

- Examples/MAX32520/Hello_World/README.md
- Examples/MAX32572/Hello_World/README.md
- Examples/MAX32670/Hello_World/README.md
- Examples/MAX32672/Hello_World/README.md
- Examples/MAX32690/Hello_World/README.md
- Examples/MAX78002/Hello_World/README.md
The LED blinks at 1Hz, because a full cycle takes 1 second
> Minor correction in Documentation

- .github/workflows/BLE_Examples_Test.yml
- .gitignore
I also added the open PHY to the gitignore
> Unlocking boards if and only if that board was locked

- Tools/Bluetooth/BLE_hci.py
- Tools/Bluetooth/conn_sweep.py
On both BLE_hci.py and conn_sweep.py.
> Modified the PER timing

- Libraries/Cordio/platform/targets/maxim/max32655/sources/pal_cfg.c
- Libraries/Cordio/platform/targets/maxim/max32665/sources/pal_cfg.c
- Libraries/Cordio/platform/targets/maxim/max32690/sources/pal_cfg.c
@jhsiao2 Please test this PR on your setup for the ME18 WLP board. Thanks!
> fix me18 WLP_V1 PER failure

- Libraries/CMSIS/Device/Maxim/MAX32520/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX32570/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX32572/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX32650/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX32655/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX32660/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX32662/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX32665/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX32670/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX32672/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX32675/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX32680/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX32690/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX78000/Source/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/MAX78002/Source/GCC/gcc.mk
> Fix ln_args parsing bug on MSYS2

- .github/workflows/BLE_Examples_Test.yml
- .github/workflows/scripts/test_launcher.sh
simplifying otas test to a single bash function.
fixing issues caused by me forgetting to search for new string containing build Bootloader option, also updating test all options
> ble yml fix

- .github/workflows/scripts/test_launcher.sh
forgot  to update function call
> calls proper function

- .github/workflows/Build_Examples.yml
- .github/workflows/scripts/build.py
- Examples/MAX78000/Library_Use/project.mk
- Fix build workflow not checking out the correct ref
- Add explicit tests for rebuilding PeriphDrivers from scratch
- Improve build output clarity (colors!)
- Fix `Library_Use` build error for `BOARD=Aud01_RevA`
> Github Actions:  Fix Build Workflow, Improve Build Output

- Tools/Bluetooth/dtm_sweep_vs_allCh.py
Requires Install of msdk-test and measurement
> dtm sweep with better plotting

- Libraries/Cordio/platform/targets/maxim/max32665/sources/pal_timer.c
cleans up a trace output that I made ugly so that i can see it when it scrolls by
> Remove debug message

- Libraries/MAXUSB/Makefile
- Libraries/MAXUSB/include/devclass/ccid.h
- Libraries/MAXUSB/src/devclass/ccid.c
USB CCID device class implementation.
> Maxusb ccid implementation

- Examples/MAX78000/TMR/README.md
Jira ticket for this issue is [here](https://jira.maxim-ic.com/projects/MSDK/issues/MSDK-1187?filter=allopenissues)
> docs(Examples): Fix pin number for timer configuration

- Libraries/Cordio/docs/Applications/BLE_periph.md
A client recently could not get MTU to update because of missing step in our docs.
> docs(BLE): Update MTU configuration procedure

- Libraries/MiscDrivers/Camera/mipi_camera.c
This fixes a build regression that slipped through from #644
> fix(ignore): Fix MAX78002 Build Regression When OV5640_DVP is Defined

- Libraries/CMSIS/Device/Maxim/MAX32665/Include/max32665.svd
- Libraries/CMSIS/Device/Maxim/MAX32665/Include/owm_regs.h
- Libraries/PeriphDrivers/Source/OWM/owm_reva_me14.svd
https://github.com/Analog-Devices-MSDK/msdk/issues/688
> fix(CMSIS): Fix OWM_CTRL_STAT_PRES_DET field location for MAX32665

- Examples/MAX78000/CNN/facial_recognition/include/facedetection.h
- Examples/MAX78000/CNN/facial_recognition/include/tft_utils.h
- Examples/MAX78000/CNN/facial_recognition/main.c
- Examples/MAX78000/CNN/facial_recognition/src/faceID.c
- Examples/MAX78000/CNN/facial_recognition/src/facedetection.c
- Examples/MAX78000/CNN/facial_recognition/src/post_process.c
- Examples/MAX78000/CNN/facial_recognition/src/tft_utils.c
The facial-recognition demo is updated to use the DMA for writing the images to the FTHR TFT and improved the TFT update rate.
> feat(Examples): Speedup FTHR TFT update for facial-recognition demo for MAX78000

- .gitignore
Removed git sub module no longer included in msdk.
> fix(Examples): Removed dead submodule

- Libraries/CMSIS/Device/Maxim/GCC/gcc.mk
- Libraries/CMSIS/Device/Maxim/GCC/gcc_riscv.mk
This PR adds the following header string to the build output to help improve exposure to our UG, development, and support resources.
```serial
****************************************************************************
* Analog Devices MSDK
* - User Guide: https://analog-devices-msdk.github.io/msdk/USERGUIDE/
* - Get Support: https://www.analog.com/support/technical-support.html
* - Report Issues: https://github.com/Analog-Devices-MSDK/msdk/issues
* - Contributing: https://analog-devices-msdk.github.io/msdk/CONTRIBUTING/
****************************************************************************
```
> feat(Build): Add Helper String to Build Output

- Libraries/MAXUSB/include/core/maxq/usbio_maxq.h
> fix(MAXUSB): Remove unterminated #ifdef

- Libraries/Cordio/controller/sources/ble/lctr/lctr_int_adv_master_ae.h
- Libraries/Cordio/controller/sources/ble/lctr/lctr_main_adv_master_ae.c
- Libraries/Cordio/controller/sources/ble/lctr/lctr_main_conn.c
> fix(BLE): Add Parenthesis Around Some Cordio Ternaries

- Examples/MAX32690/I2C/main.c
- Libraries/Boards/MAX32690/EvKit_V1/Include/board.h
- Libraries/Boards/MAX32690/FTHR/Include/board.h
> fix(Examples): Highlight JP9/JP10 in printfs for MAX32690EVKIT I2C Example

- Libraries/MiscDrivers/Camera/camera.h
- Libraries/MiscDrivers/Camera/debayering.h
- Libraries/MiscDrivers/Camera/mipi_camera.h
- Libraries/MiscDrivers/Camera/sccb.h
- Libraries/MiscDrivers/Display/display.h
- Libraries/MiscDrivers/Display/sharp_mip.h
- Libraries/MiscDrivers/Display/ssd1306.h
- Libraries/MiscDrivers/Display/st7735s.h
- Libraries/MiscDrivers/Display/st7735s_cfaf128128b1.h
- Libraries/MiscDrivers/Display/tft_ili9341.h
- Libraries/MiscDrivers/Display/tft_ssd2119.h
- Libraries/MiscDrivers/Display/tft_st7735.h
- Libraries/MiscDrivers/Touchscreen/tsc2046.h
> fix(MiscDrivers): Add Missing C++ Guards to Camera and Display Files

- Examples/MAX32665/AUDIO_Playback/Makefile
- Examples/MAX32665/AUDIO_Playback/audio.c
- Examples/MAX32665/AUDIO_Playback/audio.h
- Examples/MAX32665/AUDIO_Playback/audio_regs.h
- Examples/MAX32665/AUDIO_Playback/main.c
- Examples/MAX32690/ADC/main.c
Did not check the copyright when this example was merged into main. In the process of creating a workflow that checks for the copyright.
> fix(Examples): Fix copyright in AUDIO_Playback example for MAX32665

- Examples/MAX32655/LP/main.c
Added Power Down LP Mode option. Tested with MAX32655 EvKit - grounding P3.0 on JH9 recovers from PDM mode.
> feat(Examples): MSDK-1243: Add Power Down Mode to MAX32655 LP Example

- Examples/MAX32665/SPI_3Wire/.cproject
- Examples/MAX32665/SPI_3Wire/.project
- Examples/MAX32665/SPI_3Wire/.settings/language.settings.xml
- Examples/MAX32665/SPI_3Wire/.settings/org.eclipse.cdt.codan.core.prefs
- Examples/MAX32665/SPI_3Wire/.settings/org.eclipse.cdt.core.prefs
- Examples/MAX32665/SPI_3Wire/.vscode/README.md
- Examples/MAX32665/SPI_3Wire/.vscode/c_cpp_properties.json
- Examples/MAX32665/SPI_3Wire/.vscode/flash.gdb
- Examples/MAX32665/SPI_3Wire/.vscode/launch.json
- Examples/MAX32665/SPI_3Wire/.vscode/settings.json
- Examples/MAX32665/SPI_3Wire/.vscode/tasks.json
- Examples/MAX32665/SPI_3Wire/Makefile
- Examples/MAX32665/SPI_3Wire/README.md
- Examples/MAX32665/SPI_3Wire/SPI_3Wire.launch
- Examples/MAX32665/SPI_3Wire/main.c
- Examples/MAX32665/SPI_3Wire/project.mk
- Libraries/Boards/MAX32665/FTHR/examples.txt
- Libraries/Boards/MAX32665/FTHR2/examples.txt
Add 3 Wire SPI example for MAX32665FTHR and MAX32665FTHR2
> feat(Examples): Add 3 Wire SPI example for MAX32665

- Libraries/CMSIS/Device/Maxim/MAX32690/Source/IAR/cmain.s
- Libraries/CMSIS/Device/Maxim/MAX32690/Source/IAR/heap.c
- Libraries/CMSIS/Device/Maxim/MAX32690/Source/IAR/low_level_init.c
- Libraries/CMSIS/Device/Maxim/MAX32690/Source/IAR/startup_max32690.s
This PR adds the necessary ME18 startup files for IAR. This allows for native support of the IAR new project package.
https://github.com/Analog-Devices-MSDK/IAR_Support_For_MAX32xxx
> feat(CMSIS): Add IAR startup files for MAX32690

- README.md
Fixes some broken links in the README, removes an outdated copy of the license text
> fix(Documentation): Fix Broken README Links

- Libraries/CMSIS/Device/Maxim/MAX32650/Include/max32650.h
> fix(PeriphDrivers): Add Missing SEC/MSEC/USEC Utility Macros to MAX32650

- Libraries/PeriphDrivers/Source/SPI/spi_me18.c
> fix(PeriphDrivers): Fix MAX32690 SPI DMA RX ReqSel for SPI 2, 3, and 4 

- .github/workflows/BLE_Examples_Test.yml
Update paths for BLE examples.
> fix(workflow): Update BLE examples path in BLE_Examples_Test workflow

- Libraries/MiscDrivers/Display/tft_ssd2119.c
Description
This PR refactors the SPI transmit for tft_ssd2119.
> fix(MiscDrivers): Refactor TFT SPI transmit for tft_ssd2119.

- Libraries/Cordio/controller/include/ble/ll_api.h
- Libraries/Cordio/controller/sources/ble/ll/ll_main_dtm.c
This is a simple API to check whether a test is running.
> feat(BLE): Added API to check whether a test is actively running 

- .clang-format
- .github/workflows/BLE_Examples_Test.yml
- .github/workflows/Build_Examples.yml
- .github/workflows/Generate_Register_Files.yml
- .github/workflows/PR_Title_Check.yml
- .github/workflows/Release.yml
- .github/workflows/Stale_PR.yml
- .github/workflows/Verify_Register_SVD.yml
- .github/workflows/build-cordio-platform-docs.yml
- .github/workflows/build-docs.yml
- .github/workflows/build-max32665-ds.yml
- .github/workflows/clang-format-check.yml
- .github/workflows/clang-format-run-pr.yml
- .github/workflows/clang-format-run.sh
- .github/workflows/labeler.yml
- .github/workflows/linter.yml
- .github/workflows/simple_per_test.yml
- .github/workflows/update_version.yml
This commit apply copyright change in https://github.com/analogdevicesinc/msdk/pull/941 PR to the github action files.
It is requires to to use file in hal_adi layer as it is. 
See: https://github.com/adi-innersource/hal_adi/pull/9#discussion_r1541221611
Related PR: https://github.com/adi-innersource/hal_adi/pull/9
> chore(workflow): Update copyrights

- .github/workflows/scripts/zephyr-hal.sh
- .github/workflows/zephyr-hal.yml
hal_adi includes exact copy of MSDK peripheral drivers and CMSIS files
This PR update script that copy files from MSDK to hal_adi
> ci(workflow): Copy MSDK peripheral files to hal_adi

- Examples/MAX78000/CNN/facial_recognition/db_gen/generate_face_db.py
- Examples/MAX78000/CNN/facial_recognition/db_gen/utils.py
- Examples/MAX78002/CNN/facial_recognition/db_gen/generate_face_db.py
- Examples/MAX78002/CNN/facial_recognition/db_gen/utils.py
- Examples/MAX78002/CNN/facial_recognition/src/record.c
fix(Examples) Face Detection Library Change for MAX78000, MAX78002 Facial Recognition Demos
Due to the broken checkpoint links, the face-detection library has been replaced with the batch-face. The batch-face provides the same speed and detection performance and keeps checkpoints on GitHub.
> fix(Examples): Face Detection Library Change for MAX78000, MAX78002 Facial Recognition Demos

- Libraries/Cordio/docs/CORDIO_USERGUIDE.md
add code snippet example for the following function in CORDIO_USERGUIDE.md: 
1. WSF_ASSERT
2. WSF_CS
3. WSF_BUF
4. WSF_MSG
5. WSF_TIMER
6. WSF_TRACE
7. WSF_NVM
> docs(BLE): Add Documentation for Wireless Stack Framework in CORDIO_USERGUIDE

- Examples/MAX32690/Bluetooth/BLE_otas/dats_main.c
Removed extra code left in otas
> fix(BLE): OTAS Example

- Examples/MAX32655/Bluetooth/BLE4_ctr/main.c
- Examples/MAX32655/Bluetooth/BLE5_ctr/main.c
- Examples/MAX32665/Bluetooth/BLE4_ctr/main.c
- Examples/MAX32665/Bluetooth/BLE5_ctr/main.c
- Examples/MAX32690/Bluetooth/BLE4_ctr/main.c
- Examples/MAX32690/Bluetooth/BLE5_ctr/main.c
- Libraries/Cordio/controller/include/common/chci_tr.h
- Libraries/Cordio/controller/sources/ble/lhci/lhci_cmd_vs.c
- Libraries/Cordio/controller/sources/ble/ll/ll_main_dtm.c
- Libraries/Cordio/controller/sources/common/chci/chci_tr.c
- Libraries/Cordio/wsf/include/wsf_os.h
- Libraries/Cordio/wsf/include/wsf_types.h
Updating an API in Libraries/Cordio to match a new Bluetooth library.
> refactor(BLE): Updating API to match new Library

- Libraries/libs.mk
- Libraries/lwIP/Maxim/freeRTOS/sys_arch.c
- Libraries/lwIP/Maxim/mxc_eth.c
- Libraries/lwIP/Maxim/mxc_ppp.c
- Libraries/lwIP/include/Maxim/arch/sys_arch.h
- Libraries/lwIP/include/Maxim/mxc_ppp.h
- USERGUIDE.md
Adds USS library support to libs.mk (enable via `LIB_USS = 1`).
Additionally adds some modifications to the lwIP stack to support the USS library.
> feat(ThirdParty): Add USS Library Support

- Libraries/Cordio/platform/include/pal_led.h
- Libraries/Cordio/platform/targets/maxim/build/libCordio.mk
- Libraries/Cordio/platform/targets/maxim/max32655/sources/pal_led.c
- Libraries/Cordio/platform/targets/maxim/max32690/sources/pal_led.c
Simplifying the LED interface that libphy uses. This will allow the higher layers to modify the pin locations and even disable the LED functionality of libphy.
> refactor(BLE): Simplifying LED interface with libphy.

- Libraries/PeriphDrivers/Include/MAX32520/spi.h
- Libraries/PeriphDrivers/Include/MAX32570/spi.h
- Libraries/PeriphDrivers/Include/MAX32572/spi.h
- Libraries/PeriphDrivers/Include/MAX32650/spi.h
- Libraries/PeriphDrivers/Include/MAX32655/spi.h
- Libraries/PeriphDrivers/Include/MAX32657/spi.h
- Libraries/PeriphDrivers/Include/MAX32660/spi.h
- Libraries/PeriphDrivers/Include/MAX32662/spi.h
- Libraries/PeriphDrivers/Include/MAX32665/spi.h
- Libraries/PeriphDrivers/Include/MAX32670/spi.h
- Libraries/PeriphDrivers/Include/MAX32672/spi.h
- Libraries/PeriphDrivers/Include/MAX32675/spi.h
- Libraries/PeriphDrivers/Include/MAX32680/spi.h
- Libraries/PeriphDrivers/Include/MAX32690/spi.h
- Libraries/PeriphDrivers/Include/MAX78000/spi.h
- Libraries/PeriphDrivers/Include/MAX78002/spi.h
> fix(Documentation): Fix Inaccurate SPI Threshold Docstrings

- Examples/MAX78002/CNN/pascalvoc-retinanetv7_3/.cproject
- Examples/MAX78002/CNN/pascalvoc-retinanetv7_3/.vscode/settings.json
> fix(Other): Update pascalvoc-retinanetv7_3 Eclipse Include Paths

- Libraries/PeriphDrivers/Source/TMR/tmr_revb.c
We passed in the clock source instead of the prescaler to MXC_TMR_RevB_SetPrescalar. Fix to pass in cfs->pres.
The MSDK repo follows a custom rule set based on the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard. The pull request titles will follow this format:
`type(scope)<!>: Subject`
The list of possible types are:
1.  **fix** – a bug fix has occurred
2.  **feat** – a new feature was introduced
3.  **chore** – changes that do not relate to a fix or feature, or a catch-all type for changes that don’t really fit under any of the other types
4.  **refactor** – refactored code that neither fixes a bug nor adds a new feature
5.  **docs** – updates to documentation
6.  **style** – code styling changes (linter or clang-format)
7.  **test** – changes involving …
> fix(PeriphDrivers): Fix TMR prescaler for revb

- Libraries/PeriphDrivers/Source/GPIO/gpio_me14.c
This commit add strength selection for output mode.
> fix(PeriphDrivers): Add Strength Configuration for ME14

- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/.cproject
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/.project
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/.settings/language.settings.xml
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/.settings/org.eclipse.cdt.codan.core.prefs
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/.settings/org.eclipse.cdt.core.prefs
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/.vscode/README.md
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/.vscode/c_cpp_properties.json
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/.vscode/flash.gdb
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/.vscode/launch.json
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/.vscode/settings.json
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/.vscode/tasks.json
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/Makefile
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/README.md
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/main.c
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/msc_ext_flash.c
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/msc_ext_flash.launch
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/project.mk
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/tusb_config.h
- Examples/MAX32690/USB/TinyUSB/msc_ext_flash/usb_descriptors.c
- Libraries/Boards/MAX32690/APARD/Source/board.c
- Libraries/PeriphDrivers/Source/SPIXF/spixf_me18.c
Adds a TinyUSB mass storage example project, reading/writing to the SPIXF device on the AD-APARD32690 board.  
Also includes minor updates to the BSP and PeriphDriver for correct operation of the SPIXF.
> feat(Examples): MAX32690 TInyUSB MSC + External Flash Example

- .github/pull_request_template.md
This PR updates the PR template so users know they need to delete the unnecessary parts.
> fix(Other): Add `delete me warning` in PR template

- Libraries/Cordio/platform/include/pal_bb.h
- Added declaration for PalBbIsEnabled
> chore(BLE): Added Declaration for PalBbIsEnabled

- Examples/MAX32655/Bluetooth/RF_Test/main.c
- Examples/MAX32665/Bluetooth/RF_Test/main.c
- Examples/MAX32690/Bluetooth/RF_Test/main.c
- Updated PHY optons to correct values
> fix(Examples): RF Test

- Libraries/libs.mk
- Added flag to select BLE_API directory
> build(ThirdParty): Added flag to select BLE_API directory

- Libraries/zephyr/MAX/Source/MAX32655/CMakeLists.txt
- Libraries/zephyr/MAX/Source/MAX32657/CMakeLists.txt
- Libraries/zephyr/MAX/Source/MAX32662/CMakeLists.txt
- Libraries/zephyr/MAX/Source/MAX32665/CMakeLists.txt
- Libraries/zephyr/MAX/Source/MAX32670/CMakeLists.txt
- Libraries/zephyr/MAX/Source/MAX32672/CMakeLists.txt
- Libraries/zephyr/MAX/Source/MAX32675/CMakeLists.txt
- Libraries/zephyr/MAX/Source/MAX32680/CMakeLists.txt
- Libraries/zephyr/MAX/Source/MAX32690/CMakeLists.txt
- Libraries/zephyr/MAX/Source/MAX78002/CMakeLists.txt
This PR adds Zephyr hwinfo driver's dependencies to zephyr_library_sources.
> feat(Other): Add Zephyr hwinfo driver's dependencies

- Libraries/zephyr/MAX/Include/wrap_max32_usb.h
This PR creates Zephyr USB wrapper for SoC specific initialization steps.
> feat(Other): Add USB wrapper file

- .github/workflows/zephyr-hal.yml
Updated paths in zephyr-hal.yml to fix path issue also added global user information back.
Example error link: https://github.com/analogdevicesinc/msdk/actions/runs/13215285065/job/36893810255
> fix(Other): Fix zephyr-hal.yml path issue

- Libraries/CMSIS/Device/Maxim/MAX32660/Include/uart_regs.h
- Libraries/zephyr/MAX/Include/wrap_max32_sys.h
- Libraries/zephyr/MAX/Include/wrap_max32_uart.h
- Libraries/zephyr/MAX/Source/MAX32660/CMakeLists.txt
- Libraries/zephyr/MAX/Source/MAX32660/max32xxx_system.c
This PR adds MAX32660 hal files for zephyr support.
> feat(Other): Add MAX32660 Zephyr Support

- Libraries/PeriphDrivers/Include/MAX32657/lp.h
- Libraries/PeriphDrivers/Source/LP/lp_me30.c
- Libraries/zephyr/MAX/Include/wrap_max32_lp.h
Added exit wrappers for leaving Backup mode and restoring system
> feat(PeriphDrivers): Added backup mode exit wrappers

- Libraries/PeriphDrivers/Source/I3C/i3c_reva.c
Rework I3C clock calculation.
Adjust duty cycle to achieve lower push-pull frequencies. Handle rounding errors to achieve frequencies as close as possible to the requested rates.
> fix(PeriphDrivers): Rework I3C clock calculation

- .github/workflows/zephyr-hal.yml
Two small fixes for the new Zephyr HAL export:
* Explicitly set the git user config
* When pushing, set an upstream target for the push.
> ci(workflow): A few Zephyr HAL export fixes
